// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package byreal_clmm

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("REALQqNEomY6cQGZJUGwywTBD2UmDT32rZcNnfxQ5N2")
