// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package whirlpool

// Account discriminators
var (
	Account_WhirlpoolsConfigExtension = [8]byte{2, 99, 215, 163, 240, 26, 153, 58}
	Account_WhirlpoolsConfig          = [8]byte{157, 20, 49, 224, 217, 87, 193, 254}
	Account_FeeTier                   = [8]byte{56, 75, 159, 76, 142, 68, 190, 105}
	Account_PositionBundle            = [8]byte{129, 169, 175, 65, 185, 95, 32, 100}
	Account_Position                  = [8]byte{170, 188, 143, 228, 122, 64, 247, 208}
	Account_TickArray                 = [8]byte{69, 97, 189, 190, 110, 7, 66, 187}
	Account_TokenBadge                = [8]byte{116, 219, 204, 229, 249, 116, 255, 150}
	Account_Whirlpool                 = [8]byte{63, 149, 209, 12, 225, 128, 99, 9}
)

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_InitializeConfig                     = [8]byte{208, 127, 21, 1, 194, 190, 196, 70}
	Instruction_InitializePool                       = [8]byte{95, 180, 10, 172, 84, 174, 232, 40}
	Instruction_InitializeTickArray                  = [8]byte{11, 188, 193, 214, 141, 91, 149, 184}
	Instruction_InitializeFeeTier                    = [8]byte{183, 74, 156, 160, 112, 2, 42, 30}
	Instruction_InitializeReward                     = [8]byte{95, 135, 192, 196, 242, 129, 230, 68}
	Instruction_SetRewardEmissions                   = [8]byte{13, 197, 86, 168, 109, 176, 27, 244}
	Instruction_OpenPosition                         = [8]byte{135, 128, 47, 77, 15, 152, 240, 49}
	Instruction_OpenPositionWithMetadata             = [8]byte{242, 29, 134, 48, 58, 110, 14, 60}
	Instruction_IncreaseLiquidity                    = [8]byte{46, 156, 243, 118, 13, 205, 251, 178}
	Instruction_DecreaseLiquidity                    = [8]byte{160, 38, 208, 111, 104, 91, 44, 1}
	Instruction_UpdateFeesAndRewards                 = [8]byte{154, 230, 250, 13, 236, 209, 75, 223}
	Instruction_CollectFees                          = [8]byte{164, 152, 207, 99, 30, 186, 19, 182}
	Instruction_CollectReward                        = [8]byte{70, 5, 132, 87, 86, 235, 177, 34}
	Instruction_CollectProtocolFees                  = [8]byte{22, 67, 23, 98, 150, 178, 70, 220}
	Instruction_Swap                                 = [8]byte{248, 198, 158, 145, 225, 117, 135, 200}
	Instruction_ClosePosition                        = [8]byte{123, 134, 81, 0, 49, 68, 98, 98}
	Instruction_SetDefaultFeeRate                    = [8]byte{118, 215, 214, 157, 182, 229, 208, 228}
	Instruction_SetDefaultProtocolFeeRate            = [8]byte{107, 205, 249, 226, 151, 35, 86, 0}
	Instruction_SetFeeRate                           = [8]byte{53, 243, 137, 65, 8, 140, 158, 6}
	Instruction_SetProtocolFeeRate                   = [8]byte{95, 7, 4, 50, 154, 79, 156, 131}
	Instruction_SetFeeAuthority                      = [8]byte{31, 1, 50, 87, 237, 101, 97, 132}
	Instruction_SetCollectProtocolFeesAuthority      = [8]byte{34, 150, 93, 244, 139, 225, 233, 67}
	Instruction_SetRewardAuthority                   = [8]byte{34, 39, 183, 252, 83, 28, 85, 127}
	Instruction_SetRewardAuthorityBySuperAuthority   = [8]byte{240, 154, 201, 198, 148, 93, 56, 25}
	Instruction_SetRewardEmissionsSuperAuthority     = [8]byte{207, 5, 200, 209, 122, 56, 82, 183}
	Instruction_TwoHopSwap                           = [8]byte{195, 96, 237, 108, 68, 162, 219, 230}
	Instruction_InitializePositionBundle             = [8]byte{117, 45, 241, 149, 24, 18, 194, 65}
	Instruction_InitializePositionBundleWithMetadata = [8]byte{93, 124, 16, 179, 249, 131, 115, 245}
	Instruction_DeletePositionBundle                 = [8]byte{100, 25, 99, 2, 217, 239, 124, 173}
	Instruction_OpenBundledPosition                  = [8]byte{169, 113, 126, 171, 213, 172, 212, 49}
	Instruction_CloseBundledPosition                 = [8]byte{41, 36, 216, 245, 27, 85, 103, 67}
	Instruction_CollectFeesV2                        = [8]byte{207, 117, 95, 191, 229, 180, 226, 15}
	Instruction_CollectProtocolFeesV2                = [8]byte{103, 128, 222, 134, 114, 200, 22, 200}
	Instruction_CollectRewardV2                      = [8]byte{177, 107, 37, 180, 160, 19, 49, 209}
	Instruction_DecreaseLiquidityV2                  = [8]byte{58, 127, 188, 62, 79, 82, 196, 96}
	Instruction_IncreaseLiquidityV2                  = [8]byte{133, 29, 89, 223, 69, 238, 176, 10}
	Instruction_InitializePoolV2                     = [8]byte{207, 45, 87, 242, 27, 63, 204, 67}
	Instruction_InitializeRewardV2                   = [8]byte{91, 1, 77, 50, 235, 229, 133, 49}
	Instruction_SetRewardEmissionsV2                 = [8]byte{114, 228, 72, 32, 193, 48, 160, 102}
	Instruction_SwapV2                               = [8]byte{43, 4, 237, 11, 26, 201, 30, 98}
	Instruction_TwoHopSwapV2                         = [8]byte{186, 143, 209, 29, 254, 2, 194, 117}
	Instruction_InitializeConfigExtension            = [8]byte{55, 9, 53, 9, 114, 57, 209, 52}
	Instruction_SetConfigExtensionAuthority          = [8]byte{44, 94, 241, 116, 24, 188, 60, 143}
	Instruction_SetTokenBadgeAuthority               = [8]byte{207, 202, 4, 32, 205, 79, 13, 178}
	Instruction_InitializeTokenBadge                 = [8]byte{253, 77, 205, 95, 27, 224, 89, 223}
	Instruction_DeleteTokenBadge                     = [8]byte{53, 146, 68, 8, 18, 117, 17, 185}
)
