// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package whirlpool

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type OpenPositionBumps struct {
	PositionBump uint8 `json:"positionBump"`
}

func (obj OpenPositionBumps) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PositionBump`:
	err = encoder.Encode(obj.PositionBump)
	if err != nil {
		return errors.NewField("PositionBump", err)
	}
	return nil
}

func (obj OpenPositionBumps) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OpenPositionBumps: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OpenPositionBumps) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PositionBump`:
	err = decoder.Decode(&obj.PositionBump)
	if err != nil {
		return errors.NewField("PositionBump", err)
	}
	return nil
}

func (obj *OpenPositionBumps) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OpenPositionBumps: %w", err)
	}
	return nil
}

func UnmarshalOpenPositionBumps(buf []byte) (*OpenPositionBumps, error) {
	obj := new(OpenPositionBumps)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type OpenPositionWithMetadataBumps struct {
	PositionBump uint8 `json:"positionBump"`
	MetadataBump uint8 `json:"metadataBump"`
}

func (obj OpenPositionWithMetadataBumps) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PositionBump`:
	err = encoder.Encode(obj.PositionBump)
	if err != nil {
		return errors.NewField("PositionBump", err)
	}
	// Serialize `MetadataBump`:
	err = encoder.Encode(obj.MetadataBump)
	if err != nil {
		return errors.NewField("MetadataBump", err)
	}
	return nil
}

func (obj OpenPositionWithMetadataBumps) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding OpenPositionWithMetadataBumps: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *OpenPositionWithMetadataBumps) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PositionBump`:
	err = decoder.Decode(&obj.PositionBump)
	if err != nil {
		return errors.NewField("PositionBump", err)
	}
	// Deserialize `MetadataBump`:
	err = decoder.Decode(&obj.MetadataBump)
	if err != nil {
		return errors.NewField("MetadataBump", err)
	}
	return nil
}

func (obj *OpenPositionWithMetadataBumps) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling OpenPositionWithMetadataBumps: %w", err)
	}
	return nil
}

func UnmarshalOpenPositionWithMetadataBumps(buf []byte) (*OpenPositionWithMetadataBumps, error) {
	obj := new(OpenPositionWithMetadataBumps)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PositionRewardInfo struct {
	GrowthInsideCheckpoint binary.Uint128 `json:"growthInsideCheckpoint"`
	AmountOwed             uint64         `json:"amountOwed"`
}

func (obj PositionRewardInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `GrowthInsideCheckpoint`:
	err = encoder.Encode(obj.GrowthInsideCheckpoint)
	if err != nil {
		return errors.NewField("GrowthInsideCheckpoint", err)
	}
	// Serialize `AmountOwed`:
	err = encoder.Encode(obj.AmountOwed)
	if err != nil {
		return errors.NewField("AmountOwed", err)
	}
	return nil
}

func (obj PositionRewardInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PositionRewardInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PositionRewardInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `GrowthInsideCheckpoint`:
	err = decoder.Decode(&obj.GrowthInsideCheckpoint)
	if err != nil {
		return errors.NewField("GrowthInsideCheckpoint", err)
	}
	// Deserialize `AmountOwed`:
	err = decoder.Decode(&obj.AmountOwed)
	if err != nil {
		return errors.NewField("AmountOwed", err)
	}
	return nil
}

func (obj *PositionRewardInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PositionRewardInfo: %w", err)
	}
	return nil
}

func UnmarshalPositionRewardInfo(buf []byte) (*PositionRewardInfo, error) {
	obj := new(PositionRewardInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Tick struct {
	Initialized          bool              `json:"initialized"`
	LiquidityNet         binary.Int128     `json:"liquidityNet"`
	LiquidityGross       binary.Uint128    `json:"liquidityGross"`
	FeeGrowthOutsideA    binary.Uint128    `json:"feeGrowthOutsideA"`
	FeeGrowthOutsideB    binary.Uint128    `json:"feeGrowthOutsideB"`
	RewardGrowthsOutside [3]binary.Uint128 `json:"rewardGrowthsOutside"`
}

func (obj Tick) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Initialized`:
	err = encoder.Encode(obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Serialize `LiquidityNet`:
	err = encoder.Encode(obj.LiquidityNet)
	if err != nil {
		return errors.NewField("LiquidityNet", err)
	}
	// Serialize `LiquidityGross`:
	err = encoder.Encode(obj.LiquidityGross)
	if err != nil {
		return errors.NewField("LiquidityGross", err)
	}
	// Serialize `FeeGrowthOutsideA`:
	err = encoder.Encode(obj.FeeGrowthOutsideA)
	if err != nil {
		return errors.NewField("FeeGrowthOutsideA", err)
	}
	// Serialize `FeeGrowthOutsideB`:
	err = encoder.Encode(obj.FeeGrowthOutsideB)
	if err != nil {
		return errors.NewField("FeeGrowthOutsideB", err)
	}
	// Serialize `RewardGrowthsOutside`:
	err = encoder.Encode(obj.RewardGrowthsOutside)
	if err != nil {
		return errors.NewField("RewardGrowthsOutside", err)
	}
	return nil
}

func (obj Tick) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Tick: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Tick) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Initialized`:
	err = decoder.Decode(&obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Deserialize `LiquidityNet`:
	err = decoder.Decode(&obj.LiquidityNet)
	if err != nil {
		return errors.NewField("LiquidityNet", err)
	}
	// Deserialize `LiquidityGross`:
	err = decoder.Decode(&obj.LiquidityGross)
	if err != nil {
		return errors.NewField("LiquidityGross", err)
	}
	// Deserialize `FeeGrowthOutsideA`:
	err = decoder.Decode(&obj.FeeGrowthOutsideA)
	if err != nil {
		return errors.NewField("FeeGrowthOutsideA", err)
	}
	// Deserialize `FeeGrowthOutsideB`:
	err = decoder.Decode(&obj.FeeGrowthOutsideB)
	if err != nil {
		return errors.NewField("FeeGrowthOutsideB", err)
	}
	// Deserialize `RewardGrowthsOutside`:
	err = decoder.Decode(&obj.RewardGrowthsOutside)
	if err != nil {
		return errors.NewField("RewardGrowthsOutside", err)
	}
	return nil
}

func (obj *Tick) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Tick: %w", err)
	}
	return nil
}

func UnmarshalTick(buf []byte) (*Tick, error) {
	obj := new(Tick)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WhirlpoolRewardInfo struct {
	Mint                  solanago.PublicKey `json:"mint"`
	Vault                 solanago.PublicKey `json:"vault"`
	Authority             solanago.PublicKey `json:"authority"`
	EmissionsPerSecondX64 binary.Uint128     `json:"emissionsPerSecondX64"`
	GrowthGlobalX64       binary.Uint128     `json:"growthGlobalX64"`
}

func (obj WhirlpoolRewardInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Vault`:
	err = encoder.Encode(obj.Vault)
	if err != nil {
		return errors.NewField("Vault", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `EmissionsPerSecondX64`:
	err = encoder.Encode(obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	// Serialize `GrowthGlobalX64`:
	err = encoder.Encode(obj.GrowthGlobalX64)
	if err != nil {
		return errors.NewField("GrowthGlobalX64", err)
	}
	return nil
}

func (obj WhirlpoolRewardInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WhirlpoolRewardInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WhirlpoolRewardInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Vault`:
	err = decoder.Decode(&obj.Vault)
	if err != nil {
		return errors.NewField("Vault", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `EmissionsPerSecondX64`:
	err = decoder.Decode(&obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	// Deserialize `GrowthGlobalX64`:
	err = decoder.Decode(&obj.GrowthGlobalX64)
	if err != nil {
		return errors.NewField("GrowthGlobalX64", err)
	}
	return nil
}

func (obj *WhirlpoolRewardInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WhirlpoolRewardInfo: %w", err)
	}
	return nil
}

func UnmarshalWhirlpoolRewardInfo(buf []byte) (*WhirlpoolRewardInfo, error) {
	obj := new(WhirlpoolRewardInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WhirlpoolBumps struct {
	WhirlpoolBump uint8 `json:"whirlpoolBump"`
}

func (obj WhirlpoolBumps) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WhirlpoolBump`:
	err = encoder.Encode(obj.WhirlpoolBump)
	if err != nil {
		return errors.NewField("WhirlpoolBump", err)
	}
	return nil
}

func (obj WhirlpoolBumps) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WhirlpoolBumps: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WhirlpoolBumps) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WhirlpoolBump`:
	err = decoder.Decode(&obj.WhirlpoolBump)
	if err != nil {
		return errors.NewField("WhirlpoolBump", err)
	}
	return nil
}

func (obj *WhirlpoolBumps) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WhirlpoolBumps: %w", err)
	}
	return nil
}

func UnmarshalWhirlpoolBumps(buf []byte) (*WhirlpoolBumps, error) {
	obj := new(WhirlpoolBumps)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type RemainingAccountsSlice struct {
	AccountsType AccountsType `json:"accountsType"`
	Length       uint8        `json:"length"`
}

func (obj RemainingAccountsSlice) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `AccountsType`:
	err = encoder.Encode(obj.AccountsType)
	if err != nil {
		return errors.NewField("AccountsType", err)
	}
	// Serialize `Length`:
	err = encoder.Encode(obj.Length)
	if err != nil {
		return errors.NewField("Length", err)
	}
	return nil
}

func (obj RemainingAccountsSlice) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding RemainingAccountsSlice: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *RemainingAccountsSlice) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `AccountsType`:
	err = decoder.Decode(&obj.AccountsType)
	if err != nil {
		return errors.NewField("AccountsType", err)
	}
	// Deserialize `Length`:
	err = decoder.Decode(&obj.Length)
	if err != nil {
		return errors.NewField("Length", err)
	}
	return nil
}

func (obj *RemainingAccountsSlice) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling RemainingAccountsSlice: %w", err)
	}
	return nil
}

func UnmarshalRemainingAccountsSlice(buf []byte) (*RemainingAccountsSlice, error) {
	obj := new(RemainingAccountsSlice)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type RemainingAccountsInfo struct {
	Slices []RemainingAccountsSlice `json:"slices"`
}

func (obj RemainingAccountsInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Slices`:
	err = encoder.Encode(obj.Slices)
	if err != nil {
		return errors.NewField("Slices", err)
	}
	return nil
}

func (obj RemainingAccountsInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding RemainingAccountsInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *RemainingAccountsInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Slices`:
	err = decoder.Decode(&obj.Slices)
	if err != nil {
		return errors.NewField("Slices", err)
	}
	return nil
}

func (obj *RemainingAccountsInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling RemainingAccountsInfo: %w", err)
	}
	return nil
}

func UnmarshalRemainingAccountsInfo(buf []byte) (*RemainingAccountsInfo, error) {
	obj := new(RemainingAccountsInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CurrIndex binary.BorshEnum

const (
	CurrIndex_Below CurrIndex = iota
	CurrIndex_Inside
	CurrIndex_Above
)

func (value CurrIndex) String() string {
	switch value {
	case CurrIndex_Below:
		return "Below"
	case CurrIndex_Inside:
		return "Inside"
	case CurrIndex_Above:
		return "Above"
	default:
		return ""
	}
}

type TickLabel binary.BorshEnum

const (
	TickLabel_Upper TickLabel = iota
	TickLabel_Lower
)

func (value TickLabel) String() string {
	switch value {
	case TickLabel_Upper:
		return "Upper"
	case TickLabel_Lower:
		return "Lower"
	default:
		return ""
	}
}

type Direction binary.BorshEnum

const (
	Direction_Left Direction = iota
	Direction_Right
)

func (value Direction) String() string {
	switch value {
	case Direction_Left:
		return "Left"
	case Direction_Right:
		return "Right"
	default:
		return ""
	}
}

type AccountsType binary.BorshEnum

const (
	AccountsType_TransferHookA AccountsType = iota
	AccountsType_TransferHookB
	AccountsType_TransferHookReward
	AccountsType_TransferHookInput
	AccountsType_TransferHookIntermediate
	AccountsType_TransferHookOutput
	AccountsType_SupplementalTickArrays
	AccountsType_SupplementalTickArraysOne
	AccountsType_SupplementalTickArraysTwo
)

func (value AccountsType) String() string {
	switch value {
	case AccountsType_TransferHookA:
		return "TransferHookA"
	case AccountsType_TransferHookB:
		return "TransferHookB"
	case AccountsType_TransferHookReward:
		return "TransferHookReward"
	case AccountsType_TransferHookInput:
		return "TransferHookInput"
	case AccountsType_TransferHookIntermediate:
		return "TransferHookIntermediate"
	case AccountsType_TransferHookOutput:
		return "TransferHookOutput"
	case AccountsType_SupplementalTickArrays:
		return "SupplementalTickArrays"
	case AccountsType_SupplementalTickArraysOne:
		return "SupplementalTickArraysOne"
	case AccountsType_SupplementalTickArraysTwo:
		return "SupplementalTickArraysTwo"
	default:
		return ""
	}
}

type WhirlpoolsConfigExtension struct {
	WhirlpoolsConfig         solanago.PublicKey `json:"whirlpoolsConfig"`
	ConfigExtensionAuthority solanago.PublicKey `json:"configExtensionAuthority"`
	TokenBadgeAuthority      solanago.PublicKey `json:"tokenBadgeAuthority"`
}

func (obj WhirlpoolsConfigExtension) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WhirlpoolsConfig`:
	err = encoder.Encode(obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Serialize `ConfigExtensionAuthority`:
	err = encoder.Encode(obj.ConfigExtensionAuthority)
	if err != nil {
		return errors.NewField("ConfigExtensionAuthority", err)
	}
	// Serialize `TokenBadgeAuthority`:
	err = encoder.Encode(obj.TokenBadgeAuthority)
	if err != nil {
		return errors.NewField("TokenBadgeAuthority", err)
	}
	return nil
}

func (obj WhirlpoolsConfigExtension) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WhirlpoolsConfigExtension: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WhirlpoolsConfigExtension) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WhirlpoolsConfig`:
	err = decoder.Decode(&obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Deserialize `ConfigExtensionAuthority`:
	err = decoder.Decode(&obj.ConfigExtensionAuthority)
	if err != nil {
		return errors.NewField("ConfigExtensionAuthority", err)
	}
	// Deserialize `TokenBadgeAuthority`:
	err = decoder.Decode(&obj.TokenBadgeAuthority)
	if err != nil {
		return errors.NewField("TokenBadgeAuthority", err)
	}
	return nil
}

func (obj *WhirlpoolsConfigExtension) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WhirlpoolsConfigExtension: %w", err)
	}
	return nil
}

func UnmarshalWhirlpoolsConfigExtension(buf []byte) (*WhirlpoolsConfigExtension, error) {
	obj := new(WhirlpoolsConfigExtension)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WhirlpoolsConfig struct {
	FeeAuthority                  solanago.PublicKey `json:"feeAuthority"`
	CollectProtocolFeesAuthority  solanago.PublicKey `json:"collectProtocolFeesAuthority"`
	RewardEmissionsSuperAuthority solanago.PublicKey `json:"rewardEmissionsSuperAuthority"`
	DefaultProtocolFeeRate        uint16             `json:"defaultProtocolFeeRate"`
}

func (obj WhirlpoolsConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `FeeAuthority`:
	err = encoder.Encode(obj.FeeAuthority)
	if err != nil {
		return errors.NewField("FeeAuthority", err)
	}
	// Serialize `CollectProtocolFeesAuthority`:
	err = encoder.Encode(obj.CollectProtocolFeesAuthority)
	if err != nil {
		return errors.NewField("CollectProtocolFeesAuthority", err)
	}
	// Serialize `RewardEmissionsSuperAuthority`:
	err = encoder.Encode(obj.RewardEmissionsSuperAuthority)
	if err != nil {
		return errors.NewField("RewardEmissionsSuperAuthority", err)
	}
	// Serialize `DefaultProtocolFeeRate`:
	err = encoder.Encode(obj.DefaultProtocolFeeRate)
	if err != nil {
		return errors.NewField("DefaultProtocolFeeRate", err)
	}
	return nil
}

func (obj WhirlpoolsConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WhirlpoolsConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WhirlpoolsConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `FeeAuthority`:
	err = decoder.Decode(&obj.FeeAuthority)
	if err != nil {
		return errors.NewField("FeeAuthority", err)
	}
	// Deserialize `CollectProtocolFeesAuthority`:
	err = decoder.Decode(&obj.CollectProtocolFeesAuthority)
	if err != nil {
		return errors.NewField("CollectProtocolFeesAuthority", err)
	}
	// Deserialize `RewardEmissionsSuperAuthority`:
	err = decoder.Decode(&obj.RewardEmissionsSuperAuthority)
	if err != nil {
		return errors.NewField("RewardEmissionsSuperAuthority", err)
	}
	// Deserialize `DefaultProtocolFeeRate`:
	err = decoder.Decode(&obj.DefaultProtocolFeeRate)
	if err != nil {
		return errors.NewField("DefaultProtocolFeeRate", err)
	}
	return nil
}

func (obj *WhirlpoolsConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WhirlpoolsConfig: %w", err)
	}
	return nil
}

func UnmarshalWhirlpoolsConfig(buf []byte) (*WhirlpoolsConfig, error) {
	obj := new(WhirlpoolsConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type FeeTier struct {
	WhirlpoolsConfig solanago.PublicKey `json:"whirlpoolsConfig"`
	TickSpacing      uint16             `json:"tickSpacing"`
	DefaultFeeRate   uint16             `json:"defaultFeeRate"`
}

func (obj FeeTier) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WhirlpoolsConfig`:
	err = encoder.Encode(obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `DefaultFeeRate`:
	err = encoder.Encode(obj.DefaultFeeRate)
	if err != nil {
		return errors.NewField("DefaultFeeRate", err)
	}
	return nil
}

func (obj FeeTier) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeTier: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeTier) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WhirlpoolsConfig`:
	err = decoder.Decode(&obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `DefaultFeeRate`:
	err = decoder.Decode(&obj.DefaultFeeRate)
	if err != nil {
		return errors.NewField("DefaultFeeRate", err)
	}
	return nil
}

func (obj *FeeTier) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeTier: %w", err)
	}
	return nil
}

func UnmarshalFeeTier(buf []byte) (*FeeTier, error) {
	obj := new(FeeTier)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PositionBundle struct {
	PositionBundleMint solanago.PublicKey `json:"positionBundleMint"`
	PositionBitmap     [32]uint8          `json:"positionBitmap"`
}

func (obj PositionBundle) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PositionBundleMint`:
	err = encoder.Encode(obj.PositionBundleMint)
	if err != nil {
		return errors.NewField("PositionBundleMint", err)
	}
	// Serialize `PositionBitmap`:
	err = encoder.Encode(obj.PositionBitmap)
	if err != nil {
		return errors.NewField("PositionBitmap", err)
	}
	return nil
}

func (obj PositionBundle) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PositionBundle: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PositionBundle) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PositionBundleMint`:
	err = decoder.Decode(&obj.PositionBundleMint)
	if err != nil {
		return errors.NewField("PositionBundleMint", err)
	}
	// Deserialize `PositionBitmap`:
	err = decoder.Decode(&obj.PositionBitmap)
	if err != nil {
		return errors.NewField("PositionBitmap", err)
	}
	return nil
}

func (obj *PositionBundle) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PositionBundle: %w", err)
	}
	return nil
}

func UnmarshalPositionBundle(buf []byte) (*PositionBundle, error) {
	obj := new(PositionBundle)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Position struct {
	Whirlpool            solanago.PublicKey    `json:"whirlpool"`
	PositionMint         solanago.PublicKey    `json:"positionMint"`
	Liquidity            binary.Uint128        `json:"liquidity"`
	TickLowerIndex       int32                 `json:"tickLowerIndex"`
	TickUpperIndex       int32                 `json:"tickUpperIndex"`
	FeeGrowthCheckpointA binary.Uint128        `json:"feeGrowthCheckpointA"`
	FeeOwedA             uint64                `json:"feeOwedA"`
	FeeGrowthCheckpointB binary.Uint128        `json:"feeGrowthCheckpointB"`
	FeeOwedB             uint64                `json:"feeOwedB"`
	RewardInfos          [3]PositionRewardInfo `json:"rewardInfos"`
}

func (obj Position) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Whirlpool`:
	err = encoder.Encode(obj.Whirlpool)
	if err != nil {
		return errors.NewField("Whirlpool", err)
	}
	// Serialize `PositionMint`:
	err = encoder.Encode(obj.PositionMint)
	if err != nil {
		return errors.NewField("PositionMint", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `TickLowerIndex`:
	err = encoder.Encode(obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Serialize `TickUpperIndex`:
	err = encoder.Encode(obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Serialize `FeeGrowthCheckpointA`:
	err = encoder.Encode(obj.FeeGrowthCheckpointA)
	if err != nil {
		return errors.NewField("FeeGrowthCheckpointA", err)
	}
	// Serialize `FeeOwedA`:
	err = encoder.Encode(obj.FeeOwedA)
	if err != nil {
		return errors.NewField("FeeOwedA", err)
	}
	// Serialize `FeeGrowthCheckpointB`:
	err = encoder.Encode(obj.FeeGrowthCheckpointB)
	if err != nil {
		return errors.NewField("FeeGrowthCheckpointB", err)
	}
	// Serialize `FeeOwedB`:
	err = encoder.Encode(obj.FeeOwedB)
	if err != nil {
		return errors.NewField("FeeOwedB", err)
	}
	// Serialize `RewardInfos`:
	err = encoder.Encode(obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	return nil
}

func (obj Position) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Position: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Position) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Whirlpool`:
	err = decoder.Decode(&obj.Whirlpool)
	if err != nil {
		return errors.NewField("Whirlpool", err)
	}
	// Deserialize `PositionMint`:
	err = decoder.Decode(&obj.PositionMint)
	if err != nil {
		return errors.NewField("PositionMint", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `TickLowerIndex`:
	err = decoder.Decode(&obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Deserialize `TickUpperIndex`:
	err = decoder.Decode(&obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Deserialize `FeeGrowthCheckpointA`:
	err = decoder.Decode(&obj.FeeGrowthCheckpointA)
	if err != nil {
		return errors.NewField("FeeGrowthCheckpointA", err)
	}
	// Deserialize `FeeOwedA`:
	err = decoder.Decode(&obj.FeeOwedA)
	if err != nil {
		return errors.NewField("FeeOwedA", err)
	}
	// Deserialize `FeeGrowthCheckpointB`:
	err = decoder.Decode(&obj.FeeGrowthCheckpointB)
	if err != nil {
		return errors.NewField("FeeGrowthCheckpointB", err)
	}
	// Deserialize `FeeOwedB`:
	err = decoder.Decode(&obj.FeeOwedB)
	if err != nil {
		return errors.NewField("FeeOwedB", err)
	}
	// Deserialize `RewardInfos`:
	err = decoder.Decode(&obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	return nil
}

func (obj *Position) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Position: %w", err)
	}
	return nil
}

func UnmarshalPosition(buf []byte) (*Position, error) {
	obj := new(Position)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TickArray struct {
	StartTickIndex int32              `json:"startTickIndex"`
	Ticks          [88]Tick           `json:"ticks"`
	Whirlpool      solanago.PublicKey `json:"whirlpool"`
}

func (obj TickArray) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `StartTickIndex`:
	err = encoder.Encode(obj.StartTickIndex)
	if err != nil {
		return errors.NewField("StartTickIndex", err)
	}
	// Serialize `Ticks`:
	err = encoder.Encode(obj.Ticks)
	if err != nil {
		return errors.NewField("Ticks", err)
	}
	// Serialize `Whirlpool`:
	err = encoder.Encode(obj.Whirlpool)
	if err != nil {
		return errors.NewField("Whirlpool", err)
	}
	return nil
}

func (obj TickArray) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TickArray: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TickArray) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `StartTickIndex`:
	err = decoder.Decode(&obj.StartTickIndex)
	if err != nil {
		return errors.NewField("StartTickIndex", err)
	}
	// Deserialize `Ticks`:
	err = decoder.Decode(&obj.Ticks)
	if err != nil {
		return errors.NewField("Ticks", err)
	}
	// Deserialize `Whirlpool`:
	err = decoder.Decode(&obj.Whirlpool)
	if err != nil {
		return errors.NewField("Whirlpool", err)
	}
	return nil
}

func (obj *TickArray) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TickArray: %w", err)
	}
	return nil
}

func UnmarshalTickArray(buf []byte) (*TickArray, error) {
	obj := new(TickArray)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TokenBadge struct {
	WhirlpoolsConfig solanago.PublicKey `json:"whirlpoolsConfig"`
	TokenMint        solanago.PublicKey `json:"tokenMint"`
}

func (obj TokenBadge) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WhirlpoolsConfig`:
	err = encoder.Encode(obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Serialize `TokenMint`:
	err = encoder.Encode(obj.TokenMint)
	if err != nil {
		return errors.NewField("TokenMint", err)
	}
	return nil
}

func (obj TokenBadge) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TokenBadge: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TokenBadge) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WhirlpoolsConfig`:
	err = decoder.Decode(&obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Deserialize `TokenMint`:
	err = decoder.Decode(&obj.TokenMint)
	if err != nil {
		return errors.NewField("TokenMint", err)
	}
	return nil
}

func (obj *TokenBadge) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TokenBadge: %w", err)
	}
	return nil
}

func UnmarshalTokenBadge(buf []byte) (*TokenBadge, error) {
	obj := new(TokenBadge)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Whirlpool struct {
	WhirlpoolsConfig           solanago.PublicKey     `json:"whirlpoolsConfig"`
	WhirlpoolBump              [1]uint8               `json:"whirlpoolBump"`
	TickSpacing                uint16                 `json:"tickSpacing"`
	TickSpacingSeed            [2]uint8               `json:"tickSpacingSeed"`
	FeeRate                    uint16                 `json:"feeRate"`
	ProtocolFeeRate            uint16                 `json:"protocolFeeRate"`
	Liquidity                  binary.Uint128         `json:"liquidity"`
	SqrtPrice                  binary.Uint128         `json:"sqrtPrice"`
	TickCurrentIndex           int32                  `json:"tickCurrentIndex"`
	ProtocolFeeOwedA           uint64                 `json:"protocolFeeOwedA"`
	ProtocolFeeOwedB           uint64                 `json:"protocolFeeOwedB"`
	TokenMintA                 solanago.PublicKey     `json:"tokenMintA"`
	TokenVaultA                solanago.PublicKey     `json:"tokenVaultA"`
	FeeGrowthGlobalA           binary.Uint128         `json:"feeGrowthGlobalA"`
	TokenMintB                 solanago.PublicKey     `json:"tokenMintB"`
	TokenVaultB                solanago.PublicKey     `json:"tokenVaultB"`
	FeeGrowthGlobalB           binary.Uint128         `json:"feeGrowthGlobalB"`
	RewardLastUpdatedTimestamp uint64                 `json:"rewardLastUpdatedTimestamp"`
	RewardInfos                [3]WhirlpoolRewardInfo `json:"rewardInfos"`
}

func (obj Whirlpool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WhirlpoolsConfig`:
	err = encoder.Encode(obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Serialize `WhirlpoolBump`:
	err = encoder.Encode(obj.WhirlpoolBump)
	if err != nil {
		return errors.NewField("WhirlpoolBump", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `TickSpacingSeed`:
	err = encoder.Encode(obj.TickSpacingSeed)
	if err != nil {
		return errors.NewField("TickSpacingSeed", err)
	}
	// Serialize `FeeRate`:
	err = encoder.Encode(obj.FeeRate)
	if err != nil {
		return errors.NewField("FeeRate", err)
	}
	// Serialize `ProtocolFeeRate`:
	err = encoder.Encode(obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `SqrtPrice`:
	err = encoder.Encode(obj.SqrtPrice)
	if err != nil {
		return errors.NewField("SqrtPrice", err)
	}
	// Serialize `TickCurrentIndex`:
	err = encoder.Encode(obj.TickCurrentIndex)
	if err != nil {
		return errors.NewField("TickCurrentIndex", err)
	}
	// Serialize `ProtocolFeeOwedA`:
	err = encoder.Encode(obj.ProtocolFeeOwedA)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedA", err)
	}
	// Serialize `ProtocolFeeOwedB`:
	err = encoder.Encode(obj.ProtocolFeeOwedB)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedB", err)
	}
	// Serialize `TokenMintA`:
	err = encoder.Encode(obj.TokenMintA)
	if err != nil {
		return errors.NewField("TokenMintA", err)
	}
	// Serialize `TokenVaultA`:
	err = encoder.Encode(obj.TokenVaultA)
	if err != nil {
		return errors.NewField("TokenVaultA", err)
	}
	// Serialize `FeeGrowthGlobalA`:
	err = encoder.Encode(obj.FeeGrowthGlobalA)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalA", err)
	}
	// Serialize `TokenMintB`:
	err = encoder.Encode(obj.TokenMintB)
	if err != nil {
		return errors.NewField("TokenMintB", err)
	}
	// Serialize `TokenVaultB`:
	err = encoder.Encode(obj.TokenVaultB)
	if err != nil {
		return errors.NewField("TokenVaultB", err)
	}
	// Serialize `FeeGrowthGlobalB`:
	err = encoder.Encode(obj.FeeGrowthGlobalB)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalB", err)
	}
	// Serialize `RewardLastUpdatedTimestamp`:
	err = encoder.Encode(obj.RewardLastUpdatedTimestamp)
	if err != nil {
		return errors.NewField("RewardLastUpdatedTimestamp", err)
	}
	// Serialize `RewardInfos`:
	err = encoder.Encode(obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	return nil
}

func (obj Whirlpool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Whirlpool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Whirlpool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WhirlpoolsConfig`:
	err = decoder.Decode(&obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Deserialize `WhirlpoolBump`:
	err = decoder.Decode(&obj.WhirlpoolBump)
	if err != nil {
		return errors.NewField("WhirlpoolBump", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `TickSpacingSeed`:
	err = decoder.Decode(&obj.TickSpacingSeed)
	if err != nil {
		return errors.NewField("TickSpacingSeed", err)
	}
	// Deserialize `FeeRate`:
	err = decoder.Decode(&obj.FeeRate)
	if err != nil {
		return errors.NewField("FeeRate", err)
	}
	// Deserialize `ProtocolFeeRate`:
	err = decoder.Decode(&obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `SqrtPrice`:
	err = decoder.Decode(&obj.SqrtPrice)
	if err != nil {
		return errors.NewField("SqrtPrice", err)
	}
	// Deserialize `TickCurrentIndex`:
	err = decoder.Decode(&obj.TickCurrentIndex)
	if err != nil {
		return errors.NewField("TickCurrentIndex", err)
	}
	// Deserialize `ProtocolFeeOwedA`:
	err = decoder.Decode(&obj.ProtocolFeeOwedA)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedA", err)
	}
	// Deserialize `ProtocolFeeOwedB`:
	err = decoder.Decode(&obj.ProtocolFeeOwedB)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedB", err)
	}
	// Deserialize `TokenMintA`:
	err = decoder.Decode(&obj.TokenMintA)
	if err != nil {
		return errors.NewField("TokenMintA", err)
	}
	// Deserialize `TokenVaultA`:
	err = decoder.Decode(&obj.TokenVaultA)
	if err != nil {
		return errors.NewField("TokenVaultA", err)
	}
	// Deserialize `FeeGrowthGlobalA`:
	err = decoder.Decode(&obj.FeeGrowthGlobalA)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalA", err)
	}
	// Deserialize `TokenMintB`:
	err = decoder.Decode(&obj.TokenMintB)
	if err != nil {
		return errors.NewField("TokenMintB", err)
	}
	// Deserialize `TokenVaultB`:
	err = decoder.Decode(&obj.TokenVaultB)
	if err != nil {
		return errors.NewField("TokenVaultB", err)
	}
	// Deserialize `FeeGrowthGlobalB`:
	err = decoder.Decode(&obj.FeeGrowthGlobalB)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalB", err)
	}
	// Deserialize `RewardLastUpdatedTimestamp`:
	err = decoder.Decode(&obj.RewardLastUpdatedTimestamp)
	if err != nil {
		return errors.NewField("RewardLastUpdatedTimestamp", err)
	}
	// Deserialize `RewardInfos`:
	err = decoder.Decode(&obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	return nil
}

func (obj *Whirlpool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Whirlpool: %w", err)
	}
	return nil
}

func UnmarshalWhirlpool(buf []byte) (*Whirlpool, error) {
	obj := new(Whirlpool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
