// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package pump_amm

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "buy" instruction.
func NewBuyInstruction(
	// Params:
	baseAmountOutParam uint64,
	maxQuoteAmountInParam uint64,

	// Accounts:
	poolAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	baseMintAccount solanago.PublicKey,
	quoteMintAccount solanago.PublicKey,
	userBaseTokenAccountAccount solanago.PublicKey,
	userQuoteTokenAccountAccount solanago.PublicKey,
	poolBaseTokenAccountAccount solanago.PublicKey,
	poolQuoteTokenAccountAccount solanago.PublicKey,
	protocolFeeRecipientAccount solanago.PublicKey,
	protocolFeeRecipientTokenAccountAccount solanago.PublicKey,
	baseTokenProgramAccount solanago.PublicKey,
	quoteTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
	coinCreatorVaultAtaAccount solanago.PublicKey,
	coinCreatorVaultAuthorityAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Buy[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `baseAmountOutParam`:
		err = enc__.Encode(baseAmountOutParam)
		if err != nil {
			return nil, errors.NewField("baseAmountOutParam", err)
		}
		// Serialize `maxQuoteAmountInParam`:
		err = enc__.Encode(maxQuoteAmountInParam)
		if err != nil {
			return nil, errors.NewField("maxQuoteAmountInParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, false, false))
		// Account 1 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 2 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 3 "base_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseMintAccount, false, false))
		// Account 4 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 5 "user_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseTokenAccountAccount, true, false))
		// Account 6 "user_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteTokenAccountAccount, true, false))
		// Account 7 "pool_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolBaseTokenAccountAccount, true, false))
		// Account 8 "pool_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolQuoteTokenAccountAccount, true, false))
		// Account 9 "protocol_fee_recipient": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeRecipientAccount, false, false))
		// Account 10 "protocol_fee_recipient_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeRecipientTokenAccountAccount, true, false))
		// Account 11 "base_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseTokenProgramAccount, false, false))
		// Account 12 "quote_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 15 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 16 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
		// Account 17 "coin_creator_vault_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorVaultAtaAccount, true, false))
		// Account 18 "coin_creator_vault_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorVaultAuthorityAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "collect_coin_creator_fee" instruction.
func NewCollectCoinCreatorFeeInstruction(
	quoteMintAccount solanago.PublicKey,
	quoteTokenProgramAccount solanago.PublicKey,
	coinCreatorAccount solanago.PublicKey,
	coinCreatorVaultAuthorityAccount solanago.PublicKey,
	coinCreatorVaultAtaAccount solanago.PublicKey,
	coinCreatorTokenAccountAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 1 "quote_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteTokenProgramAccount, false, false))
		// Account 2 "coin_creator": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorAccount, false, true))
		// Account 3 "coin_creator_vault_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorVaultAuthorityAccount, false, false))
		// Account 4 "coin_creator_vault_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorVaultAtaAccount, true, false))
		// Account 5 "coin_creator_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorTokenAccountAccount, true, false))
		// Account 6 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 7 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_config" instruction.
func NewCreateConfigInstruction(
	// Params:
	lpFeeBasisPointsParam uint64,
	protocolFeeBasisPointsParam uint64,
	protocolFeeRecipientsParam [8]solanago.PublicKey,
	coinCreatorFeeBasisPointsParam uint64,

	// Accounts:
	adminAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateConfig[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `lpFeeBasisPointsParam`:
		err = enc__.Encode(lpFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("lpFeeBasisPointsParam", err)
		}
		// Serialize `protocolFeeBasisPointsParam`:
		err = enc__.Encode(protocolFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("protocolFeeBasisPointsParam", err)
		}
		// Serialize `protocolFeeRecipientsParam`:
		err = enc__.Encode(protocolFeeRecipientsParam)
		if err != nil {
			return nil, errors.NewField("protocolFeeRecipientsParam", err)
		}
		// Serialize `coinCreatorFeeBasisPointsParam`:
		err = enc__.Encode(coinCreatorFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("coinCreatorFeeBasisPointsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Writable, Signer, Required, Address: 8LWu7QM2dGR1G8nKDHthckea57bkCzXyBTAKPJUBDHo8
		accounts__.Append(solanago.NewAccountMeta(adminAccount, true, true))
		// Account 1 "global_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "create_pool" instruction.
func NewCreatePoolInstruction(
	// Params:
	indexParam uint16,
	baseAmountInParam uint64,
	quoteAmountInParam uint64,
	coinCreatorParam solanago.PublicKey,

	// Accounts:
	poolAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	creatorAccount solanago.PublicKey,
	baseMintAccount solanago.PublicKey,
	quoteMintAccount solanago.PublicKey,
	lpMintAccount solanago.PublicKey,
	userBaseTokenAccountAccount solanago.PublicKey,
	userQuoteTokenAccountAccount solanago.PublicKey,
	userPoolTokenAccountAccount solanago.PublicKey,
	poolBaseTokenAccountAccount solanago.PublicKey,
	poolQuoteTokenAccountAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	baseTokenProgramAccount solanago.PublicKey,
	quoteTokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreatePool[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `indexParam`:
		err = enc__.Encode(indexParam)
		if err != nil {
			return nil, errors.NewField("indexParam", err)
		}
		// Serialize `baseAmountInParam`:
		err = enc__.Encode(baseAmountInParam)
		if err != nil {
			return nil, errors.NewField("baseAmountInParam", err)
		}
		// Serialize `quoteAmountInParam`:
		err = enc__.Encode(quoteAmountInParam)
		if err != nil {
			return nil, errors.NewField("quoteAmountInParam", err)
		}
		// Serialize `coinCreatorParam`:
		err = enc__.Encode(coinCreatorParam)
		if err != nil {
			return nil, errors.NewField("coinCreatorParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 1 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 2 "creator": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(creatorAccount, true, true))
		// Account 3 "base_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseMintAccount, false, false))
		// Account 4 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 5 "lp_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAccount, true, false))
		// Account 6 "user_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseTokenAccountAccount, true, false))
		// Account 7 "user_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteTokenAccountAccount, true, false))
		// Account 8 "user_pool_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userPoolTokenAccountAccount, true, false))
		// Account 9 "pool_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolBaseTokenAccountAccount, true, false))
		// Account 10 "pool_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolQuoteTokenAccountAccount, true, false))
		// Account 11 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 12 "token_2022_program": Read-only, Non-signer, Required, Address: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 13 "base_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseTokenProgramAccount, false, false))
		// Account 14 "quote_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteTokenProgramAccount, false, false))
		// Account 15 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 16 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 17 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "deposit" instruction.
func NewDepositInstruction(
	// Params:
	lpTokenAmountOutParam uint64,
	maxBaseAmountInParam uint64,
	maxQuoteAmountInParam uint64,

	// Accounts:
	poolAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	baseMintAccount solanago.PublicKey,
	quoteMintAccount solanago.PublicKey,
	lpMintAccount solanago.PublicKey,
	userBaseTokenAccountAccount solanago.PublicKey,
	userQuoteTokenAccountAccount solanago.PublicKey,
	userPoolTokenAccountAccount solanago.PublicKey,
	poolBaseTokenAccountAccount solanago.PublicKey,
	poolQuoteTokenAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Deposit[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `lpTokenAmountOutParam`:
		err = enc__.Encode(lpTokenAmountOutParam)
		if err != nil {
			return nil, errors.NewField("lpTokenAmountOutParam", err)
		}
		// Serialize `maxBaseAmountInParam`:
		err = enc__.Encode(maxBaseAmountInParam)
		if err != nil {
			return nil, errors.NewField("maxBaseAmountInParam", err)
		}
		// Serialize `maxQuoteAmountInParam`:
		err = enc__.Encode(maxQuoteAmountInParam)
		if err != nil {
			return nil, errors.NewField("maxQuoteAmountInParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 1 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 2 "user": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, false, true))
		// Account 3 "base_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseMintAccount, false, false))
		// Account 4 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 5 "lp_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAccount, true, false))
		// Account 6 "user_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseTokenAccountAccount, true, false))
		// Account 7 "user_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteTokenAccountAccount, true, false))
		// Account 8 "user_pool_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userPoolTokenAccountAccount, true, false))
		// Account 9 "pool_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolBaseTokenAccountAccount, true, false))
		// Account 10 "pool_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolQuoteTokenAccountAccount, true, false))
		// Account 11 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 12 "token_2022_program": Read-only, Non-signer, Required, Address: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 13 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 14 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "disable" instruction.
func NewDisableInstruction(
	// Params:
	disableCreatePoolParam bool,
	disableDepositParam bool,
	disableWithdrawParam bool,
	disableBuyParam bool,
	disableSellParam bool,

	// Accounts:
	adminAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Disable[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `disableCreatePoolParam`:
		err = enc__.Encode(disableCreatePoolParam)
		if err != nil {
			return nil, errors.NewField("disableCreatePoolParam", err)
		}
		// Serialize `disableDepositParam`:
		err = enc__.Encode(disableDepositParam)
		if err != nil {
			return nil, errors.NewField("disableDepositParam", err)
		}
		// Serialize `disableWithdrawParam`:
		err = enc__.Encode(disableWithdrawParam)
		if err != nil {
			return nil, errors.NewField("disableWithdrawParam", err)
		}
		// Serialize `disableBuyParam`:
		err = enc__.Encode(disableBuyParam)
		if err != nil {
			return nil, errors.NewField("disableBuyParam", err)
		}
		// Serialize `disableSellParam`:
		err = enc__.Encode(disableSellParam)
		if err != nil {
			return nil, errors.NewField("disableSellParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 1 "global_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, true, false))
		// Account 2 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 3 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "extend_account" instruction.
func NewExtendAccountInstruction(
	accountAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(accountAccount, true, false))
		// Account 1 "user": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, false, true))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "sell" instruction.
func NewSellInstruction(
	// Params:
	baseAmountInParam uint64,
	minQuoteAmountOutParam uint64,

	// Accounts:
	poolAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	baseMintAccount solanago.PublicKey,
	quoteMintAccount solanago.PublicKey,
	userBaseTokenAccountAccount solanago.PublicKey,
	userQuoteTokenAccountAccount solanago.PublicKey,
	poolBaseTokenAccountAccount solanago.PublicKey,
	poolQuoteTokenAccountAccount solanago.PublicKey,
	protocolFeeRecipientAccount solanago.PublicKey,
	protocolFeeRecipientTokenAccountAccount solanago.PublicKey,
	baseTokenProgramAccount solanago.PublicKey,
	quoteTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
	coinCreatorVaultAtaAccount solanago.PublicKey,
	coinCreatorVaultAuthorityAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Sell[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `baseAmountInParam`:
		err = enc__.Encode(baseAmountInParam)
		if err != nil {
			return nil, errors.NewField("baseAmountInParam", err)
		}
		// Serialize `minQuoteAmountOutParam`:
		err = enc__.Encode(minQuoteAmountOutParam)
		if err != nil {
			return nil, errors.NewField("minQuoteAmountOutParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, false, false))
		// Account 1 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 2 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 3 "base_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseMintAccount, false, false))
		// Account 4 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 5 "user_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseTokenAccountAccount, true, false))
		// Account 6 "user_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteTokenAccountAccount, true, false))
		// Account 7 "pool_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolBaseTokenAccountAccount, true, false))
		// Account 8 "pool_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolQuoteTokenAccountAccount, true, false))
		// Account 9 "protocol_fee_recipient": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeRecipientAccount, false, false))
		// Account 10 "protocol_fee_recipient_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeRecipientTokenAccountAccount, true, false))
		// Account 11 "base_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseTokenProgramAccount, false, false))
		// Account 12 "quote_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteTokenProgramAccount, false, false))
		// Account 13 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 14 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 15 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 16 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
		// Account 17 "coin_creator_vault_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorVaultAtaAccount, true, false))
		// Account 18 "coin_creator_vault_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(coinCreatorVaultAuthorityAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_coin_creator" instruction.
// Sets Pool::coin_creator from Metaplex metadata creator or BondingCurve::creator
func NewSetCoinCreatorInstruction(
	poolAccount solanago.PublicKey,
	metadataAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 1 "metadata": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(metadataAccount, false, false))
		// Account 2 "bonding_curve": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "update_admin" instruction.
func NewUpdateAdminInstruction(
	adminAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	newAdminAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 1 "global_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, true, false))
		// Account 2 "new_admin": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(newAdminAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "update_fee_config" instruction.
func NewUpdateFeeConfigInstruction(
	// Params:
	lpFeeBasisPointsParam uint64,
	protocolFeeBasisPointsParam uint64,
	protocolFeeRecipientsParam [8]solanago.PublicKey,
	coinCreatorFeeBasisPointsParam uint64,

	// Accounts:
	adminAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateFeeConfig[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `lpFeeBasisPointsParam`:
		err = enc__.Encode(lpFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("lpFeeBasisPointsParam", err)
		}
		// Serialize `protocolFeeBasisPointsParam`:
		err = enc__.Encode(protocolFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("protocolFeeBasisPointsParam", err)
		}
		// Serialize `protocolFeeRecipientsParam`:
		err = enc__.Encode(protocolFeeRecipientsParam)
		if err != nil {
			return nil, errors.NewField("protocolFeeRecipientsParam", err)
		}
		// Serialize `coinCreatorFeeBasisPointsParam`:
		err = enc__.Encode(coinCreatorFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("coinCreatorFeeBasisPointsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 1 "global_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, true, false))
		// Account 2 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 3 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "withdraw" instruction.
func NewWithdrawInstruction(
	// Params:
	lpTokenAmountInParam uint64,
	minBaseAmountOutParam uint64,
	minQuoteAmountOutParam uint64,

	// Accounts:
	poolAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	baseMintAccount solanago.PublicKey,
	quoteMintAccount solanago.PublicKey,
	lpMintAccount solanago.PublicKey,
	userBaseTokenAccountAccount solanago.PublicKey,
	userQuoteTokenAccountAccount solanago.PublicKey,
	userPoolTokenAccountAccount solanago.PublicKey,
	poolBaseTokenAccountAccount solanago.PublicKey,
	poolQuoteTokenAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Withdraw[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `lpTokenAmountInParam`:
		err = enc__.Encode(lpTokenAmountInParam)
		if err != nil {
			return nil, errors.NewField("lpTokenAmountInParam", err)
		}
		// Serialize `minBaseAmountOutParam`:
		err = enc__.Encode(minBaseAmountOutParam)
		if err != nil {
			return nil, errors.NewField("minBaseAmountOutParam", err)
		}
		// Serialize `minQuoteAmountOutParam`:
		err = enc__.Encode(minQuoteAmountOutParam)
		if err != nil {
			return nil, errors.NewField("minQuoteAmountOutParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 1 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 2 "user": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, false, true))
		// Account 3 "base_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(baseMintAccount, false, false))
		// Account 4 "quote_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(quoteMintAccount, false, false))
		// Account 5 "lp_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAccount, true, false))
		// Account 6 "user_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userBaseTokenAccountAccount, true, false))
		// Account 7 "user_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userQuoteTokenAccountAccount, true, false))
		// Account 8 "user_pool_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userPoolTokenAccountAccount, true, false))
		// Account 9 "pool_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolBaseTokenAccountAccount, true, false))
		// Account 10 "pool_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolQuoteTokenAccountAccount, true, false))
		// Account 11 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 12 "token_2022_program": Read-only, Non-signer, Required, Address: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 13 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 14 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
