// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package pump_amm

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type BondingCurve struct {
	VirtualTokenReserves uint64             `json:"virtualTokenReserves"`
	VirtualSolReserves   uint64             `json:"virtualSolReserves"`
	RealTokenReserves    uint64             `json:"realTokenReserves"`
	RealSolReserves      uint64             `json:"realSolReserves"`
	TokenTotalSupply     uint64             `json:"tokenTotalSupply"`
	Complete             bool               `json:"complete"`
	Creator              solanago.PublicKey `json:"creator"`
}

func (obj BondingCurve) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `RealSolReserves`:
	err = encoder.Encode(obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `Complete`:
	err = encoder.Encode(obj.Complete)
	if err != nil {
		return errors.NewField("Complete", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj BondingCurve) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BondingCurve: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BondingCurve) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `RealSolReserves`:
	err = decoder.Decode(&obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `Complete`:
	err = decoder.Decode(&obj.Complete)
	if err != nil {
		return errors.NewField("Complete", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj *BondingCurve) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BondingCurve: %w", err)
	}
	return nil
}

func UnmarshalBondingCurve(buf []byte) (*BondingCurve, error) {
	obj := new(BondingCurve)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type BuyEvent struct {
	Timestamp                        int64              `json:"timestamp"`
	BaseAmountOut                    uint64             `json:"baseAmountOut"`
	MaxQuoteAmountIn                 uint64             `json:"maxQuoteAmountIn"`
	UserBaseTokenReserves            uint64             `json:"userBaseTokenReserves"`
	UserQuoteTokenReserves           uint64             `json:"userQuoteTokenReserves"`
	PoolBaseTokenReserves            uint64             `json:"poolBaseTokenReserves"`
	PoolQuoteTokenReserves           uint64             `json:"poolQuoteTokenReserves"`
	QuoteAmountIn                    uint64             `json:"quoteAmountIn"`
	LpFeeBasisPoints                 uint64             `json:"lpFeeBasisPoints"`
	LpFee                            uint64             `json:"lpFee"`
	ProtocolFeeBasisPoints           uint64             `json:"protocolFeeBasisPoints"`
	ProtocolFee                      uint64             `json:"protocolFee"`
	QuoteAmountInWithLpFee           uint64             `json:"quoteAmountInWithLpFee"`
	UserQuoteAmountIn                uint64             `json:"userQuoteAmountIn"`
	Pool                             solanago.PublicKey `json:"pool"`
	User                             solanago.PublicKey `json:"user"`
	UserBaseTokenAccount             solanago.PublicKey `json:"userBaseTokenAccount"`
	UserQuoteTokenAccount            solanago.PublicKey `json:"userQuoteTokenAccount"`
	ProtocolFeeRecipient             solanago.PublicKey `json:"protocolFeeRecipient"`
	ProtocolFeeRecipientTokenAccount solanago.PublicKey `json:"protocolFeeRecipientTokenAccount"`
	CoinCreator                      solanago.PublicKey `json:"coinCreator"`
	CoinCreatorFeeBasisPoints        uint64             `json:"coinCreatorFeeBasisPoints"`
	CoinCreatorFee                   uint64             `json:"coinCreatorFee"`
}

func (obj BuyEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `BaseAmountOut`:
	err = encoder.Encode(obj.BaseAmountOut)
	if err != nil {
		return errors.NewField("BaseAmountOut", err)
	}
	// Serialize `MaxQuoteAmountIn`:
	err = encoder.Encode(obj.MaxQuoteAmountIn)
	if err != nil {
		return errors.NewField("MaxQuoteAmountIn", err)
	}
	// Serialize `UserBaseTokenReserves`:
	err = encoder.Encode(obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Serialize `UserQuoteTokenReserves`:
	err = encoder.Encode(obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Serialize `PoolBaseTokenReserves`:
	err = encoder.Encode(obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Serialize `PoolQuoteTokenReserves`:
	err = encoder.Encode(obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Serialize `QuoteAmountIn`:
	err = encoder.Encode(obj.QuoteAmountIn)
	if err != nil {
		return errors.NewField("QuoteAmountIn", err)
	}
	// Serialize `LpFeeBasisPoints`:
	err = encoder.Encode(obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Serialize `LpFee`:
	err = encoder.Encode(obj.LpFee)
	if err != nil {
		return errors.NewField("LpFee", err)
	}
	// Serialize `ProtocolFeeBasisPoints`:
	err = encoder.Encode(obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Serialize `ProtocolFee`:
	err = encoder.Encode(obj.ProtocolFee)
	if err != nil {
		return errors.NewField("ProtocolFee", err)
	}
	// Serialize `QuoteAmountInWithLpFee`:
	err = encoder.Encode(obj.QuoteAmountInWithLpFee)
	if err != nil {
		return errors.NewField("QuoteAmountInWithLpFee", err)
	}
	// Serialize `UserQuoteAmountIn`:
	err = encoder.Encode(obj.UserQuoteAmountIn)
	if err != nil {
		return errors.NewField("UserQuoteAmountIn", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `UserBaseTokenAccount`:
	err = encoder.Encode(obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Serialize `UserQuoteTokenAccount`:
	err = encoder.Encode(obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Serialize `ProtocolFeeRecipient`:
	err = encoder.Encode(obj.ProtocolFeeRecipient)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipient", err)
	}
	// Serialize `ProtocolFeeRecipientTokenAccount`:
	err = encoder.Encode(obj.ProtocolFeeRecipientTokenAccount)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipientTokenAccount", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	// Serialize `CoinCreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	// Serialize `CoinCreatorFee`:
	err = encoder.Encode(obj.CoinCreatorFee)
	if err != nil {
		return errors.NewField("CoinCreatorFee", err)
	}
	return nil
}

func (obj BuyEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BuyEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BuyEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `BaseAmountOut`:
	err = decoder.Decode(&obj.BaseAmountOut)
	if err != nil {
		return errors.NewField("BaseAmountOut", err)
	}
	// Deserialize `MaxQuoteAmountIn`:
	err = decoder.Decode(&obj.MaxQuoteAmountIn)
	if err != nil {
		return errors.NewField("MaxQuoteAmountIn", err)
	}
	// Deserialize `UserBaseTokenReserves`:
	err = decoder.Decode(&obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Deserialize `UserQuoteTokenReserves`:
	err = decoder.Decode(&obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Deserialize `PoolBaseTokenReserves`:
	err = decoder.Decode(&obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Deserialize `PoolQuoteTokenReserves`:
	err = decoder.Decode(&obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Deserialize `QuoteAmountIn`:
	err = decoder.Decode(&obj.QuoteAmountIn)
	if err != nil {
		return errors.NewField("QuoteAmountIn", err)
	}
	// Deserialize `LpFeeBasisPoints`:
	err = decoder.Decode(&obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Deserialize `LpFee`:
	err = decoder.Decode(&obj.LpFee)
	if err != nil {
		return errors.NewField("LpFee", err)
	}
	// Deserialize `ProtocolFeeBasisPoints`:
	err = decoder.Decode(&obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFee`:
	err = decoder.Decode(&obj.ProtocolFee)
	if err != nil {
		return errors.NewField("ProtocolFee", err)
	}
	// Deserialize `QuoteAmountInWithLpFee`:
	err = decoder.Decode(&obj.QuoteAmountInWithLpFee)
	if err != nil {
		return errors.NewField("QuoteAmountInWithLpFee", err)
	}
	// Deserialize `UserQuoteAmountIn`:
	err = decoder.Decode(&obj.UserQuoteAmountIn)
	if err != nil {
		return errors.NewField("UserQuoteAmountIn", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `UserBaseTokenAccount`:
	err = decoder.Decode(&obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Deserialize `UserQuoteTokenAccount`:
	err = decoder.Decode(&obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Deserialize `ProtocolFeeRecipient`:
	err = decoder.Decode(&obj.ProtocolFeeRecipient)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipient", err)
	}
	// Deserialize `ProtocolFeeRecipientTokenAccount`:
	err = decoder.Decode(&obj.ProtocolFeeRecipientTokenAccount)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipientTokenAccount", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	// Deserialize `CoinCreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	// Deserialize `CoinCreatorFee`:
	err = decoder.Decode(&obj.CoinCreatorFee)
	if err != nil {
		return errors.NewField("CoinCreatorFee", err)
	}
	return nil
}

func (obj *BuyEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BuyEvent: %w", err)
	}
	return nil
}

func UnmarshalBuyEvent(buf []byte) (*BuyEvent, error) {
	obj := new(BuyEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CollectCoinCreatorFeeEvent struct {
	Timestamp               int64              `json:"timestamp"`
	CoinCreator             solanago.PublicKey `json:"coinCreator"`
	CoinCreatorFee          uint64             `json:"coinCreatorFee"`
	CoinCreatorVaultAta     solanago.PublicKey `json:"coinCreatorVaultAta"`
	CoinCreatorTokenAccount solanago.PublicKey `json:"coinCreatorTokenAccount"`
}

func (obj CollectCoinCreatorFeeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	// Serialize `CoinCreatorFee`:
	err = encoder.Encode(obj.CoinCreatorFee)
	if err != nil {
		return errors.NewField("CoinCreatorFee", err)
	}
	// Serialize `CoinCreatorVaultAta`:
	err = encoder.Encode(obj.CoinCreatorVaultAta)
	if err != nil {
		return errors.NewField("CoinCreatorVaultAta", err)
	}
	// Serialize `CoinCreatorTokenAccount`:
	err = encoder.Encode(obj.CoinCreatorTokenAccount)
	if err != nil {
		return errors.NewField("CoinCreatorTokenAccount", err)
	}
	return nil
}

func (obj CollectCoinCreatorFeeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CollectCoinCreatorFeeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CollectCoinCreatorFeeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	// Deserialize `CoinCreatorFee`:
	err = decoder.Decode(&obj.CoinCreatorFee)
	if err != nil {
		return errors.NewField("CoinCreatorFee", err)
	}
	// Deserialize `CoinCreatorVaultAta`:
	err = decoder.Decode(&obj.CoinCreatorVaultAta)
	if err != nil {
		return errors.NewField("CoinCreatorVaultAta", err)
	}
	// Deserialize `CoinCreatorTokenAccount`:
	err = decoder.Decode(&obj.CoinCreatorTokenAccount)
	if err != nil {
		return errors.NewField("CoinCreatorTokenAccount", err)
	}
	return nil
}

func (obj *CollectCoinCreatorFeeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CollectCoinCreatorFeeEvent: %w", err)
	}
	return nil
}

func UnmarshalCollectCoinCreatorFeeEvent(buf []byte) (*CollectCoinCreatorFeeEvent, error) {
	obj := new(CollectCoinCreatorFeeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CreateConfigEvent struct {
	Timestamp                 int64                 `json:"timestamp"`
	Admin                     solanago.PublicKey    `json:"admin"`
	LpFeeBasisPoints          uint64                `json:"lpFeeBasisPoints"`
	ProtocolFeeBasisPoints    uint64                `json:"protocolFeeBasisPoints"`
	ProtocolFeeRecipients     [8]solanago.PublicKey `json:"protocolFeeRecipients"`
	CoinCreatorFeeBasisPoints uint64                `json:"coinCreatorFeeBasisPoints"`
}

func (obj CreateConfigEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `LpFeeBasisPoints`:
	err = encoder.Encode(obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Serialize `ProtocolFeeBasisPoints`:
	err = encoder.Encode(obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Serialize `ProtocolFeeRecipients`:
	err = encoder.Encode(obj.ProtocolFeeRecipients)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipients", err)
	}
	// Serialize `CoinCreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	return nil
}

func (obj CreateConfigEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CreateConfigEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CreateConfigEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `LpFeeBasisPoints`:
	err = decoder.Decode(&obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFeeBasisPoints`:
	err = decoder.Decode(&obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFeeRecipients`:
	err = decoder.Decode(&obj.ProtocolFeeRecipients)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipients", err)
	}
	// Deserialize `CoinCreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	return nil
}

func (obj *CreateConfigEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CreateConfigEvent: %w", err)
	}
	return nil
}

func UnmarshalCreateConfigEvent(buf []byte) (*CreateConfigEvent, error) {
	obj := new(CreateConfigEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CreatePoolEvent struct {
	Timestamp             int64              `json:"timestamp"`
	Index                 uint16             `json:"index"`
	Creator               solanago.PublicKey `json:"creator"`
	BaseMint              solanago.PublicKey `json:"baseMint"`
	QuoteMint             solanago.PublicKey `json:"quoteMint"`
	BaseMintDecimals      uint8              `json:"baseMintDecimals"`
	QuoteMintDecimals     uint8              `json:"quoteMintDecimals"`
	BaseAmountIn          uint64             `json:"baseAmountIn"`
	QuoteAmountIn         uint64             `json:"quoteAmountIn"`
	PoolBaseAmount        uint64             `json:"poolBaseAmount"`
	PoolQuoteAmount       uint64             `json:"poolQuoteAmount"`
	MinimumLiquidity      uint64             `json:"minimumLiquidity"`
	InitialLiquidity      uint64             `json:"initialLiquidity"`
	LpTokenAmountOut      uint64             `json:"lpTokenAmountOut"`
	PoolBump              uint8              `json:"poolBump"`
	Pool                  solanago.PublicKey `json:"pool"`
	LpMint                solanago.PublicKey `json:"lpMint"`
	UserBaseTokenAccount  solanago.PublicKey `json:"userBaseTokenAccount"`
	UserQuoteTokenAccount solanago.PublicKey `json:"userQuoteTokenAccount"`
	CoinCreator           solanago.PublicKey `json:"coinCreator"`
}

func (obj CreatePoolEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Index`:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `BaseMint`:
	err = encoder.Encode(obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Serialize `QuoteMint`:
	err = encoder.Encode(obj.QuoteMint)
	if err != nil {
		return errors.NewField("QuoteMint", err)
	}
	// Serialize `BaseMintDecimals`:
	err = encoder.Encode(obj.BaseMintDecimals)
	if err != nil {
		return errors.NewField("BaseMintDecimals", err)
	}
	// Serialize `QuoteMintDecimals`:
	err = encoder.Encode(obj.QuoteMintDecimals)
	if err != nil {
		return errors.NewField("QuoteMintDecimals", err)
	}
	// Serialize `BaseAmountIn`:
	err = encoder.Encode(obj.BaseAmountIn)
	if err != nil {
		return errors.NewField("BaseAmountIn", err)
	}
	// Serialize `QuoteAmountIn`:
	err = encoder.Encode(obj.QuoteAmountIn)
	if err != nil {
		return errors.NewField("QuoteAmountIn", err)
	}
	// Serialize `PoolBaseAmount`:
	err = encoder.Encode(obj.PoolBaseAmount)
	if err != nil {
		return errors.NewField("PoolBaseAmount", err)
	}
	// Serialize `PoolQuoteAmount`:
	err = encoder.Encode(obj.PoolQuoteAmount)
	if err != nil {
		return errors.NewField("PoolQuoteAmount", err)
	}
	// Serialize `MinimumLiquidity`:
	err = encoder.Encode(obj.MinimumLiquidity)
	if err != nil {
		return errors.NewField("MinimumLiquidity", err)
	}
	// Serialize `InitialLiquidity`:
	err = encoder.Encode(obj.InitialLiquidity)
	if err != nil {
		return errors.NewField("InitialLiquidity", err)
	}
	// Serialize `LpTokenAmountOut`:
	err = encoder.Encode(obj.LpTokenAmountOut)
	if err != nil {
		return errors.NewField("LpTokenAmountOut", err)
	}
	// Serialize `PoolBump`:
	err = encoder.Encode(obj.PoolBump)
	if err != nil {
		return errors.NewField("PoolBump", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `LpMint`:
	err = encoder.Encode(obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Serialize `UserBaseTokenAccount`:
	err = encoder.Encode(obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Serialize `UserQuoteTokenAccount`:
	err = encoder.Encode(obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj CreatePoolEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CreatePoolEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CreatePoolEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `BaseMint`:
	err = decoder.Decode(&obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Deserialize `QuoteMint`:
	err = decoder.Decode(&obj.QuoteMint)
	if err != nil {
		return errors.NewField("QuoteMint", err)
	}
	// Deserialize `BaseMintDecimals`:
	err = decoder.Decode(&obj.BaseMintDecimals)
	if err != nil {
		return errors.NewField("BaseMintDecimals", err)
	}
	// Deserialize `QuoteMintDecimals`:
	err = decoder.Decode(&obj.QuoteMintDecimals)
	if err != nil {
		return errors.NewField("QuoteMintDecimals", err)
	}
	// Deserialize `BaseAmountIn`:
	err = decoder.Decode(&obj.BaseAmountIn)
	if err != nil {
		return errors.NewField("BaseAmountIn", err)
	}
	// Deserialize `QuoteAmountIn`:
	err = decoder.Decode(&obj.QuoteAmountIn)
	if err != nil {
		return errors.NewField("QuoteAmountIn", err)
	}
	// Deserialize `PoolBaseAmount`:
	err = decoder.Decode(&obj.PoolBaseAmount)
	if err != nil {
		return errors.NewField("PoolBaseAmount", err)
	}
	// Deserialize `PoolQuoteAmount`:
	err = decoder.Decode(&obj.PoolQuoteAmount)
	if err != nil {
		return errors.NewField("PoolQuoteAmount", err)
	}
	// Deserialize `MinimumLiquidity`:
	err = decoder.Decode(&obj.MinimumLiquidity)
	if err != nil {
		return errors.NewField("MinimumLiquidity", err)
	}
	// Deserialize `InitialLiquidity`:
	err = decoder.Decode(&obj.InitialLiquidity)
	if err != nil {
		return errors.NewField("InitialLiquidity", err)
	}
	// Deserialize `LpTokenAmountOut`:
	err = decoder.Decode(&obj.LpTokenAmountOut)
	if err != nil {
		return errors.NewField("LpTokenAmountOut", err)
	}
	// Deserialize `PoolBump`:
	err = decoder.Decode(&obj.PoolBump)
	if err != nil {
		return errors.NewField("PoolBump", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `LpMint`:
	err = decoder.Decode(&obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Deserialize `UserBaseTokenAccount`:
	err = decoder.Decode(&obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Deserialize `UserQuoteTokenAccount`:
	err = decoder.Decode(&obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj *CreatePoolEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CreatePoolEvent: %w", err)
	}
	return nil
}

func UnmarshalCreatePoolEvent(buf []byte) (*CreatePoolEvent, error) {
	obj := new(CreatePoolEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type DepositEvent struct {
	Timestamp              int64              `json:"timestamp"`
	LpTokenAmountOut       uint64             `json:"lpTokenAmountOut"`
	MaxBaseAmountIn        uint64             `json:"maxBaseAmountIn"`
	MaxQuoteAmountIn       uint64             `json:"maxQuoteAmountIn"`
	UserBaseTokenReserves  uint64             `json:"userBaseTokenReserves"`
	UserQuoteTokenReserves uint64             `json:"userQuoteTokenReserves"`
	PoolBaseTokenReserves  uint64             `json:"poolBaseTokenReserves"`
	PoolQuoteTokenReserves uint64             `json:"poolQuoteTokenReserves"`
	BaseAmountIn           uint64             `json:"baseAmountIn"`
	QuoteAmountIn          uint64             `json:"quoteAmountIn"`
	LpMintSupply           uint64             `json:"lpMintSupply"`
	Pool                   solanago.PublicKey `json:"pool"`
	User                   solanago.PublicKey `json:"user"`
	UserBaseTokenAccount   solanago.PublicKey `json:"userBaseTokenAccount"`
	UserQuoteTokenAccount  solanago.PublicKey `json:"userQuoteTokenAccount"`
	UserPoolTokenAccount   solanago.PublicKey `json:"userPoolTokenAccount"`
}

func (obj DepositEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `LpTokenAmountOut`:
	err = encoder.Encode(obj.LpTokenAmountOut)
	if err != nil {
		return errors.NewField("LpTokenAmountOut", err)
	}
	// Serialize `MaxBaseAmountIn`:
	err = encoder.Encode(obj.MaxBaseAmountIn)
	if err != nil {
		return errors.NewField("MaxBaseAmountIn", err)
	}
	// Serialize `MaxQuoteAmountIn`:
	err = encoder.Encode(obj.MaxQuoteAmountIn)
	if err != nil {
		return errors.NewField("MaxQuoteAmountIn", err)
	}
	// Serialize `UserBaseTokenReserves`:
	err = encoder.Encode(obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Serialize `UserQuoteTokenReserves`:
	err = encoder.Encode(obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Serialize `PoolBaseTokenReserves`:
	err = encoder.Encode(obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Serialize `PoolQuoteTokenReserves`:
	err = encoder.Encode(obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Serialize `BaseAmountIn`:
	err = encoder.Encode(obj.BaseAmountIn)
	if err != nil {
		return errors.NewField("BaseAmountIn", err)
	}
	// Serialize `QuoteAmountIn`:
	err = encoder.Encode(obj.QuoteAmountIn)
	if err != nil {
		return errors.NewField("QuoteAmountIn", err)
	}
	// Serialize `LpMintSupply`:
	err = encoder.Encode(obj.LpMintSupply)
	if err != nil {
		return errors.NewField("LpMintSupply", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `UserBaseTokenAccount`:
	err = encoder.Encode(obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Serialize `UserQuoteTokenAccount`:
	err = encoder.Encode(obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Serialize `UserPoolTokenAccount`:
	err = encoder.Encode(obj.UserPoolTokenAccount)
	if err != nil {
		return errors.NewField("UserPoolTokenAccount", err)
	}
	return nil
}

func (obj DepositEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding DepositEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *DepositEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `LpTokenAmountOut`:
	err = decoder.Decode(&obj.LpTokenAmountOut)
	if err != nil {
		return errors.NewField("LpTokenAmountOut", err)
	}
	// Deserialize `MaxBaseAmountIn`:
	err = decoder.Decode(&obj.MaxBaseAmountIn)
	if err != nil {
		return errors.NewField("MaxBaseAmountIn", err)
	}
	// Deserialize `MaxQuoteAmountIn`:
	err = decoder.Decode(&obj.MaxQuoteAmountIn)
	if err != nil {
		return errors.NewField("MaxQuoteAmountIn", err)
	}
	// Deserialize `UserBaseTokenReserves`:
	err = decoder.Decode(&obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Deserialize `UserQuoteTokenReserves`:
	err = decoder.Decode(&obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Deserialize `PoolBaseTokenReserves`:
	err = decoder.Decode(&obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Deserialize `PoolQuoteTokenReserves`:
	err = decoder.Decode(&obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Deserialize `BaseAmountIn`:
	err = decoder.Decode(&obj.BaseAmountIn)
	if err != nil {
		return errors.NewField("BaseAmountIn", err)
	}
	// Deserialize `QuoteAmountIn`:
	err = decoder.Decode(&obj.QuoteAmountIn)
	if err != nil {
		return errors.NewField("QuoteAmountIn", err)
	}
	// Deserialize `LpMintSupply`:
	err = decoder.Decode(&obj.LpMintSupply)
	if err != nil {
		return errors.NewField("LpMintSupply", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `UserBaseTokenAccount`:
	err = decoder.Decode(&obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Deserialize `UserQuoteTokenAccount`:
	err = decoder.Decode(&obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Deserialize `UserPoolTokenAccount`:
	err = decoder.Decode(&obj.UserPoolTokenAccount)
	if err != nil {
		return errors.NewField("UserPoolTokenAccount", err)
	}
	return nil
}

func (obj *DepositEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling DepositEvent: %w", err)
	}
	return nil
}

func UnmarshalDepositEvent(buf []byte) (*DepositEvent, error) {
	obj := new(DepositEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type DisableEvent struct {
	Timestamp         int64              `json:"timestamp"`
	Admin             solanago.PublicKey `json:"admin"`
	DisableCreatePool bool               `json:"disableCreatePool"`
	DisableDeposit    bool               `json:"disableDeposit"`
	DisableWithdraw   bool               `json:"disableWithdraw"`
	DisableBuy        bool               `json:"disableBuy"`
	DisableSell       bool               `json:"disableSell"`
}

func (obj DisableEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `DisableCreatePool`:
	err = encoder.Encode(obj.DisableCreatePool)
	if err != nil {
		return errors.NewField("DisableCreatePool", err)
	}
	// Serialize `DisableDeposit`:
	err = encoder.Encode(obj.DisableDeposit)
	if err != nil {
		return errors.NewField("DisableDeposit", err)
	}
	// Serialize `DisableWithdraw`:
	err = encoder.Encode(obj.DisableWithdraw)
	if err != nil {
		return errors.NewField("DisableWithdraw", err)
	}
	// Serialize `DisableBuy`:
	err = encoder.Encode(obj.DisableBuy)
	if err != nil {
		return errors.NewField("DisableBuy", err)
	}
	// Serialize `DisableSell`:
	err = encoder.Encode(obj.DisableSell)
	if err != nil {
		return errors.NewField("DisableSell", err)
	}
	return nil
}

func (obj DisableEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding DisableEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *DisableEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `DisableCreatePool`:
	err = decoder.Decode(&obj.DisableCreatePool)
	if err != nil {
		return errors.NewField("DisableCreatePool", err)
	}
	// Deserialize `DisableDeposit`:
	err = decoder.Decode(&obj.DisableDeposit)
	if err != nil {
		return errors.NewField("DisableDeposit", err)
	}
	// Deserialize `DisableWithdraw`:
	err = decoder.Decode(&obj.DisableWithdraw)
	if err != nil {
		return errors.NewField("DisableWithdraw", err)
	}
	// Deserialize `DisableBuy`:
	err = decoder.Decode(&obj.DisableBuy)
	if err != nil {
		return errors.NewField("DisableBuy", err)
	}
	// Deserialize `DisableSell`:
	err = decoder.Decode(&obj.DisableSell)
	if err != nil {
		return errors.NewField("DisableSell", err)
	}
	return nil
}

func (obj *DisableEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling DisableEvent: %w", err)
	}
	return nil
}

func UnmarshalDisableEvent(buf []byte) (*DisableEvent, error) {
	obj := new(DisableEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ExtendAccountEvent struct {
	Timestamp   int64              `json:"timestamp"`
	Account     solanago.PublicKey `json:"account"`
	User        solanago.PublicKey `json:"user"`
	CurrentSize uint64             `json:"currentSize"`
	NewSize     uint64             `json:"newSize"`
}

func (obj ExtendAccountEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Account`:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `CurrentSize`:
	err = encoder.Encode(obj.CurrentSize)
	if err != nil {
		return errors.NewField("CurrentSize", err)
	}
	// Serialize `NewSize`:
	err = encoder.Encode(obj.NewSize)
	if err != nil {
		return errors.NewField("NewSize", err)
	}
	return nil
}

func (obj ExtendAccountEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ExtendAccountEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ExtendAccountEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `CurrentSize`:
	err = decoder.Decode(&obj.CurrentSize)
	if err != nil {
		return errors.NewField("CurrentSize", err)
	}
	// Deserialize `NewSize`:
	err = decoder.Decode(&obj.NewSize)
	if err != nil {
		return errors.NewField("NewSize", err)
	}
	return nil
}

func (obj *ExtendAccountEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ExtendAccountEvent: %w", err)
	}
	return nil
}

func UnmarshalExtendAccountEvent(buf []byte) (*ExtendAccountEvent, error) {
	obj := new(ExtendAccountEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type GlobalConfig struct {
	// The admin pubkey
	Admin solanago.PublicKey `json:"admin"`

	// The lp fee in basis points (0.01%)
	LpFeeBasisPoints uint64 `json:"lpFeeBasisPoints"`

	// The protocol fee in basis points (0.01%)
	ProtocolFeeBasisPoints uint64 `json:"protocolFeeBasisPoints"`

	// Flags to disable certain functionality
	// bit 0 - Disable create pool
	// bit 1 - Disable deposit
	// bit 2 - Disable withdraw
	// bit 3 - Disable buy
	// bit 4 - Disable sell
	DisableFlags uint8 `json:"disableFlags"`

	// Addresses of the protocol fee recipients
	ProtocolFeeRecipients [8]solanago.PublicKey `json:"protocolFeeRecipients"`

	// The coin creator fee in basis points (0.01%)
	CoinCreatorFeeBasisPoints uint64 `json:"coinCreatorFeeBasisPoints"`
}

func (obj GlobalConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `LpFeeBasisPoints`:
	err = encoder.Encode(obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Serialize `ProtocolFeeBasisPoints`:
	err = encoder.Encode(obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Serialize `DisableFlags`:
	err = encoder.Encode(obj.DisableFlags)
	if err != nil {
		return errors.NewField("DisableFlags", err)
	}
	// Serialize `ProtocolFeeRecipients`:
	err = encoder.Encode(obj.ProtocolFeeRecipients)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipients", err)
	}
	// Serialize `CoinCreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	return nil
}

func (obj GlobalConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding GlobalConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *GlobalConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `LpFeeBasisPoints`:
	err = decoder.Decode(&obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFeeBasisPoints`:
	err = decoder.Decode(&obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Deserialize `DisableFlags`:
	err = decoder.Decode(&obj.DisableFlags)
	if err != nil {
		return errors.NewField("DisableFlags", err)
	}
	// Deserialize `ProtocolFeeRecipients`:
	err = decoder.Decode(&obj.ProtocolFeeRecipients)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipients", err)
	}
	// Deserialize `CoinCreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	return nil
}

func (obj *GlobalConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling GlobalConfig: %w", err)
	}
	return nil
}

func UnmarshalGlobalConfig(buf []byte) (*GlobalConfig, error) {
	obj := new(GlobalConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Pool struct {
	PoolBump              uint8              `json:"poolBump"`
	Index                 uint16             `json:"index"`
	Creator               solanago.PublicKey `json:"creator"`
	BaseMint              solanago.PublicKey `json:"baseMint"`
	QuoteMint             solanago.PublicKey `json:"quoteMint"`
	LpMint                solanago.PublicKey `json:"lpMint"`
	PoolBaseTokenAccount  solanago.PublicKey `json:"poolBaseTokenAccount"`
	PoolQuoteTokenAccount solanago.PublicKey `json:"poolQuoteTokenAccount"`

	// True circulating supply without burns and lock-ups
	LpSupply    uint64             `json:"lpSupply"`
	CoinCreator solanago.PublicKey `json:"coinCreator"`
}

func (obj Pool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `PoolBump`:
	err = encoder.Encode(obj.PoolBump)
	if err != nil {
		return errors.NewField("PoolBump", err)
	}
	// Serialize `Index`:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `BaseMint`:
	err = encoder.Encode(obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Serialize `QuoteMint`:
	err = encoder.Encode(obj.QuoteMint)
	if err != nil {
		return errors.NewField("QuoteMint", err)
	}
	// Serialize `LpMint`:
	err = encoder.Encode(obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Serialize `PoolBaseTokenAccount`:
	err = encoder.Encode(obj.PoolBaseTokenAccount)
	if err != nil {
		return errors.NewField("PoolBaseTokenAccount", err)
	}
	// Serialize `PoolQuoteTokenAccount`:
	err = encoder.Encode(obj.PoolQuoteTokenAccount)
	if err != nil {
		return errors.NewField("PoolQuoteTokenAccount", err)
	}
	// Serialize `LpSupply`:
	err = encoder.Encode(obj.LpSupply)
	if err != nil {
		return errors.NewField("LpSupply", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj Pool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Pool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Pool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `PoolBump`:
	err = decoder.Decode(&obj.PoolBump)
	if err != nil {
		return errors.NewField("PoolBump", err)
	}
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return errors.NewField("Index", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `BaseMint`:
	err = decoder.Decode(&obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Deserialize `QuoteMint`:
	err = decoder.Decode(&obj.QuoteMint)
	if err != nil {
		return errors.NewField("QuoteMint", err)
	}
	// Deserialize `LpMint`:
	err = decoder.Decode(&obj.LpMint)
	if err != nil {
		return errors.NewField("LpMint", err)
	}
	// Deserialize `PoolBaseTokenAccount`:
	err = decoder.Decode(&obj.PoolBaseTokenAccount)
	if err != nil {
		return errors.NewField("PoolBaseTokenAccount", err)
	}
	// Deserialize `PoolQuoteTokenAccount`:
	err = decoder.Decode(&obj.PoolQuoteTokenAccount)
	if err != nil {
		return errors.NewField("PoolQuoteTokenAccount", err)
	}
	// Deserialize `LpSupply`:
	err = decoder.Decode(&obj.LpSupply)
	if err != nil {
		return errors.NewField("LpSupply", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj *Pool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Pool: %w", err)
	}
	return nil
}

func UnmarshalPool(buf []byte) (*Pool, error) {
	obj := new(Pool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SellEvent struct {
	Timestamp                        int64              `json:"timestamp"`
	BaseAmountIn                     uint64             `json:"baseAmountIn"`
	MinQuoteAmountOut                uint64             `json:"minQuoteAmountOut"`
	UserBaseTokenReserves            uint64             `json:"userBaseTokenReserves"`
	UserQuoteTokenReserves           uint64             `json:"userQuoteTokenReserves"`
	PoolBaseTokenReserves            uint64             `json:"poolBaseTokenReserves"`
	PoolQuoteTokenReserves           uint64             `json:"poolQuoteTokenReserves"`
	QuoteAmountOut                   uint64             `json:"quoteAmountOut"`
	LpFeeBasisPoints                 uint64             `json:"lpFeeBasisPoints"`
	LpFee                            uint64             `json:"lpFee"`
	ProtocolFeeBasisPoints           uint64             `json:"protocolFeeBasisPoints"`
	ProtocolFee                      uint64             `json:"protocolFee"`
	QuoteAmountOutWithoutLpFee       uint64             `json:"quoteAmountOutWithoutLpFee"`
	UserQuoteAmountOut               uint64             `json:"userQuoteAmountOut"`
	Pool                             solanago.PublicKey `json:"pool"`
	User                             solanago.PublicKey `json:"user"`
	UserBaseTokenAccount             solanago.PublicKey `json:"userBaseTokenAccount"`
	UserQuoteTokenAccount            solanago.PublicKey `json:"userQuoteTokenAccount"`
	ProtocolFeeRecipient             solanago.PublicKey `json:"protocolFeeRecipient"`
	ProtocolFeeRecipientTokenAccount solanago.PublicKey `json:"protocolFeeRecipientTokenAccount"`
	CoinCreator                      solanago.PublicKey `json:"coinCreator"`
	CoinCreatorFeeBasisPoints        uint64             `json:"coinCreatorFeeBasisPoints"`
	CoinCreatorFee                   uint64             `json:"coinCreatorFee"`
}

func (obj SellEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `BaseAmountIn`:
	err = encoder.Encode(obj.BaseAmountIn)
	if err != nil {
		return errors.NewField("BaseAmountIn", err)
	}
	// Serialize `MinQuoteAmountOut`:
	err = encoder.Encode(obj.MinQuoteAmountOut)
	if err != nil {
		return errors.NewField("MinQuoteAmountOut", err)
	}
	// Serialize `UserBaseTokenReserves`:
	err = encoder.Encode(obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Serialize `UserQuoteTokenReserves`:
	err = encoder.Encode(obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Serialize `PoolBaseTokenReserves`:
	err = encoder.Encode(obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Serialize `PoolQuoteTokenReserves`:
	err = encoder.Encode(obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Serialize `QuoteAmountOut`:
	err = encoder.Encode(obj.QuoteAmountOut)
	if err != nil {
		return errors.NewField("QuoteAmountOut", err)
	}
	// Serialize `LpFeeBasisPoints`:
	err = encoder.Encode(obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Serialize `LpFee`:
	err = encoder.Encode(obj.LpFee)
	if err != nil {
		return errors.NewField("LpFee", err)
	}
	// Serialize `ProtocolFeeBasisPoints`:
	err = encoder.Encode(obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Serialize `ProtocolFee`:
	err = encoder.Encode(obj.ProtocolFee)
	if err != nil {
		return errors.NewField("ProtocolFee", err)
	}
	// Serialize `QuoteAmountOutWithoutLpFee`:
	err = encoder.Encode(obj.QuoteAmountOutWithoutLpFee)
	if err != nil {
		return errors.NewField("QuoteAmountOutWithoutLpFee", err)
	}
	// Serialize `UserQuoteAmountOut`:
	err = encoder.Encode(obj.UserQuoteAmountOut)
	if err != nil {
		return errors.NewField("UserQuoteAmountOut", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `UserBaseTokenAccount`:
	err = encoder.Encode(obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Serialize `UserQuoteTokenAccount`:
	err = encoder.Encode(obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Serialize `ProtocolFeeRecipient`:
	err = encoder.Encode(obj.ProtocolFeeRecipient)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipient", err)
	}
	// Serialize `ProtocolFeeRecipientTokenAccount`:
	err = encoder.Encode(obj.ProtocolFeeRecipientTokenAccount)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipientTokenAccount", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	// Serialize `CoinCreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	// Serialize `CoinCreatorFee`:
	err = encoder.Encode(obj.CoinCreatorFee)
	if err != nil {
		return errors.NewField("CoinCreatorFee", err)
	}
	return nil
}

func (obj SellEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SellEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SellEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `BaseAmountIn`:
	err = decoder.Decode(&obj.BaseAmountIn)
	if err != nil {
		return errors.NewField("BaseAmountIn", err)
	}
	// Deserialize `MinQuoteAmountOut`:
	err = decoder.Decode(&obj.MinQuoteAmountOut)
	if err != nil {
		return errors.NewField("MinQuoteAmountOut", err)
	}
	// Deserialize `UserBaseTokenReserves`:
	err = decoder.Decode(&obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Deserialize `UserQuoteTokenReserves`:
	err = decoder.Decode(&obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Deserialize `PoolBaseTokenReserves`:
	err = decoder.Decode(&obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Deserialize `PoolQuoteTokenReserves`:
	err = decoder.Decode(&obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Deserialize `QuoteAmountOut`:
	err = decoder.Decode(&obj.QuoteAmountOut)
	if err != nil {
		return errors.NewField("QuoteAmountOut", err)
	}
	// Deserialize `LpFeeBasisPoints`:
	err = decoder.Decode(&obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Deserialize `LpFee`:
	err = decoder.Decode(&obj.LpFee)
	if err != nil {
		return errors.NewField("LpFee", err)
	}
	// Deserialize `ProtocolFeeBasisPoints`:
	err = decoder.Decode(&obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFee`:
	err = decoder.Decode(&obj.ProtocolFee)
	if err != nil {
		return errors.NewField("ProtocolFee", err)
	}
	// Deserialize `QuoteAmountOutWithoutLpFee`:
	err = decoder.Decode(&obj.QuoteAmountOutWithoutLpFee)
	if err != nil {
		return errors.NewField("QuoteAmountOutWithoutLpFee", err)
	}
	// Deserialize `UserQuoteAmountOut`:
	err = decoder.Decode(&obj.UserQuoteAmountOut)
	if err != nil {
		return errors.NewField("UserQuoteAmountOut", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `UserBaseTokenAccount`:
	err = decoder.Decode(&obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Deserialize `UserQuoteTokenAccount`:
	err = decoder.Decode(&obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Deserialize `ProtocolFeeRecipient`:
	err = decoder.Decode(&obj.ProtocolFeeRecipient)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipient", err)
	}
	// Deserialize `ProtocolFeeRecipientTokenAccount`:
	err = decoder.Decode(&obj.ProtocolFeeRecipientTokenAccount)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipientTokenAccount", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	// Deserialize `CoinCreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	// Deserialize `CoinCreatorFee`:
	err = decoder.Decode(&obj.CoinCreatorFee)
	if err != nil {
		return errors.NewField("CoinCreatorFee", err)
	}
	return nil
}

func (obj *SellEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SellEvent: %w", err)
	}
	return nil
}

func UnmarshalSellEvent(buf []byte) (*SellEvent, error) {
	obj := new(SellEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetBondingCurveCoinCreatorEvent struct {
	Timestamp    int64              `json:"timestamp"`
	BaseMint     solanago.PublicKey `json:"baseMint"`
	Pool         solanago.PublicKey `json:"pool"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	CoinCreator  solanago.PublicKey `json:"coinCreator"`
}

func (obj SetBondingCurveCoinCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `BaseMint`:
	err = encoder.Encode(obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj SetBondingCurveCoinCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetBondingCurveCoinCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetBondingCurveCoinCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `BaseMint`:
	err = decoder.Decode(&obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj *SetBondingCurveCoinCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetBondingCurveCoinCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSetBondingCurveCoinCreatorEvent(buf []byte) (*SetBondingCurveCoinCreatorEvent, error) {
	obj := new(SetBondingCurveCoinCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetMetaplexCoinCreatorEvent struct {
	Timestamp   int64              `json:"timestamp"`
	BaseMint    solanago.PublicKey `json:"baseMint"`
	Pool        solanago.PublicKey `json:"pool"`
	Metadata    solanago.PublicKey `json:"metadata"`
	CoinCreator solanago.PublicKey `json:"coinCreator"`
}

func (obj SetMetaplexCoinCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `BaseMint`:
	err = encoder.Encode(obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `Metadata`:
	err = encoder.Encode(obj.Metadata)
	if err != nil {
		return errors.NewField("Metadata", err)
	}
	// Serialize `CoinCreator`:
	err = encoder.Encode(obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj SetMetaplexCoinCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetMetaplexCoinCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetMetaplexCoinCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `BaseMint`:
	err = decoder.Decode(&obj.BaseMint)
	if err != nil {
		return errors.NewField("BaseMint", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `Metadata`:
	err = decoder.Decode(&obj.Metadata)
	if err != nil {
		return errors.NewField("Metadata", err)
	}
	// Deserialize `CoinCreator`:
	err = decoder.Decode(&obj.CoinCreator)
	if err != nil {
		return errors.NewField("CoinCreator", err)
	}
	return nil
}

func (obj *SetMetaplexCoinCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetMetaplexCoinCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSetMetaplexCoinCreatorEvent(buf []byte) (*SetMetaplexCoinCreatorEvent, error) {
	obj := new(SetMetaplexCoinCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UpdateAdminEvent struct {
	Timestamp int64              `json:"timestamp"`
	Admin     solanago.PublicKey `json:"admin"`
	NewAdmin  solanago.PublicKey `json:"newAdmin"`
}

func (obj UpdateAdminEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `NewAdmin`:
	err = encoder.Encode(obj.NewAdmin)
	if err != nil {
		return errors.NewField("NewAdmin", err)
	}
	return nil
}

func (obj UpdateAdminEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UpdateAdminEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UpdateAdminEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `NewAdmin`:
	err = decoder.Decode(&obj.NewAdmin)
	if err != nil {
		return errors.NewField("NewAdmin", err)
	}
	return nil
}

func (obj *UpdateAdminEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UpdateAdminEvent: %w", err)
	}
	return nil
}

func UnmarshalUpdateAdminEvent(buf []byte) (*UpdateAdminEvent, error) {
	obj := new(UpdateAdminEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UpdateFeeConfigEvent struct {
	Timestamp                 int64                 `json:"timestamp"`
	Admin                     solanago.PublicKey    `json:"admin"`
	LpFeeBasisPoints          uint64                `json:"lpFeeBasisPoints"`
	ProtocolFeeBasisPoints    uint64                `json:"protocolFeeBasisPoints"`
	ProtocolFeeRecipients     [8]solanago.PublicKey `json:"protocolFeeRecipients"`
	CoinCreatorFeeBasisPoints uint64                `json:"coinCreatorFeeBasisPoints"`
}

func (obj UpdateFeeConfigEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `LpFeeBasisPoints`:
	err = encoder.Encode(obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Serialize `ProtocolFeeBasisPoints`:
	err = encoder.Encode(obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Serialize `ProtocolFeeRecipients`:
	err = encoder.Encode(obj.ProtocolFeeRecipients)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipients", err)
	}
	// Serialize `CoinCreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	return nil
}

func (obj UpdateFeeConfigEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UpdateFeeConfigEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UpdateFeeConfigEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `LpFeeBasisPoints`:
	err = decoder.Decode(&obj.LpFeeBasisPoints)
	if err != nil {
		return errors.NewField("LpFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFeeBasisPoints`:
	err = decoder.Decode(&obj.ProtocolFeeBasisPoints)
	if err != nil {
		return errors.NewField("ProtocolFeeBasisPoints", err)
	}
	// Deserialize `ProtocolFeeRecipients`:
	err = decoder.Decode(&obj.ProtocolFeeRecipients)
	if err != nil {
		return errors.NewField("ProtocolFeeRecipients", err)
	}
	// Deserialize `CoinCreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CoinCreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CoinCreatorFeeBasisPoints", err)
	}
	return nil
}

func (obj *UpdateFeeConfigEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UpdateFeeConfigEvent: %w", err)
	}
	return nil
}

func UnmarshalUpdateFeeConfigEvent(buf []byte) (*UpdateFeeConfigEvent, error) {
	obj := new(UpdateFeeConfigEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WithdrawEvent struct {
	Timestamp              int64              `json:"timestamp"`
	LpTokenAmountIn        uint64             `json:"lpTokenAmountIn"`
	MinBaseAmountOut       uint64             `json:"minBaseAmountOut"`
	MinQuoteAmountOut      uint64             `json:"minQuoteAmountOut"`
	UserBaseTokenReserves  uint64             `json:"userBaseTokenReserves"`
	UserQuoteTokenReserves uint64             `json:"userQuoteTokenReserves"`
	PoolBaseTokenReserves  uint64             `json:"poolBaseTokenReserves"`
	PoolQuoteTokenReserves uint64             `json:"poolQuoteTokenReserves"`
	BaseAmountOut          uint64             `json:"baseAmountOut"`
	QuoteAmountOut         uint64             `json:"quoteAmountOut"`
	LpMintSupply           uint64             `json:"lpMintSupply"`
	Pool                   solanago.PublicKey `json:"pool"`
	User                   solanago.PublicKey `json:"user"`
	UserBaseTokenAccount   solanago.PublicKey `json:"userBaseTokenAccount"`
	UserQuoteTokenAccount  solanago.PublicKey `json:"userQuoteTokenAccount"`
	UserPoolTokenAccount   solanago.PublicKey `json:"userPoolTokenAccount"`
}

func (obj WithdrawEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `LpTokenAmountIn`:
	err = encoder.Encode(obj.LpTokenAmountIn)
	if err != nil {
		return errors.NewField("LpTokenAmountIn", err)
	}
	// Serialize `MinBaseAmountOut`:
	err = encoder.Encode(obj.MinBaseAmountOut)
	if err != nil {
		return errors.NewField("MinBaseAmountOut", err)
	}
	// Serialize `MinQuoteAmountOut`:
	err = encoder.Encode(obj.MinQuoteAmountOut)
	if err != nil {
		return errors.NewField("MinQuoteAmountOut", err)
	}
	// Serialize `UserBaseTokenReserves`:
	err = encoder.Encode(obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Serialize `UserQuoteTokenReserves`:
	err = encoder.Encode(obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Serialize `PoolBaseTokenReserves`:
	err = encoder.Encode(obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Serialize `PoolQuoteTokenReserves`:
	err = encoder.Encode(obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Serialize `BaseAmountOut`:
	err = encoder.Encode(obj.BaseAmountOut)
	if err != nil {
		return errors.NewField("BaseAmountOut", err)
	}
	// Serialize `QuoteAmountOut`:
	err = encoder.Encode(obj.QuoteAmountOut)
	if err != nil {
		return errors.NewField("QuoteAmountOut", err)
	}
	// Serialize `LpMintSupply`:
	err = encoder.Encode(obj.LpMintSupply)
	if err != nil {
		return errors.NewField("LpMintSupply", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `UserBaseTokenAccount`:
	err = encoder.Encode(obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Serialize `UserQuoteTokenAccount`:
	err = encoder.Encode(obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Serialize `UserPoolTokenAccount`:
	err = encoder.Encode(obj.UserPoolTokenAccount)
	if err != nil {
		return errors.NewField("UserPoolTokenAccount", err)
	}
	return nil
}

func (obj WithdrawEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WithdrawEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WithdrawEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `LpTokenAmountIn`:
	err = decoder.Decode(&obj.LpTokenAmountIn)
	if err != nil {
		return errors.NewField("LpTokenAmountIn", err)
	}
	// Deserialize `MinBaseAmountOut`:
	err = decoder.Decode(&obj.MinBaseAmountOut)
	if err != nil {
		return errors.NewField("MinBaseAmountOut", err)
	}
	// Deserialize `MinQuoteAmountOut`:
	err = decoder.Decode(&obj.MinQuoteAmountOut)
	if err != nil {
		return errors.NewField("MinQuoteAmountOut", err)
	}
	// Deserialize `UserBaseTokenReserves`:
	err = decoder.Decode(&obj.UserBaseTokenReserves)
	if err != nil {
		return errors.NewField("UserBaseTokenReserves", err)
	}
	// Deserialize `UserQuoteTokenReserves`:
	err = decoder.Decode(&obj.UserQuoteTokenReserves)
	if err != nil {
		return errors.NewField("UserQuoteTokenReserves", err)
	}
	// Deserialize `PoolBaseTokenReserves`:
	err = decoder.Decode(&obj.PoolBaseTokenReserves)
	if err != nil {
		return errors.NewField("PoolBaseTokenReserves", err)
	}
	// Deserialize `PoolQuoteTokenReserves`:
	err = decoder.Decode(&obj.PoolQuoteTokenReserves)
	if err != nil {
		return errors.NewField("PoolQuoteTokenReserves", err)
	}
	// Deserialize `BaseAmountOut`:
	err = decoder.Decode(&obj.BaseAmountOut)
	if err != nil {
		return errors.NewField("BaseAmountOut", err)
	}
	// Deserialize `QuoteAmountOut`:
	err = decoder.Decode(&obj.QuoteAmountOut)
	if err != nil {
		return errors.NewField("QuoteAmountOut", err)
	}
	// Deserialize `LpMintSupply`:
	err = decoder.Decode(&obj.LpMintSupply)
	if err != nil {
		return errors.NewField("LpMintSupply", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `UserBaseTokenAccount`:
	err = decoder.Decode(&obj.UserBaseTokenAccount)
	if err != nil {
		return errors.NewField("UserBaseTokenAccount", err)
	}
	// Deserialize `UserQuoteTokenAccount`:
	err = decoder.Decode(&obj.UserQuoteTokenAccount)
	if err != nil {
		return errors.NewField("UserQuoteTokenAccount", err)
	}
	// Deserialize `UserPoolTokenAccount`:
	err = decoder.Decode(&obj.UserPoolTokenAccount)
	if err != nil {
		return errors.NewField("UserPoolTokenAccount", err)
	}
	return nil
}

func (obj *WithdrawEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WithdrawEvent: %w", err)
	}
	return nil
}

func UnmarshalWithdrawEvent(buf []byte) (*WithdrawEvent, error) {
	obj := new(WithdrawEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
