// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains constants.

package lb_clmm

// Constants defined in the IDL:

const BASIS_POINT_MAX = int32(10000)
const MAX_BIN_PER_ARRAY = uint64(0x46)
const MAX_BIN_PER_POSITION = uint64(0x46)
const MAX_RESIZE_LENGTH = uint64(0x46)
const POSITION_MAX_LENGTH = uint64(0x578)
const MIN_BIN_ID = int32(-443636)
const MAX_BIN_ID = int32(443636)
const MAX_FEE_RATE = uint64(0x5f5e100)
const FEE_PRECISION = uint64(0x3b9aca00)
const MAX_PROTOCOL_SHARE = uint16(0x9c4)
const HOST_FEE_BPS = uint16(0x7d0)
const NUM_REWARDS = uint64(0x2)
const MIN_REWARD_DURATION = uint64(0x1)
const MAX_REWARD_DURATION = uint64(0x1e13380)
const EXTENSION_BINARRAY_BITMAP_SIZE = uint64(0xc)
const BIN_ARRAY_BITMAP_SIZE = int32(512)
const MAX_REWARD_BIN_SPLIT = uint64(0xf)
const ILM_PROTOCOL_SHARE = uint16(0x7d0)
const PROTOCOL_SHARE = uint16(0x1f4)
const MAX_BIN_STEP = uint16(0x190)
const MAX_BASE_FEE = uint64(0x5f5e100)
const MIN_BASE_FEE = uint64(0x186a0)
const MINIMUM_LIQUIDITY = uint64(0xf4240)

var BIN_ARRAY = []byte{98, 105, 110, 95, 97, 114, 114, 97, 121}
var ORACLE = []byte{111, 114, 97, 99, 108, 101}
var BIN_ARRAY_BITMAP_SEED = []byte{98, 105, 116, 109, 97, 112}
var PRESET_PARAMETER = []byte{112, 114, 101, 115, 101, 116, 95, 112, 97, 114, 97, 109, 101, 116, 101, 114}
var PRESET_PARAMETER2 = []byte{112, 114, 101, 115, 101, 116, 95, 112, 97, 114, 97, 109, 101, 116, 101, 114, 50}
var POSITION = []byte{112, 111, 115, 105, 116, 105, 111, 110}
var CLAIM_PROTOCOL_FEE_OPERATOR = []byte{99, 102, 95, 111, 112, 101, 114, 97, 116, 111, 114}
