// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package pump

// Account discriminators
var (
	Account_BondingCurve = [8]byte{23, 183, 248, 55, 96, 216, 172, 96}
	Account_Global       = [8]byte{167, 232, 232, 177, 200, 108, 114, 127}
)

// Event discriminators
var (
	Event_CollectCreatorFeeEvent        = [8]byte{122, 2, 127, 1, 14, 191, 12, 175}
	Event_CompleteEvent                 = [8]byte{95, 114, 97, 156, 212, 46, 152, 8}
	Event_CompletePumpAmmMigrationEvent = [8]byte{189, 233, 93, 185, 92, 148, 234, 148}
	Event_CreateEvent                   = [8]byte{27, 114, 169, 77, 222, 235, 99, 118}
	Event_ExtendAccountEvent            = [8]byte{97, 97, 215, 144, 93, 146, 22, 124}
	Event_SetCreatorEvent               = [8]byte{237, 52, 123, 37, 245, 251, 72, 210}
	Event_SetMetaplexCreatorEvent       = [8]byte{142, 203, 6, 32, 127, 105, 191, 162}
	Event_SetParamsEvent                = [8]byte{223, 195, 159, 246, 62, 48, 143, 131}
	Event_TradeEvent                    = [8]byte{189, 219, 127, 211, 78, 230, 97, 238}
	Event_UpdateGlobalAuthorityEvent    = [8]byte{182, 195, 137, 42, 35, 206, 207, 247}
)

// Instruction discriminators
var (
	Instruction_Buy                   = [8]byte{102, 6, 61, 18, 1, 218, 235, 234}
	Instruction_CollectCreatorFee     = [8]byte{20, 22, 86, 123, 198, 28, 219, 132}
	Instruction_Create                = [8]byte{24, 30, 200, 40, 5, 28, 7, 119}
	Instruction_ExtendAccount         = [8]byte{234, 102, 194, 203, 150, 72, 62, 229}
	Instruction_Initialize            = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_Migrate               = [8]byte{155, 234, 231, 146, 236, 158, 162, 30}
	Instruction_Sell                  = [8]byte{51, 230, 133, 164, 1, 127, 131, 173}
	Instruction_SetCreator            = [8]byte{254, 148, 255, 112, 207, 142, 170, 165}
	Instruction_SetMetaplexCreator    = [8]byte{138, 96, 174, 217, 48, 85, 197, 246}
	Instruction_SetParams             = [8]byte{27, 234, 178, 52, 147, 2, 187, 141}
	Instruction_UpdateGlobalAuthority = [8]byte{227, 181, 74, 196, 208, 21, 97, 213}
)
