// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package pump

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_CollectCreatorFeeEvent:
		value := new(CollectCreatorFeeEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CollectCreatorFeeEvent: %w", err)
		}
		return value, nil
	case Event_CompleteEvent:
		value := new(CompleteEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CompleteEvent: %w", err)
		}
		return value, nil
	case Event_CompletePumpAmmMigrationEvent:
		value := new(CompletePumpAmmMigrationEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CompletePumpAmmMigrationEvent: %w", err)
		}
		return value, nil
	case Event_CreateEvent:
		value := new(CreateEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as CreateEvent: %w", err)
		}
		return value, nil
	case Event_ExtendAccountEvent:
		value := new(ExtendAccountEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ExtendAccountEvent: %w", err)
		}
		return value, nil
	case Event_SetCreatorEvent:
		value := new(SetCreatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SetCreatorEvent: %w", err)
		}
		return value, nil
	case Event_SetMetaplexCreatorEvent:
		value := new(SetMetaplexCreatorEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SetMetaplexCreatorEvent: %w", err)
		}
		return value, nil
	case Event_SetParamsEvent:
		value := new(SetParamsEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SetParamsEvent: %w", err)
		}
		return value, nil
	case Event_TradeEvent:
		value := new(TradeEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TradeEvent: %w", err)
		}
		return value, nil
	case Event_UpdateGlobalAuthorityEvent:
		value := new(UpdateGlobalAuthorityEvent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as UpdateGlobalAuthorityEvent: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_CollectCreatorFeeEvent(eventData []byte) (*CollectCreatorFeeEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CollectCreatorFeeEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CollectCreatorFeeEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CollectCreatorFeeEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CollectCreatorFeeEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CompleteEvent(eventData []byte) (*CompleteEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CompleteEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CompleteEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CompleteEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CompleteEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CompletePumpAmmMigrationEvent(eventData []byte) (*CompletePumpAmmMigrationEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CompletePumpAmmMigrationEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CompletePumpAmmMigrationEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CompletePumpAmmMigrationEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CompletePumpAmmMigrationEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_CreateEvent(eventData []byte) (*CreateEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_CreateEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_CreateEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(CreateEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type CreateEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_ExtendAccountEvent(eventData []byte) (*ExtendAccountEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ExtendAccountEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ExtendAccountEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(ExtendAccountEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ExtendAccountEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SetCreatorEvent(eventData []byte) (*SetCreatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SetCreatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SetCreatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SetCreatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SetCreatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SetMetaplexCreatorEvent(eventData []byte) (*SetMetaplexCreatorEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SetMetaplexCreatorEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SetMetaplexCreatorEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SetMetaplexCreatorEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SetMetaplexCreatorEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_SetParamsEvent(eventData []byte) (*SetParamsEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SetParamsEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SetParamsEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(SetParamsEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SetParamsEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_TradeEvent(eventData []byte) (*TradeEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TradeEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TradeEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(TradeEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TradeEvent: %w", err)
	}
	return event, nil
}

func ParseEvent_UpdateGlobalAuthorityEvent(eventData []byte) (*UpdateGlobalAuthorityEvent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_UpdateGlobalAuthorityEvent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_UpdateGlobalAuthorityEvent, binary.FormatDiscriminator(discriminator))
	}
	event := new(UpdateGlobalAuthorityEvent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type UpdateGlobalAuthorityEvent: %w", err)
	}
	return event, nil
}
