// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package pump

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "buy" instruction.
// Buys tokens from a bonding curve.
func NewBuyInstruction(
	// Params:
	amountParam uint64,
	maxSolCostParam uint64,

	// Accounts:
	globalAccount solanago.PublicKey,
	feeRecipientAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	associatedBondingCurveAccount solanago.PublicKey,
	associatedUserAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	creatorVaultAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Buy[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `maxSolCostParam`:
		err = enc__.Encode(maxSolCostParam)
		if err != nil {
			return nil, errors.NewField("maxSolCostParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "global": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, false, false))
		// Account 1 "fee_recipient": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(feeRecipientAccount, true, false))
		// Account 2 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, true, false))
		// Account 4 "associated_bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedBondingCurveAccount, true, false))
		// Account 5 "associated_user": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedUserAccount, true, false))
		// Account 6 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 7 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 8 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "creator_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(creatorVaultAccount, true, false))
		// Account 10 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 11 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "collect_creator_fee" instruction.
// Collects creator_fee from creator_vault to the coin creator account
func NewCollectCreatorFeeInstruction(
	creatorAccount solanago.PublicKey,
	creatorVaultAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "creator": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(creatorAccount, true, true))
		// Account 1 "creator_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(creatorVaultAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create" instruction.
// Creates a new coin and bonding curve.
func NewCreateInstruction(
	// Params:
	nameParam string,
	symbolParam string,
	uriParam string,
	creatorParam solanago.PublicKey,

	// Accounts:
	mintAccount solanago.PublicKey,
	mintAuthorityAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	associatedBondingCurveAccount solanago.PublicKey,
	globalAccount solanago.PublicKey,
	mplTokenMetadataAccount solanago.PublicKey,
	metadataAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Create[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `nameParam`:
		err = enc__.Encode(nameParam)
		if err != nil {
			return nil, errors.NewField("nameParam", err)
		}
		// Serialize `symbolParam`:
		err = enc__.Encode(symbolParam)
		if err != nil {
			return nil, errors.NewField("symbolParam", err)
		}
		// Serialize `uriParam`:
		err = enc__.Encode(uriParam)
		if err != nil {
			return nil, errors.NewField("uriParam", err)
		}
		// Serialize `creatorParam`:
		err = enc__.Encode(creatorParam)
		if err != nil {
			return nil, errors.NewField("creatorParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "mint": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, true))
		// Account 1 "mint_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAuthorityAccount, false, false))
		// Account 2 "bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, true, false))
		// Account 3 "associated_bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedBondingCurveAccount, true, false))
		// Account 4 "global": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, false, false))
		// Account 5 "mpl_token_metadata": Read-only, Non-signer, Required, Address: metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
		accounts__.Append(solanago.NewAccountMeta(mplTokenMetadataAccount, false, false))
		// Account 6 "metadata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(metadataAccount, true, false))
		// Account 7 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 8 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 9 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 10 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 11 "rent": Read-only, Non-signer, Required, Address: SysvarRent111111111111111111111111111111111
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 12 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 13 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "extend_account" instruction.
// Extends the size of program-owned accounts
func NewExtendAccountInstruction(
	accountAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(accountAccount, true, false))
		// Account 1 "user": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, false, true))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "initialize" instruction.
// Creates the global state.
func NewInitializeInstruction(
	globalAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "global": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, true, false))
		// Account 1 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "migrate" instruction.
// Migrates liquidity to pump_amm if the bonding curve is complete
func NewMigrateInstruction(
	globalAccount solanago.PublicKey,
	withdrawAuthorityAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	associatedBondingCurveAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	pumpAmmAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	poolAuthorityAccount solanago.PublicKey,
	poolAuthorityMintAccountAccount solanago.PublicKey,
	poolAuthorityWsolAccountAccount solanago.PublicKey,
	ammGlobalConfigAccount solanago.PublicKey,
	wsolMintAccount solanago.PublicKey,
	lpMintAccount solanago.PublicKey,
	userPoolTokenAccountAccount solanago.PublicKey,
	poolBaseTokenAccountAccount solanago.PublicKey,
	poolQuoteTokenAccountAccount solanago.PublicKey,
	token2022ProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	pumpAmmEventAuthorityAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "global": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, false, false))
		// Account 1 "withdraw_authority": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(withdrawAuthorityAccount, true, false))
		// Account 2 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, true, false))
		// Account 4 "associated_bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedBondingCurveAccount, true, false))
		// Account 5 "user": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, false, true))
		// Account 6 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 7 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 8 "pump_amm": Read-only, Non-signer, Required, Address: pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA
		accounts__.Append(solanago.NewAccountMeta(pumpAmmAccount, false, false))
		// Account 9 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 10 "pool_authority": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAuthorityAccount, true, false))
		// Account 11 "pool_authority_mint_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAuthorityMintAccountAccount, true, false))
		// Account 12 "pool_authority_wsol_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAuthorityWsolAccountAccount, true, false))
		// Account 13 "amm_global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(ammGlobalConfigAccount, false, false))
		// Account 14 "wsol_mint": Read-only, Non-signer, Required, Address: So11111111111111111111111111111111111111112
		accounts__.Append(solanago.NewAccountMeta(wsolMintAccount, false, false))
		// Account 15 "lp_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpMintAccount, true, false))
		// Account 16 "user_pool_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userPoolTokenAccountAccount, true, false))
		// Account 17 "pool_base_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolBaseTokenAccountAccount, true, false))
		// Account 18 "pool_quote_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolQuoteTokenAccountAccount, true, false))
		// Account 19 "token_2022_program": Read-only, Non-signer, Required, Address: TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb
		accounts__.Append(solanago.NewAccountMeta(token2022ProgramAccount, false, false))
		// Account 20 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 21 "pump_amm_event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(pumpAmmEventAuthorityAccount, false, false))
		// Account 22 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 23 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "sell" instruction.
// Sells tokens into a bonding curve.
func NewSellInstruction(
	// Params:
	amountParam uint64,
	minSolOutputParam uint64,

	// Accounts:
	globalAccount solanago.PublicKey,
	feeRecipientAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	associatedBondingCurveAccount solanago.PublicKey,
	associatedUserAccount solanago.PublicKey,
	userAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	creatorVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Sell[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `minSolOutputParam`:
		err = enc__.Encode(minSolOutputParam)
		if err != nil {
			return nil, errors.NewField("minSolOutputParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "global": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, false, false))
		// Account 1 "fee_recipient": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(feeRecipientAccount, true, false))
		// Account 2 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, true, false))
		// Account 4 "associated_bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedBondingCurveAccount, true, false))
		// Account 5 "associated_user": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedUserAccount, true, false))
		// Account 6 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 7 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 8 "creator_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(creatorVaultAccount, true, false))
		// Account 9 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 10 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 11 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_creator" instruction.
// Allows Global::set_creator_authority to set the bonding curve creator from Metaplex metadata or input argument
func NewSetCreatorInstruction(
	// Params:
	creatorParam solanago.PublicKey,

	// Accounts:
	setCreatorAuthorityAccount solanago.PublicKey,
	globalAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	metadataAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetCreator[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `creatorParam`:
		err = enc__.Encode(creatorParam)
		if err != nil {
			return nil, errors.NewField("creatorParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "set_creator_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(setCreatorAuthorityAccount, false, true))
		// Account 1 "global": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, false, false))
		// Account 2 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "metadata": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(metadataAccount, false, false))
		// Account 4 "bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, true, false))
		// Account 5 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 6 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_metaplex_creator" instruction.
// Syncs the bonding curve creator with the Metaplex metadata creator if it exists
func NewSetMetaplexCreatorInstruction(
	mintAccount solanago.PublicKey,
	metadataAccount solanago.PublicKey,
	bondingCurveAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 1 "metadata": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(metadataAccount, false, false))
		// Account 2 "bonding_curve": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(bondingCurveAccount, true, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "set_params" instruction.
// Sets the global state parameters.
func NewSetParamsInstruction(
	// Params:
	initialVirtualTokenReservesParam uint64,
	initialVirtualSolReservesParam uint64,
	initialRealTokenReservesParam uint64,
	tokenTotalSupplyParam uint64,
	feeBasisPointsParam uint64,
	withdrawAuthorityParam solanago.PublicKey,
	enableMigrateParam bool,
	poolMigrationFeeParam uint64,
	creatorFeeBasisPointsParam uint64,
	setCreatorAuthorityParam solanago.PublicKey,

	// Accounts:
	globalAccount solanago.PublicKey,
	authorityAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetParams[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `initialVirtualTokenReservesParam`:
		err = enc__.Encode(initialVirtualTokenReservesParam)
		if err != nil {
			return nil, errors.NewField("initialVirtualTokenReservesParam", err)
		}
		// Serialize `initialVirtualSolReservesParam`:
		err = enc__.Encode(initialVirtualSolReservesParam)
		if err != nil {
			return nil, errors.NewField("initialVirtualSolReservesParam", err)
		}
		// Serialize `initialRealTokenReservesParam`:
		err = enc__.Encode(initialRealTokenReservesParam)
		if err != nil {
			return nil, errors.NewField("initialRealTokenReservesParam", err)
		}
		// Serialize `tokenTotalSupplyParam`:
		err = enc__.Encode(tokenTotalSupplyParam)
		if err != nil {
			return nil, errors.NewField("tokenTotalSupplyParam", err)
		}
		// Serialize `feeBasisPointsParam`:
		err = enc__.Encode(feeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("feeBasisPointsParam", err)
		}
		// Serialize `withdrawAuthorityParam`:
		err = enc__.Encode(withdrawAuthorityParam)
		if err != nil {
			return nil, errors.NewField("withdrawAuthorityParam", err)
		}
		// Serialize `enableMigrateParam`:
		err = enc__.Encode(enableMigrateParam)
		if err != nil {
			return nil, errors.NewField("enableMigrateParam", err)
		}
		// Serialize `poolMigrationFeeParam`:
		err = enc__.Encode(poolMigrationFeeParam)
		if err != nil {
			return nil, errors.NewField("poolMigrationFeeParam", err)
		}
		// Serialize `creatorFeeBasisPointsParam`:
		err = enc__.Encode(creatorFeeBasisPointsParam)
		if err != nil {
			return nil, errors.NewField("creatorFeeBasisPointsParam", err)
		}
		// Serialize `setCreatorAuthorityParam`:
		err = enc__.Encode(setCreatorAuthorityParam)
		if err != nil {
			return nil, errors.NewField("setCreatorAuthorityParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "global": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, true, false))
		// Account 1 "authority": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, true, true))
		// Account 2 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 3 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_global_authority" instruction.
func NewUpdateGlobalAuthorityInstruction(
	globalAccount solanago.PublicKey,
	authorityAccount solanago.PublicKey,
	newAuthorityAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "global": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalAccount, true, false))
		// Account 1 "authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, true))
		// Account 2 "new_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(newAuthorityAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}
