// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package pump

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type BondingCurve struct {
	VirtualTokenReserves uint64             `json:"virtualTokenReserves"`
	VirtualSolReserves   uint64             `json:"virtualSolReserves"`
	RealTokenReserves    uint64             `json:"realTokenReserves"`
	RealSolReserves      uint64             `json:"realSolReserves"`
	TokenTotalSupply     uint64             `json:"tokenTotalSupply"`
	Complete             bool               `json:"complete"`
	Creator              solanago.PublicKey `json:"creator"`
}

func (obj BondingCurve) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `RealSolReserves`:
	err = encoder.Encode(obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `Complete`:
	err = encoder.Encode(obj.Complete)
	if err != nil {
		return errors.NewField("Complete", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj BondingCurve) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BondingCurve: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BondingCurve) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `RealSolReserves`:
	err = decoder.Decode(&obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `Complete`:
	err = decoder.Decode(&obj.Complete)
	if err != nil {
		return errors.NewField("Complete", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj *BondingCurve) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BondingCurve: %w", err)
	}
	return nil
}

func UnmarshalBondingCurve(buf []byte) (*BondingCurve, error) {
	obj := new(BondingCurve)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CollectCreatorFeeEvent struct {
	Timestamp  int64              `json:"timestamp"`
	Creator    solanago.PublicKey `json:"creator"`
	CreatorFee uint64             `json:"creatorFee"`
}

func (obj CollectCreatorFeeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `CreatorFee`:
	err = encoder.Encode(obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	return nil
}

func (obj CollectCreatorFeeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CollectCreatorFeeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CollectCreatorFeeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `CreatorFee`:
	err = decoder.Decode(&obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	return nil
}

func (obj *CollectCreatorFeeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CollectCreatorFeeEvent: %w", err)
	}
	return nil
}

func UnmarshalCollectCreatorFeeEvent(buf []byte) (*CollectCreatorFeeEvent, error) {
	obj := new(CollectCreatorFeeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CompleteEvent struct {
	User         solanago.PublicKey `json:"user"`
	Mint         solanago.PublicKey `json:"mint"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	Timestamp    int64              `json:"timestamp"`
}

func (obj CompleteEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj CompleteEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CompleteEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CompleteEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *CompleteEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CompleteEvent: %w", err)
	}
	return nil
}

func UnmarshalCompleteEvent(buf []byte) (*CompleteEvent, error) {
	obj := new(CompleteEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CompletePumpAmmMigrationEvent struct {
	User             solanago.PublicKey `json:"user"`
	Mint             solanago.PublicKey `json:"mint"`
	MintAmount       uint64             `json:"mintAmount"`
	SolAmount        uint64             `json:"solAmount"`
	PoolMigrationFee uint64             `json:"poolMigrationFee"`
	BondingCurve     solanago.PublicKey `json:"bondingCurve"`
	Timestamp        int64              `json:"timestamp"`
	Pool             solanago.PublicKey `json:"pool"`
}

func (obj CompletePumpAmmMigrationEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `MintAmount`:
	err = encoder.Encode(obj.MintAmount)
	if err != nil {
		return errors.NewField("MintAmount", err)
	}
	// Serialize `SolAmount`:
	err = encoder.Encode(obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Serialize `PoolMigrationFee`:
	err = encoder.Encode(obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	return nil
}

func (obj CompletePumpAmmMigrationEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CompletePumpAmmMigrationEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CompletePumpAmmMigrationEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `MintAmount`:
	err = decoder.Decode(&obj.MintAmount)
	if err != nil {
		return errors.NewField("MintAmount", err)
	}
	// Deserialize `SolAmount`:
	err = decoder.Decode(&obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Deserialize `PoolMigrationFee`:
	err = decoder.Decode(&obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	return nil
}

func (obj *CompletePumpAmmMigrationEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CompletePumpAmmMigrationEvent: %w", err)
	}
	return nil
}

func UnmarshalCompletePumpAmmMigrationEvent(buf []byte) (*CompletePumpAmmMigrationEvent, error) {
	obj := new(CompletePumpAmmMigrationEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type CreateEvent struct {
	Name                 string             `json:"name"`
	Symbol               string             `json:"symbol"`
	Uri                  string             `json:"uri"`
	Mint                 solanago.PublicKey `json:"mint"`
	BondingCurve         solanago.PublicKey `json:"bondingCurve"`
	User                 solanago.PublicKey `json:"user"`
	Creator              solanago.PublicKey `json:"creator"`
	Timestamp            int64              `json:"timestamp"`
	VirtualTokenReserves uint64             `json:"virtualTokenReserves"`
	VirtualSolReserves   uint64             `json:"virtualSolReserves"`
	RealTokenReserves    uint64             `json:"realTokenReserves"`
	TokenTotalSupply     uint64             `json:"tokenTotalSupply"`
}

func (obj CreateEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Name`:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return errors.NewField("Name", err)
	}
	// Serialize `Symbol`:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	// Serialize `Uri`:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return errors.NewField("Uri", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	return nil
}

func (obj CreateEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding CreateEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *CreateEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return errors.NewField("Name", err)
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	// Deserialize `Uri`:
	err = decoder.Decode(&obj.Uri)
	if err != nil {
		return errors.NewField("Uri", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	return nil
}

func (obj *CreateEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling CreateEvent: %w", err)
	}
	return nil
}

func UnmarshalCreateEvent(buf []byte) (*CreateEvent, error) {
	obj := new(CreateEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ExtendAccountEvent struct {
	Account     solanago.PublicKey `json:"account"`
	User        solanago.PublicKey `json:"user"`
	CurrentSize uint64             `json:"currentSize"`
	NewSize     uint64             `json:"newSize"`
	Timestamp   int64              `json:"timestamp"`
}

func (obj ExtendAccountEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Account`:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `CurrentSize`:
	err = encoder.Encode(obj.CurrentSize)
	if err != nil {
		return errors.NewField("CurrentSize", err)
	}
	// Serialize `NewSize`:
	err = encoder.Encode(obj.NewSize)
	if err != nil {
		return errors.NewField("NewSize", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj ExtendAccountEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ExtendAccountEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ExtendAccountEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `CurrentSize`:
	err = decoder.Decode(&obj.CurrentSize)
	if err != nil {
		return errors.NewField("CurrentSize", err)
	}
	// Deserialize `NewSize`:
	err = decoder.Decode(&obj.NewSize)
	if err != nil {
		return errors.NewField("NewSize", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *ExtendAccountEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ExtendAccountEvent: %w", err)
	}
	return nil
}

func UnmarshalExtendAccountEvent(buf []byte) (*ExtendAccountEvent, error) {
	obj := new(ExtendAccountEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Global struct {
	// Unused
	Initialized                 bool               `json:"initialized"`
	Authority                   solanago.PublicKey `json:"authority"`
	FeeRecipient                solanago.PublicKey `json:"feeRecipient"`
	InitialVirtualTokenReserves uint64             `json:"initialVirtualTokenReserves"`
	InitialVirtualSolReserves   uint64             `json:"initialVirtualSolReserves"`
	InitialRealTokenReserves    uint64             `json:"initialRealTokenReserves"`
	TokenTotalSupply            uint64             `json:"tokenTotalSupply"`
	FeeBasisPoints              uint64             `json:"feeBasisPoints"`
	WithdrawAuthority           solanago.PublicKey `json:"withdrawAuthority"`

	// Unused
	EnableMigrate         bool                  `json:"enableMigrate"`
	PoolMigrationFee      uint64                `json:"poolMigrationFee"`
	CreatorFeeBasisPoints uint64                `json:"creatorFeeBasisPoints"`
	FeeRecipients         [7]solanago.PublicKey `json:"feeRecipients"`
	SetCreatorAuthority   solanago.PublicKey    `json:"setCreatorAuthority"`
}

func (obj Global) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Initialized`:
	err = encoder.Encode(obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `FeeRecipient`:
	err = encoder.Encode(obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Serialize `InitialVirtualTokenReserves`:
	err = encoder.Encode(obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Serialize `InitialVirtualSolReserves`:
	err = encoder.Encode(obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Serialize `InitialRealTokenReserves`:
	err = encoder.Encode(obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `FeeBasisPoints`:
	err = encoder.Encode(obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Serialize `WithdrawAuthority`:
	err = encoder.Encode(obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Serialize `EnableMigrate`:
	err = encoder.Encode(obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Serialize `PoolMigrationFee`:
	err = encoder.Encode(obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Serialize `CreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Serialize `FeeRecipients`:
	err = encoder.Encode(obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Serialize `SetCreatorAuthority`:
	err = encoder.Encode(obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	return nil
}

func (obj Global) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Global: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Global) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Initialized`:
	err = decoder.Decode(&obj.Initialized)
	if err != nil {
		return errors.NewField("Initialized", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `FeeRecipient`:
	err = decoder.Decode(&obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Deserialize `InitialVirtualTokenReserves`:
	err = decoder.Decode(&obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Deserialize `InitialVirtualSolReserves`:
	err = decoder.Decode(&obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Deserialize `InitialRealTokenReserves`:
	err = decoder.Decode(&obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `FeeBasisPoints`:
	err = decoder.Decode(&obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Deserialize `WithdrawAuthority`:
	err = decoder.Decode(&obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Deserialize `EnableMigrate`:
	err = decoder.Decode(&obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Deserialize `PoolMigrationFee`:
	err = decoder.Decode(&obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Deserialize `CreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Deserialize `FeeRecipients`:
	err = decoder.Decode(&obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Deserialize `SetCreatorAuthority`:
	err = decoder.Decode(&obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	return nil
}

func (obj *Global) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Global: %w", err)
	}
	return nil
}

func UnmarshalGlobal(buf []byte) (*Global, error) {
	obj := new(Global)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetCreatorEvent struct {
	Timestamp    int64              `json:"timestamp"`
	Mint         solanago.PublicKey `json:"mint"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	Creator      solanago.PublicKey `json:"creator"`
}

func (obj SetCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj SetCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj *SetCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSetCreatorEvent(buf []byte) (*SetCreatorEvent, error) {
	obj := new(SetCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetMetaplexCreatorEvent struct {
	Timestamp    int64              `json:"timestamp"`
	Mint         solanago.PublicKey `json:"mint"`
	BondingCurve solanago.PublicKey `json:"bondingCurve"`
	Metadata     solanago.PublicKey `json:"metadata"`
	Creator      solanago.PublicKey `json:"creator"`
}

func (obj SetMetaplexCreatorEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `BondingCurve`:
	err = encoder.Encode(obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Serialize `Metadata`:
	err = encoder.Encode(obj.Metadata)
	if err != nil {
		return errors.NewField("Metadata", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj SetMetaplexCreatorEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetMetaplexCreatorEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetMetaplexCreatorEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `BondingCurve`:
	err = decoder.Decode(&obj.BondingCurve)
	if err != nil {
		return errors.NewField("BondingCurve", err)
	}
	// Deserialize `Metadata`:
	err = decoder.Decode(&obj.Metadata)
	if err != nil {
		return errors.NewField("Metadata", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	return nil
}

func (obj *SetMetaplexCreatorEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetMetaplexCreatorEvent: %w", err)
	}
	return nil
}

func UnmarshalSetMetaplexCreatorEvent(buf []byte) (*SetMetaplexCreatorEvent, error) {
	obj := new(SetMetaplexCreatorEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type SetParamsEvent struct {
	InitialVirtualTokenReserves uint64                `json:"initialVirtualTokenReserves"`
	InitialVirtualSolReserves   uint64                `json:"initialVirtualSolReserves"`
	InitialRealTokenReserves    uint64                `json:"initialRealTokenReserves"`
	FinalRealSolReserves        uint64                `json:"finalRealSolReserves"`
	TokenTotalSupply            uint64                `json:"tokenTotalSupply"`
	FeeBasisPoints              uint64                `json:"feeBasisPoints"`
	WithdrawAuthority           solanago.PublicKey    `json:"withdrawAuthority"`
	EnableMigrate               bool                  `json:"enableMigrate"`
	PoolMigrationFee            uint64                `json:"poolMigrationFee"`
	CreatorFeeBasisPoints       uint64                `json:"creatorFeeBasisPoints"`
	FeeRecipients               [8]solanago.PublicKey `json:"feeRecipients"`
	Timestamp                   int64                 `json:"timestamp"`
	SetCreatorAuthority         solanago.PublicKey    `json:"setCreatorAuthority"`
}

func (obj SetParamsEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `InitialVirtualTokenReserves`:
	err = encoder.Encode(obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Serialize `InitialVirtualSolReserves`:
	err = encoder.Encode(obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Serialize `InitialRealTokenReserves`:
	err = encoder.Encode(obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Serialize `FinalRealSolReserves`:
	err = encoder.Encode(obj.FinalRealSolReserves)
	if err != nil {
		return errors.NewField("FinalRealSolReserves", err)
	}
	// Serialize `TokenTotalSupply`:
	err = encoder.Encode(obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Serialize `FeeBasisPoints`:
	err = encoder.Encode(obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Serialize `WithdrawAuthority`:
	err = encoder.Encode(obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Serialize `EnableMigrate`:
	err = encoder.Encode(obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Serialize `PoolMigrationFee`:
	err = encoder.Encode(obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Serialize `CreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Serialize `FeeRecipients`:
	err = encoder.Encode(obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `SetCreatorAuthority`:
	err = encoder.Encode(obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	return nil
}

func (obj SetParamsEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SetParamsEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SetParamsEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `InitialVirtualTokenReserves`:
	err = decoder.Decode(&obj.InitialVirtualTokenReserves)
	if err != nil {
		return errors.NewField("InitialVirtualTokenReserves", err)
	}
	// Deserialize `InitialVirtualSolReserves`:
	err = decoder.Decode(&obj.InitialVirtualSolReserves)
	if err != nil {
		return errors.NewField("InitialVirtualSolReserves", err)
	}
	// Deserialize `InitialRealTokenReserves`:
	err = decoder.Decode(&obj.InitialRealTokenReserves)
	if err != nil {
		return errors.NewField("InitialRealTokenReserves", err)
	}
	// Deserialize `FinalRealSolReserves`:
	err = decoder.Decode(&obj.FinalRealSolReserves)
	if err != nil {
		return errors.NewField("FinalRealSolReserves", err)
	}
	// Deserialize `TokenTotalSupply`:
	err = decoder.Decode(&obj.TokenTotalSupply)
	if err != nil {
		return errors.NewField("TokenTotalSupply", err)
	}
	// Deserialize `FeeBasisPoints`:
	err = decoder.Decode(&obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Deserialize `WithdrawAuthority`:
	err = decoder.Decode(&obj.WithdrawAuthority)
	if err != nil {
		return errors.NewField("WithdrawAuthority", err)
	}
	// Deserialize `EnableMigrate`:
	err = decoder.Decode(&obj.EnableMigrate)
	if err != nil {
		return errors.NewField("EnableMigrate", err)
	}
	// Deserialize `PoolMigrationFee`:
	err = decoder.Decode(&obj.PoolMigrationFee)
	if err != nil {
		return errors.NewField("PoolMigrationFee", err)
	}
	// Deserialize `CreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Deserialize `FeeRecipients`:
	err = decoder.Decode(&obj.FeeRecipients)
	if err != nil {
		return errors.NewField("FeeRecipients", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `SetCreatorAuthority`:
	err = decoder.Decode(&obj.SetCreatorAuthority)
	if err != nil {
		return errors.NewField("SetCreatorAuthority", err)
	}
	return nil
}

func (obj *SetParamsEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SetParamsEvent: %w", err)
	}
	return nil
}

func UnmarshalSetParamsEvent(buf []byte) (*SetParamsEvent, error) {
	obj := new(SetParamsEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TradeEvent struct {
	Mint                  solanago.PublicKey `json:"mint"`
	SolAmount             uint64             `json:"solAmount"`
	TokenAmount           uint64             `json:"tokenAmount"`
	IsBuy                 bool               `json:"isBuy"`
	User                  solanago.PublicKey `json:"user"`
	Timestamp             int64              `json:"timestamp"`
	VirtualSolReserves    uint64             `json:"virtualSolReserves"`
	VirtualTokenReserves  uint64             `json:"virtualTokenReserves"`
	RealSolReserves       uint64             `json:"realSolReserves"`
	RealTokenReserves     uint64             `json:"realTokenReserves"`
	FeeRecipient          solanago.PublicKey `json:"feeRecipient"`
	FeeBasisPoints        uint64             `json:"feeBasisPoints"`
	Fee                   uint64             `json:"fee"`
	Creator               solanago.PublicKey `json:"creator"`
	CreatorFeeBasisPoints uint64             `json:"creatorFeeBasisPoints"`
	CreatorFee            uint64             `json:"creatorFee"`
}

func (obj TradeEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `SolAmount`:
	err = encoder.Encode(obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Serialize `TokenAmount`:
	err = encoder.Encode(obj.TokenAmount)
	if err != nil {
		return errors.NewField("TokenAmount", err)
	}
	// Serialize `IsBuy`:
	err = encoder.Encode(obj.IsBuy)
	if err != nil {
		return errors.NewField("IsBuy", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `VirtualSolReserves`:
	err = encoder.Encode(obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Serialize `VirtualTokenReserves`:
	err = encoder.Encode(obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Serialize `RealSolReserves`:
	err = encoder.Encode(obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Serialize `RealTokenReserves`:
	err = encoder.Encode(obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Serialize `FeeRecipient`:
	err = encoder.Encode(obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Serialize `FeeBasisPoints`:
	err = encoder.Encode(obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Serialize `Fee`:
	err = encoder.Encode(obj.Fee)
	if err != nil {
		return errors.NewField("Fee", err)
	}
	// Serialize `Creator`:
	err = encoder.Encode(obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Serialize `CreatorFeeBasisPoints`:
	err = encoder.Encode(obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Serialize `CreatorFee`:
	err = encoder.Encode(obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	return nil
}

func (obj TradeEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TradeEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TradeEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `SolAmount`:
	err = decoder.Decode(&obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	// Deserialize `TokenAmount`:
	err = decoder.Decode(&obj.TokenAmount)
	if err != nil {
		return errors.NewField("TokenAmount", err)
	}
	// Deserialize `IsBuy`:
	err = decoder.Decode(&obj.IsBuy)
	if err != nil {
		return errors.NewField("IsBuy", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `VirtualSolReserves`:
	err = decoder.Decode(&obj.VirtualSolReserves)
	if err != nil {
		return errors.NewField("VirtualSolReserves", err)
	}
	// Deserialize `VirtualTokenReserves`:
	err = decoder.Decode(&obj.VirtualTokenReserves)
	if err != nil {
		return errors.NewField("VirtualTokenReserves", err)
	}
	// Deserialize `RealSolReserves`:
	err = decoder.Decode(&obj.RealSolReserves)
	if err != nil {
		return errors.NewField("RealSolReserves", err)
	}
	// Deserialize `RealTokenReserves`:
	err = decoder.Decode(&obj.RealTokenReserves)
	if err != nil {
		return errors.NewField("RealTokenReserves", err)
	}
	// Deserialize `FeeRecipient`:
	err = decoder.Decode(&obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Deserialize `FeeBasisPoints`:
	err = decoder.Decode(&obj.FeeBasisPoints)
	if err != nil {
		return errors.NewField("FeeBasisPoints", err)
	}
	// Deserialize `Fee`:
	err = decoder.Decode(&obj.Fee)
	if err != nil {
		return errors.NewField("Fee", err)
	}
	// Deserialize `Creator`:
	err = decoder.Decode(&obj.Creator)
	if err != nil {
		return errors.NewField("Creator", err)
	}
	// Deserialize `CreatorFeeBasisPoints`:
	err = decoder.Decode(&obj.CreatorFeeBasisPoints)
	if err != nil {
		return errors.NewField("CreatorFeeBasisPoints", err)
	}
	// Deserialize `CreatorFee`:
	err = decoder.Decode(&obj.CreatorFee)
	if err != nil {
		return errors.NewField("CreatorFee", err)
	}
	return nil
}

func (obj *TradeEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TradeEvent: %w", err)
	}
	return nil
}

func UnmarshalTradeEvent(buf []byte) (*TradeEvent, error) {
	obj := new(TradeEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UpdateGlobalAuthorityEvent struct {
	Global       solanago.PublicKey `json:"global"`
	Authority    solanago.PublicKey `json:"authority"`
	NewAuthority solanago.PublicKey `json:"newAuthority"`
	Timestamp    int64              `json:"timestamp"`
}

func (obj UpdateGlobalAuthorityEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Global`:
	err = encoder.Encode(obj.Global)
	if err != nil {
		return errors.NewField("Global", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `NewAuthority`:
	err = encoder.Encode(obj.NewAuthority)
	if err != nil {
		return errors.NewField("NewAuthority", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj UpdateGlobalAuthorityEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UpdateGlobalAuthorityEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UpdateGlobalAuthorityEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Global`:
	err = decoder.Decode(&obj.Global)
	if err != nil {
		return errors.NewField("Global", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `NewAuthority`:
	err = decoder.Decode(&obj.NewAuthority)
	if err != nil {
		return errors.NewField("NewAuthority", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *UpdateGlobalAuthorityEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UpdateGlobalAuthorityEvent: %w", err)
	}
	return nil
}

func UnmarshalUpdateGlobalAuthorityEvent(buf []byte) (*UpdateGlobalAuthorityEvent, error) {
	obj := new(UpdateGlobalAuthorityEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
