// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package tuna

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_FusionPool:
		value := new(FusionPool)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as FusionPool: %w", err)
		}
		return value, nil
	case Account_LendingPosition:
		value := new(LendingPosition)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as LendingPosition: %w", err)
		}
		return value, nil
	case Account_Market:
		value := new(Market)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Market: %w", err)
		}
		return value, nil
	case Account_TunaConfig:
		value := new(TunaConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TunaConfig: %w", err)
		}
		return value, nil
	case Account_TunaPosition:
		value := new(TunaPosition)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TunaPosition: %w", err)
		}
		return value, nil
	case Account_Vault:
		value := new(Vault)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Vault: %w", err)
		}
		return value, nil
	case Account_Whirlpool:
		value := new(Whirlpool)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Whirlpool: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_FusionPool(accountData []byte) (*FusionPool, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_FusionPool {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_FusionPool, binary.FormatDiscriminator(discriminator))
	}
	acc := new(FusionPool)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type FusionPool: %w", err)
	}
	return acc, nil
}

func ParseAccount_LendingPosition(accountData []byte) (*LendingPosition, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_LendingPosition {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_LendingPosition, binary.FormatDiscriminator(discriminator))
	}
	acc := new(LendingPosition)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type LendingPosition: %w", err)
	}
	return acc, nil
}

func ParseAccount_Market(accountData []byte) (*Market, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Market {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Market, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Market)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Market: %w", err)
	}
	return acc, nil
}

func ParseAccount_TunaConfig(accountData []byte) (*TunaConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TunaConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TunaConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TunaConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TunaConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_TunaPosition(accountData []byte) (*TunaPosition, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TunaPosition {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TunaPosition, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TunaPosition)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TunaPosition: %w", err)
	}
	return acc, nil
}

func ParseAccount_Vault(accountData []byte) (*Vault, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Vault {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Vault, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Vault)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Vault: %w", err)
	}
	return acc, nil
}

func ParseAccount_Whirlpool(accountData []byte) (*Whirlpool, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Whirlpool {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Whirlpool, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Whirlpool)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Whirlpool: %w", err)
	}
	return acc, nil
}
