// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package tuna

// Account discriminators
var (
	Account_FusionPool      = [8]byte{254, 204, 207, 98, 25, 181, 29, 67}
	Account_LendingPosition = [8]byte{47, 255, 252, 35, 20, 245, 157, 243}
	Account_Market          = [8]byte{219, 190, 213, 55, 0, 227, 198, 154}
	Account_TunaConfig      = [8]byte{124, 149, 24, 7, 195, 168, 153, 58}
	Account_TunaPosition    = [8]byte{76, 197, 161, 51, 232, 15, 137, 220}
	Account_Vault           = [8]byte{211, 8, 232, 43, 2, 152, 117, 119}
	Account_Whirlpool       = [8]byte{63, 149, 209, 12, 225, 128, 99, 9}
)

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_AddLiquidityFusion                      = [8]byte{186, 221, 60, 139, 153, 11, 193, 11}
	Instruction_AddLiquidityOrca                        = [8]byte{185, 68, 41, 204, 33, 179, 12, 78}
	Instruction_ClosePositionFusion                     = [8]byte{91, 149, 37, 23, 74, 118, 53, 119}
	Instruction_ClosePositionOrca                       = [8]byte{253, 98, 90, 239, 191, 36, 161, 26}
	Instruction_CollectAndCompoundFeesFusion            = [8]byte{61, 213, 30, 201, 89, 220, 156, 13}
	Instruction_CollectAndCompoundFeesOrca              = [8]byte{213, 44, 171, 74, 209, 13, 137, 0}
	Instruction_CollectFeesFusion                       = [8]byte{52, 219, 25, 250, 31, 203, 9, 129}
	Instruction_CollectFeesOrca                         = [8]byte{147, 188, 191, 37, 255, 10, 239, 76}
	Instruction_CollectRewardOrca                       = [8]byte{99, 253, 84, 63, 250, 243, 165, 191}
	Instruction_CreateMarket                            = [8]byte{103, 226, 97, 235, 200, 188, 251, 254}
	Instruction_CreateTunaConfig                        = [8]byte{79, 78, 175, 62, 234, 68, 202, 241}
	Instruction_CreateVault                             = [8]byte{29, 237, 247, 208, 193, 82, 54, 135}
	Instruction_Deposit                                 = [8]byte{242, 35, 198, 137, 82, 225, 242, 182}
	Instruction_LiquidatePositionFusion                 = [8]byte{57, 160, 162, 122, 114, 173, 138, 220}
	Instruction_LiquidatePositionOrca                   = [8]byte{62, 92, 176, 35, 164, 100, 46, 141}
	Instruction_OpenLendingPosition                     = [8]byte{174, 227, 181, 127, 78, 227, 244, 19}
	Instruction_OpenPositionFusion                      = [8]byte{78, 68, 77, 41, 132, 42, 34, 238}
	Instruction_OpenPositionOrca                        = [8]byte{201, 85, 45, 226, 182, 208, 246, 115}
	Instruction_OpenPositionWithLiquidityFusion         = [8]byte{123, 115, 192, 91, 113, 191, 73, 56}
	Instruction_OpenPositionWithLiquidityOrca           = [8]byte{163, 21, 84, 199, 172, 40, 87, 122}
	Instruction_RebalancePositionFusion                 = [8]byte{190, 86, 41, 87, 5, 231, 10, 51}
	Instruction_RebalancePositionOrca                   = [8]byte{124, 212, 164, 128, 31, 143, 101, 231}
	Instruction_RemoveLiquidityFusion                   = [8]byte{175, 74, 205, 238, 4, 123, 166, 35}
	Instruction_RemoveLiquidityOrca                     = [8]byte{30, 69, 45, 170, 183, 195, 12, 119}
	Instruction_RepayBadDebt                            = [8]byte{112, 144, 188, 157, 43, 106, 141, 34}
	Instruction_RepayDebt                               = [8]byte{79, 200, 30, 15, 252, 22, 162, 8}
	Instruction_SetAdminAuthority                       = [8]byte{72, 49, 37, 167, 149, 98, 49, 174}
	Instruction_SetDefaultMaxPercentageOfLeftovers      = [8]byte{37, 179, 107, 65, 203, 141, 183, 27}
	Instruction_SetDefaultMaxSwapSlippage               = [8]byte{122, 22, 122, 128, 248, 196, 227, 181}
	Instruction_SetDefaultOraclePriceDeviationThreshold = [8]byte{142, 158, 143, 67, 206, 91, 139, 120}
	Instruction_SetFeeRecipient                         = [8]byte{227, 18, 215, 42, 237, 246, 151, 66}
	Instruction_SetLimitOrders                          = [8]byte{65, 128, 90, 161, 171, 133, 122, 255}
	Instruction_SetLiquidatorAuthority                  = [8]byte{246, 146, 22, 66, 159, 216, 172, 143}
	Instruction_SetOwnerAuthority                       = [8]byte{128, 171, 210, 21, 103, 179, 80, 117}
	Instruction_SetSuspendedState                       = [8]byte{145, 13, 20, 161, 30, 62, 226, 32}
	Instruction_SetTunaPositionFlags                    = [8]byte{110, 73, 96, 139, 194, 71, 253, 57}
	Instruction_SetTunaPositionRebalanceThreshold       = [8]byte{108, 170, 86, 159, 171, 164, 28, 51}
	Instruction_UpdateMarket                            = [8]byte{153, 39, 2, 197, 179, 50, 199, 217}
	Instruction_UpdateVault                             = [8]byte{67, 229, 185, 188, 226, 11, 210, 60}
	Instruction_Withdraw                                = [8]byte{183, 18, 70, 156, 148, 109, 161, 34}
)
