// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package tuna

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("tuna4uSQZncNeeiAMKbstuxA9CUkHH6HmC64wgmnogD")
