// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package tuna

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type AccountsType binary.BorshEnum

const (
	AccountsType_SwapTickArrays AccountsType = iota
	AccountsType_TickArrayLower
	AccountsType_TickArrayUpper
	AccountsType_PoolVaultTokenA
	AccountsType_PoolVaultTokenB
	AccountsType_WhirlpoolOracle
	AccountsType_Rewards
	AccountsType_SecondaryTickArrayLower
	AccountsType_SecondaryTickArrayUpper
)

func (value AccountsType) String() string {
	switch value {
	case AccountsType_SwapTickArrays:
		return "SwapTickArrays"
	case AccountsType_TickArrayLower:
		return "TickArrayLower"
	case AccountsType_TickArrayUpper:
		return "TickArrayUpper"
	case AccountsType_PoolVaultTokenA:
		return "PoolVaultTokenA"
	case AccountsType_PoolVaultTokenB:
		return "PoolVaultTokenB"
	case AccountsType_WhirlpoolOracle:
		return "WhirlpoolOracle"
	case AccountsType_Rewards:
		return "Rewards"
	case AccountsType_SecondaryTickArrayLower:
		return "SecondaryTickArrayLower"
	case AccountsType_SecondaryTickArrayUpper:
		return "SecondaryTickArrayUpper"
	default:
		return ""
	}
}

type FusionPool struct {
	Bump                 [1]uint8           `json:"bump"`
	Version              uint16             `json:"version"`
	TokenMintA           solanago.PublicKey `json:"tokenMintA"`
	TokenMintB           solanago.PublicKey `json:"tokenMintB"`
	TokenVaultA          solanago.PublicKey `json:"tokenVaultA"`
	TokenVaultB          solanago.PublicKey `json:"tokenVaultB"`
	TickSpacing          uint16             `json:"tickSpacing"`
	TickSpacingSeed      [2]uint8           `json:"tickSpacingSeed"`
	FeeRate              uint16             `json:"feeRate"`
	ProtocolFeeRate      uint16             `json:"protocolFeeRate"`
	ClpRewardRate        uint16             `json:"clpRewardRate"`
	OrderProtocolFeeRate uint16             `json:"orderProtocolFeeRate"`
	Liquidity            binary.Uint128     `json:"liquidity"`
	SqrtPrice            binary.Uint128     `json:"sqrtPrice"`
	TickCurrentIndex     int32              `json:"tickCurrentIndex"`
	ProtocolFeeOwedA     uint64             `json:"protocolFeeOwedA"`
	ProtocolFeeOwedB     uint64             `json:"protocolFeeOwedB"`
	FeeGrowthGlobalA     binary.Uint128     `json:"feeGrowthGlobalA"`
	FeeGrowthGlobalB     binary.Uint128     `json:"feeGrowthGlobalB"`
	OrdersTotalAmountA   uint64             `json:"ordersTotalAmountA"`
	OrdersTotalAmountB   uint64             `json:"ordersTotalAmountB"`
	OrdersFilledAmountA  uint64             `json:"ordersFilledAmountA"`
	OrdersFilledAmountB  uint64             `json:"ordersFilledAmountB"`
	OlpFeeOwedA          uint64             `json:"olpFeeOwedA"`
	OlpFeeOwedB          uint64             `json:"olpFeeOwedB"`
	Reserved             [140]uint8         `json:"reserved"`
}

func (obj FusionPool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `TokenMintA`:
	err = encoder.Encode(obj.TokenMintA)
	if err != nil {
		return errors.NewField("TokenMintA", err)
	}
	// Serialize `TokenMintB`:
	err = encoder.Encode(obj.TokenMintB)
	if err != nil {
		return errors.NewField("TokenMintB", err)
	}
	// Serialize `TokenVaultA`:
	err = encoder.Encode(obj.TokenVaultA)
	if err != nil {
		return errors.NewField("TokenVaultA", err)
	}
	// Serialize `TokenVaultB`:
	err = encoder.Encode(obj.TokenVaultB)
	if err != nil {
		return errors.NewField("TokenVaultB", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `TickSpacingSeed`:
	err = encoder.Encode(obj.TickSpacingSeed)
	if err != nil {
		return errors.NewField("TickSpacingSeed", err)
	}
	// Serialize `FeeRate`:
	err = encoder.Encode(obj.FeeRate)
	if err != nil {
		return errors.NewField("FeeRate", err)
	}
	// Serialize `ProtocolFeeRate`:
	err = encoder.Encode(obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Serialize `ClpRewardRate`:
	err = encoder.Encode(obj.ClpRewardRate)
	if err != nil {
		return errors.NewField("ClpRewardRate", err)
	}
	// Serialize `OrderProtocolFeeRate`:
	err = encoder.Encode(obj.OrderProtocolFeeRate)
	if err != nil {
		return errors.NewField("OrderProtocolFeeRate", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `SqrtPrice`:
	err = encoder.Encode(obj.SqrtPrice)
	if err != nil {
		return errors.NewField("SqrtPrice", err)
	}
	// Serialize `TickCurrentIndex`:
	err = encoder.Encode(obj.TickCurrentIndex)
	if err != nil {
		return errors.NewField("TickCurrentIndex", err)
	}
	// Serialize `ProtocolFeeOwedA`:
	err = encoder.Encode(obj.ProtocolFeeOwedA)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedA", err)
	}
	// Serialize `ProtocolFeeOwedB`:
	err = encoder.Encode(obj.ProtocolFeeOwedB)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedB", err)
	}
	// Serialize `FeeGrowthGlobalA`:
	err = encoder.Encode(obj.FeeGrowthGlobalA)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalA", err)
	}
	// Serialize `FeeGrowthGlobalB`:
	err = encoder.Encode(obj.FeeGrowthGlobalB)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalB", err)
	}
	// Serialize `OrdersTotalAmountA`:
	err = encoder.Encode(obj.OrdersTotalAmountA)
	if err != nil {
		return errors.NewField("OrdersTotalAmountA", err)
	}
	// Serialize `OrdersTotalAmountB`:
	err = encoder.Encode(obj.OrdersTotalAmountB)
	if err != nil {
		return errors.NewField("OrdersTotalAmountB", err)
	}
	// Serialize `OrdersFilledAmountA`:
	err = encoder.Encode(obj.OrdersFilledAmountA)
	if err != nil {
		return errors.NewField("OrdersFilledAmountA", err)
	}
	// Serialize `OrdersFilledAmountB`:
	err = encoder.Encode(obj.OrdersFilledAmountB)
	if err != nil {
		return errors.NewField("OrdersFilledAmountB", err)
	}
	// Serialize `OlpFeeOwedA`:
	err = encoder.Encode(obj.OlpFeeOwedA)
	if err != nil {
		return errors.NewField("OlpFeeOwedA", err)
	}
	// Serialize `OlpFeeOwedB`:
	err = encoder.Encode(obj.OlpFeeOwedB)
	if err != nil {
		return errors.NewField("OlpFeeOwedB", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj FusionPool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FusionPool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FusionPool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `TokenMintA`:
	err = decoder.Decode(&obj.TokenMintA)
	if err != nil {
		return errors.NewField("TokenMintA", err)
	}
	// Deserialize `TokenMintB`:
	err = decoder.Decode(&obj.TokenMintB)
	if err != nil {
		return errors.NewField("TokenMintB", err)
	}
	// Deserialize `TokenVaultA`:
	err = decoder.Decode(&obj.TokenVaultA)
	if err != nil {
		return errors.NewField("TokenVaultA", err)
	}
	// Deserialize `TokenVaultB`:
	err = decoder.Decode(&obj.TokenVaultB)
	if err != nil {
		return errors.NewField("TokenVaultB", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `TickSpacingSeed`:
	err = decoder.Decode(&obj.TickSpacingSeed)
	if err != nil {
		return errors.NewField("TickSpacingSeed", err)
	}
	// Deserialize `FeeRate`:
	err = decoder.Decode(&obj.FeeRate)
	if err != nil {
		return errors.NewField("FeeRate", err)
	}
	// Deserialize `ProtocolFeeRate`:
	err = decoder.Decode(&obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Deserialize `ClpRewardRate`:
	err = decoder.Decode(&obj.ClpRewardRate)
	if err != nil {
		return errors.NewField("ClpRewardRate", err)
	}
	// Deserialize `OrderProtocolFeeRate`:
	err = decoder.Decode(&obj.OrderProtocolFeeRate)
	if err != nil {
		return errors.NewField("OrderProtocolFeeRate", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `SqrtPrice`:
	err = decoder.Decode(&obj.SqrtPrice)
	if err != nil {
		return errors.NewField("SqrtPrice", err)
	}
	// Deserialize `TickCurrentIndex`:
	err = decoder.Decode(&obj.TickCurrentIndex)
	if err != nil {
		return errors.NewField("TickCurrentIndex", err)
	}
	// Deserialize `ProtocolFeeOwedA`:
	err = decoder.Decode(&obj.ProtocolFeeOwedA)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedA", err)
	}
	// Deserialize `ProtocolFeeOwedB`:
	err = decoder.Decode(&obj.ProtocolFeeOwedB)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedB", err)
	}
	// Deserialize `FeeGrowthGlobalA`:
	err = decoder.Decode(&obj.FeeGrowthGlobalA)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalA", err)
	}
	// Deserialize `FeeGrowthGlobalB`:
	err = decoder.Decode(&obj.FeeGrowthGlobalB)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalB", err)
	}
	// Deserialize `OrdersTotalAmountA`:
	err = decoder.Decode(&obj.OrdersTotalAmountA)
	if err != nil {
		return errors.NewField("OrdersTotalAmountA", err)
	}
	// Deserialize `OrdersTotalAmountB`:
	err = decoder.Decode(&obj.OrdersTotalAmountB)
	if err != nil {
		return errors.NewField("OrdersTotalAmountB", err)
	}
	// Deserialize `OrdersFilledAmountA`:
	err = decoder.Decode(&obj.OrdersFilledAmountA)
	if err != nil {
		return errors.NewField("OrdersFilledAmountA", err)
	}
	// Deserialize `OrdersFilledAmountB`:
	err = decoder.Decode(&obj.OrdersFilledAmountB)
	if err != nil {
		return errors.NewField("OrdersFilledAmountB", err)
	}
	// Deserialize `OlpFeeOwedA`:
	err = decoder.Decode(&obj.OlpFeeOwedA)
	if err != nil {
		return errors.NewField("OlpFeeOwedA", err)
	}
	// Deserialize `OlpFeeOwedB`:
	err = decoder.Decode(&obj.OlpFeeOwedB)
	if err != nil {
		return errors.NewField("OlpFeeOwedB", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *FusionPool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FusionPool: %w", err)
	}
	return nil
}

func UnmarshalFusionPool(buf []byte) (*FusionPool, error) {
	obj := new(FusionPool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type LendingPosition struct {
	// Struct version
	Version uint16 `json:"version"`

	// Bump seed for the lending position account
	Bump [1]uint8 `json:"bump"`

	// Authority address used for managing the position
	Authority solanago.PublicKey `json:"authority"`

	// Mint address of the token in the vault
	PoolMint solanago.PublicKey `json:"poolMint"`

	// The amount of funds provided by user. Used to compute earned amount.
	DepositedFunds uint64 `json:"depositedFunds"`

	// The amount of funds provided by user to the vault as shares
	DepositedShares uint64 `json:"depositedShares"`

	// Reserved
	Reserved [64]uint8 `json:"reserved"`
}

func (obj LendingPosition) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `PoolMint`:
	err = encoder.Encode(obj.PoolMint)
	if err != nil {
		return errors.NewField("PoolMint", err)
	}
	// Serialize `DepositedFunds`:
	err = encoder.Encode(obj.DepositedFunds)
	if err != nil {
		return errors.NewField("DepositedFunds", err)
	}
	// Serialize `DepositedShares`:
	err = encoder.Encode(obj.DepositedShares)
	if err != nil {
		return errors.NewField("DepositedShares", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj LendingPosition) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LendingPosition: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LendingPosition) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `PoolMint`:
	err = decoder.Decode(&obj.PoolMint)
	if err != nil {
		return errors.NewField("PoolMint", err)
	}
	// Deserialize `DepositedFunds`:
	err = decoder.Decode(&obj.DepositedFunds)
	if err != nil {
		return errors.NewField("DepositedFunds", err)
	}
	// Deserialize `DepositedShares`:
	err = decoder.Decode(&obj.DepositedShares)
	if err != nil {
		return errors.NewField("DepositedShares", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *LendingPosition) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LendingPosition: %w", err)
	}
	return nil
}

func UnmarshalLendingPosition(buf []byte) (*LendingPosition, error) {
	obj := new(LendingPosition)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Market struct {
	// Struct version
	Version uint16 `json:"version"`

	// Bump seed for the market account
	Bump [1]uint8 `json:"bump"`

	// Market maker: Orca, Fusion, etc...
	MarketMaker MarketMaker `json:"marketMaker"`

	// Liquidity pool address
	Pool solanago.PublicKey `json:"pool"`

	// Address Lookup Table address for this market
	AddressLookupTable solanago.PublicKey `json:"addressLookupTable"`

	// Maximum allowed leverage for this market
	MaxLeverage uint32 `json:"maxLeverage"`

	// Protocol fee represented as hundredths of a basis point. (Value of 100 is equal to 0.01%)
	ProtocolFee uint16 `json:"protocolFee"`

	// Protocol fee on collateral (funds provided by a user) represented as hundredths of a basis point. (Value of 100 is equal to 0.01%)
	ProtocolFeeOnCollateral uint16 `json:"protocolFeeOnCollateral"`

	// Liquidation fee represented as hundredths of a basis point. (Value of 100 is equal to 0.01%)
	LiquidationFee uint32 `json:"liquidationFee"`

	// Liquidation threshold represented as hundredths of a basis point. The position is treated as unhealthy if debt > balance * (liquidation_threshold / HUNDRED_PERCENT).
	LiquidationThreshold uint32 `json:"liquidationThreshold"`

	// Limit order execution fee represented as hundredths of a basis point. (Value of 100 is equal to 0.01%)
	LimitOrderExecutionFee uint32 `json:"limitOrderExecutionFee"`

	// Oracle price deviation threshold represented as hundredths of a basis point. If it's set to zero, the default value from the global config is used.
	OraclePriceDeviationThreshold uint32 `json:"oraclePriceDeviationThreshold"`

	// True if the market is disabled (no more position can be opened).
	Disabled bool `json:"disabled"`

	// Total borrowed shares of token A.
	BorrowedSharesA uint64 `json:"borrowedSharesA"`

	// Total borrowed shares of token B.
	BorrowedSharesB uint64 `json:"borrowedSharesB"`

	// Total borrow limit for this market in token A.
	BorrowLimitA uint64 `json:"borrowLimitA"`

	// Total borrow limit for this market in token B.
	BorrowLimitB uint64 `json:"borrowLimitB"`

	// Maximum allowed swap slippage represented as hundredths of a basis point. If it's set to zero, the default value from the global config is used.
	MaxSwapSlippage uint32 `json:"maxSwapSlippage"`

	// The protocol fee taken from yield when a position is re-balanced.
	RebalanceProtocolFee uint32 `json:"rebalanceProtocolFee"`

	// Reserved
	Reserved [207]uint8 `json:"reserved"`
}

func (obj Market) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `MarketMaker`:
	err = encoder.Encode(obj.MarketMaker)
	if err != nil {
		return errors.NewField("MarketMaker", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `AddressLookupTable`:
	err = encoder.Encode(obj.AddressLookupTable)
	if err != nil {
		return errors.NewField("AddressLookupTable", err)
	}
	// Serialize `MaxLeverage`:
	err = encoder.Encode(obj.MaxLeverage)
	if err != nil {
		return errors.NewField("MaxLeverage", err)
	}
	// Serialize `ProtocolFee`:
	err = encoder.Encode(obj.ProtocolFee)
	if err != nil {
		return errors.NewField("ProtocolFee", err)
	}
	// Serialize `ProtocolFeeOnCollateral`:
	err = encoder.Encode(obj.ProtocolFeeOnCollateral)
	if err != nil {
		return errors.NewField("ProtocolFeeOnCollateral", err)
	}
	// Serialize `LiquidationFee`:
	err = encoder.Encode(obj.LiquidationFee)
	if err != nil {
		return errors.NewField("LiquidationFee", err)
	}
	// Serialize `LiquidationThreshold`:
	err = encoder.Encode(obj.LiquidationThreshold)
	if err != nil {
		return errors.NewField("LiquidationThreshold", err)
	}
	// Serialize `LimitOrderExecutionFee`:
	err = encoder.Encode(obj.LimitOrderExecutionFee)
	if err != nil {
		return errors.NewField("LimitOrderExecutionFee", err)
	}
	// Serialize `OraclePriceDeviationThreshold`:
	err = encoder.Encode(obj.OraclePriceDeviationThreshold)
	if err != nil {
		return errors.NewField("OraclePriceDeviationThreshold", err)
	}
	// Serialize `Disabled`:
	err = encoder.Encode(obj.Disabled)
	if err != nil {
		return errors.NewField("Disabled", err)
	}
	// Serialize `BorrowedSharesA`:
	err = encoder.Encode(obj.BorrowedSharesA)
	if err != nil {
		return errors.NewField("BorrowedSharesA", err)
	}
	// Serialize `BorrowedSharesB`:
	err = encoder.Encode(obj.BorrowedSharesB)
	if err != nil {
		return errors.NewField("BorrowedSharesB", err)
	}
	// Serialize `BorrowLimitA`:
	err = encoder.Encode(obj.BorrowLimitA)
	if err != nil {
		return errors.NewField("BorrowLimitA", err)
	}
	// Serialize `BorrowLimitB`:
	err = encoder.Encode(obj.BorrowLimitB)
	if err != nil {
		return errors.NewField("BorrowLimitB", err)
	}
	// Serialize `MaxSwapSlippage`:
	err = encoder.Encode(obj.MaxSwapSlippage)
	if err != nil {
		return errors.NewField("MaxSwapSlippage", err)
	}
	// Serialize `RebalanceProtocolFee`:
	err = encoder.Encode(obj.RebalanceProtocolFee)
	if err != nil {
		return errors.NewField("RebalanceProtocolFee", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj Market) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Market: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Market) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `MarketMaker`:
	err = decoder.Decode(&obj.MarketMaker)
	if err != nil {
		return errors.NewField("MarketMaker", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `AddressLookupTable`:
	err = decoder.Decode(&obj.AddressLookupTable)
	if err != nil {
		return errors.NewField("AddressLookupTable", err)
	}
	// Deserialize `MaxLeverage`:
	err = decoder.Decode(&obj.MaxLeverage)
	if err != nil {
		return errors.NewField("MaxLeverage", err)
	}
	// Deserialize `ProtocolFee`:
	err = decoder.Decode(&obj.ProtocolFee)
	if err != nil {
		return errors.NewField("ProtocolFee", err)
	}
	// Deserialize `ProtocolFeeOnCollateral`:
	err = decoder.Decode(&obj.ProtocolFeeOnCollateral)
	if err != nil {
		return errors.NewField("ProtocolFeeOnCollateral", err)
	}
	// Deserialize `LiquidationFee`:
	err = decoder.Decode(&obj.LiquidationFee)
	if err != nil {
		return errors.NewField("LiquidationFee", err)
	}
	// Deserialize `LiquidationThreshold`:
	err = decoder.Decode(&obj.LiquidationThreshold)
	if err != nil {
		return errors.NewField("LiquidationThreshold", err)
	}
	// Deserialize `LimitOrderExecutionFee`:
	err = decoder.Decode(&obj.LimitOrderExecutionFee)
	if err != nil {
		return errors.NewField("LimitOrderExecutionFee", err)
	}
	// Deserialize `OraclePriceDeviationThreshold`:
	err = decoder.Decode(&obj.OraclePriceDeviationThreshold)
	if err != nil {
		return errors.NewField("OraclePriceDeviationThreshold", err)
	}
	// Deserialize `Disabled`:
	err = decoder.Decode(&obj.Disabled)
	if err != nil {
		return errors.NewField("Disabled", err)
	}
	// Deserialize `BorrowedSharesA`:
	err = decoder.Decode(&obj.BorrowedSharesA)
	if err != nil {
		return errors.NewField("BorrowedSharesA", err)
	}
	// Deserialize `BorrowedSharesB`:
	err = decoder.Decode(&obj.BorrowedSharesB)
	if err != nil {
		return errors.NewField("BorrowedSharesB", err)
	}
	// Deserialize `BorrowLimitA`:
	err = decoder.Decode(&obj.BorrowLimitA)
	if err != nil {
		return errors.NewField("BorrowLimitA", err)
	}
	// Deserialize `BorrowLimitB`:
	err = decoder.Decode(&obj.BorrowLimitB)
	if err != nil {
		return errors.NewField("BorrowLimitB", err)
	}
	// Deserialize `MaxSwapSlippage`:
	err = decoder.Decode(&obj.MaxSwapSlippage)
	if err != nil {
		return errors.NewField("MaxSwapSlippage", err)
	}
	// Deserialize `RebalanceProtocolFee`:
	err = decoder.Decode(&obj.RebalanceProtocolFee)
	if err != nil {
		return errors.NewField("RebalanceProtocolFee", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *Market) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Market: %w", err)
	}
	return nil
}

func UnmarshalMarket(buf []byte) (*Market, error) {
	obj := new(Market)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type MarketMaker binary.BorshEnum

const (
	MarketMaker_Orca MarketMaker = iota
	MarketMaker_Fusion
)

func (value MarketMaker) String() string {
	switch value {
	case MarketMaker_Orca:
		return "Orca"
	case MarketMaker_Fusion:
		return "Fusion"
	default:
		return ""
	}
}

type RemainingAccountsInfo struct {
	Slices []RemainingAccountsSlice `json:"slices"`
}

func (obj RemainingAccountsInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Slices`:
	err = encoder.Encode(obj.Slices)
	if err != nil {
		return errors.NewField("Slices", err)
	}
	return nil
}

func (obj RemainingAccountsInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding RemainingAccountsInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *RemainingAccountsInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Slices`:
	err = decoder.Decode(&obj.Slices)
	if err != nil {
		return errors.NewField("Slices", err)
	}
	return nil
}

func (obj *RemainingAccountsInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling RemainingAccountsInfo: %w", err)
	}
	return nil
}

func UnmarshalRemainingAccountsInfo(buf []byte) (*RemainingAccountsInfo, error) {
	obj := new(RemainingAccountsInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type RemainingAccountsSlice struct {
	AccountsType AccountsType `json:"accountsType"`
	Length       uint8        `json:"length"`
}

func (obj RemainingAccountsSlice) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `AccountsType`:
	err = encoder.Encode(obj.AccountsType)
	if err != nil {
		return errors.NewField("AccountsType", err)
	}
	// Serialize `Length`:
	err = encoder.Encode(obj.Length)
	if err != nil {
		return errors.NewField("Length", err)
	}
	return nil
}

func (obj RemainingAccountsSlice) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding RemainingAccountsSlice: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *RemainingAccountsSlice) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `AccountsType`:
	err = decoder.Decode(&obj.AccountsType)
	if err != nil {
		return errors.NewField("AccountsType", err)
	}
	// Deserialize `Length`:
	err = decoder.Decode(&obj.Length)
	if err != nil {
		return errors.NewField("Length", err)
	}
	return nil
}

func (obj *RemainingAccountsSlice) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling RemainingAccountsSlice: %w", err)
	}
	return nil
}

func UnmarshalRemainingAccountsSlice(buf []byte) (*RemainingAccountsSlice, error) {
	obj := new(RemainingAccountsSlice)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TunaConfig struct {
	// Struct version.
	Version uint16 `json:"version"`

	// Bump seed for the vaults config account.
	Bump uint8 `json:"bump"`

	// Current update authority address for both the TunaConfig and the Vault PDAs themselves - can be updated.
	AdminAuthority solanago.PublicKey `json:"adminAuthority"`

	// Fee recipient address.
	FeeRecipient solanago.PublicKey `json:"feeRecipient"`

	// Owner of the program. Can change ownership and set the admin of the program.
	OwnerAuthority solanago.PublicKey `json:"ownerAuthority"`

	// Maximum allowed swap slippage percentage.
	MaxSwapSlippage uint32 `json:"maxSwapSlippage"`

	// Maximum allowed percentage of leftovers.
	MaxPercentageOfLeftovers uint32 `json:"maxPercentageOfLeftovers"`

	// Suspends lending deposits in case of emergency.
	SuspendLendingDeposits bool `json:"suspendLendingDeposits"`

	// Suspends lending withdrawals in case of emergency.
	SuspendLendingWithdrawals bool `json:"suspendLendingWithdrawals"`

	// Suspends adding liquidity to positions in case of emergency.
	SuspendAddLiquidity bool `json:"suspendAddLiquidity"`

	// Suspends removing liquidity, claiming fees and closing positions in case of emergency.
	SuspendRemoveLiquidity bool `json:"suspendRemoveLiquidity"`

	// Liquidation bot wallet.
	LiquidatorAuthority solanago.PublicKey `json:"liquidatorAuthority"`

	// Maximum allowed oracle price deviation in percent.
	OraclePriceDeviationThreshold uint32 `json:"oraclePriceDeviationThreshold"`

	// Reserved
	Reserved [176]uint8 `json:"reserved"`
}

func (obj TunaConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `AdminAuthority`:
	err = encoder.Encode(obj.AdminAuthority)
	if err != nil {
		return errors.NewField("AdminAuthority", err)
	}
	// Serialize `FeeRecipient`:
	err = encoder.Encode(obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Serialize `OwnerAuthority`:
	err = encoder.Encode(obj.OwnerAuthority)
	if err != nil {
		return errors.NewField("OwnerAuthority", err)
	}
	// Serialize `MaxSwapSlippage`:
	err = encoder.Encode(obj.MaxSwapSlippage)
	if err != nil {
		return errors.NewField("MaxSwapSlippage", err)
	}
	// Serialize `MaxPercentageOfLeftovers`:
	err = encoder.Encode(obj.MaxPercentageOfLeftovers)
	if err != nil {
		return errors.NewField("MaxPercentageOfLeftovers", err)
	}
	// Serialize `SuspendLendingDeposits`:
	err = encoder.Encode(obj.SuspendLendingDeposits)
	if err != nil {
		return errors.NewField("SuspendLendingDeposits", err)
	}
	// Serialize `SuspendLendingWithdrawals`:
	err = encoder.Encode(obj.SuspendLendingWithdrawals)
	if err != nil {
		return errors.NewField("SuspendLendingWithdrawals", err)
	}
	// Serialize `SuspendAddLiquidity`:
	err = encoder.Encode(obj.SuspendAddLiquidity)
	if err != nil {
		return errors.NewField("SuspendAddLiquidity", err)
	}
	// Serialize `SuspendRemoveLiquidity`:
	err = encoder.Encode(obj.SuspendRemoveLiquidity)
	if err != nil {
		return errors.NewField("SuspendRemoveLiquidity", err)
	}
	// Serialize `LiquidatorAuthority`:
	err = encoder.Encode(obj.LiquidatorAuthority)
	if err != nil {
		return errors.NewField("LiquidatorAuthority", err)
	}
	// Serialize `OraclePriceDeviationThreshold`:
	err = encoder.Encode(obj.OraclePriceDeviationThreshold)
	if err != nil {
		return errors.NewField("OraclePriceDeviationThreshold", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj TunaConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TunaConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TunaConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `AdminAuthority`:
	err = decoder.Decode(&obj.AdminAuthority)
	if err != nil {
		return errors.NewField("AdminAuthority", err)
	}
	// Deserialize `FeeRecipient`:
	err = decoder.Decode(&obj.FeeRecipient)
	if err != nil {
		return errors.NewField("FeeRecipient", err)
	}
	// Deserialize `OwnerAuthority`:
	err = decoder.Decode(&obj.OwnerAuthority)
	if err != nil {
		return errors.NewField("OwnerAuthority", err)
	}
	// Deserialize `MaxSwapSlippage`:
	err = decoder.Decode(&obj.MaxSwapSlippage)
	if err != nil {
		return errors.NewField("MaxSwapSlippage", err)
	}
	// Deserialize `MaxPercentageOfLeftovers`:
	err = decoder.Decode(&obj.MaxPercentageOfLeftovers)
	if err != nil {
		return errors.NewField("MaxPercentageOfLeftovers", err)
	}
	// Deserialize `SuspendLendingDeposits`:
	err = decoder.Decode(&obj.SuspendLendingDeposits)
	if err != nil {
		return errors.NewField("SuspendLendingDeposits", err)
	}
	// Deserialize `SuspendLendingWithdrawals`:
	err = decoder.Decode(&obj.SuspendLendingWithdrawals)
	if err != nil {
		return errors.NewField("SuspendLendingWithdrawals", err)
	}
	// Deserialize `SuspendAddLiquidity`:
	err = decoder.Decode(&obj.SuspendAddLiquidity)
	if err != nil {
		return errors.NewField("SuspendAddLiquidity", err)
	}
	// Deserialize `SuspendRemoveLiquidity`:
	err = decoder.Decode(&obj.SuspendRemoveLiquidity)
	if err != nil {
		return errors.NewField("SuspendRemoveLiquidity", err)
	}
	// Deserialize `LiquidatorAuthority`:
	err = decoder.Decode(&obj.LiquidatorAuthority)
	if err != nil {
		return errors.NewField("LiquidatorAuthority", err)
	}
	// Deserialize `OraclePriceDeviationThreshold`:
	err = decoder.Decode(&obj.OraclePriceDeviationThreshold)
	if err != nil {
		return errors.NewField("OraclePriceDeviationThreshold", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *TunaConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TunaConfig: %w", err)
	}
	return nil
}

func UnmarshalTunaConfig(buf []byte) (*TunaConfig, error) {
	obj := new(TunaConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TunaPosition struct {
	// Struct version
	Version uint16 `json:"version"`

	// Bump seed for the tuna position account
	Bump [1]uint8 `json:"bump"`

	// The authority address used for managing the position
	Authority solanago.PublicKey `json:"authority"`

	// Liquidity pool address this position belongs to
	Pool solanago.PublicKey `json:"pool"`

	// The mint address for token A
	MintA solanago.PublicKey `json:"mintA"`

	// The mint address for token B
	MintB solanago.PublicKey `json:"mintB"`

	// The mint address for the position token (minted and used in Orca/Fusion)
	PositionMint solanago.PublicKey `json:"positionMint"`

	// Total minted liquidity
	Liquidity binary.Uint128 `json:"liquidity"`

	// Position lower tick
	TickLowerIndex int32 `json:"tickLowerIndex"`

	// Position upper tick
	TickUpperIndex int32 `json:"tickUpperIndex"`

	// The amount of shares borrowed by user from vault A.
	LoanSharesA uint64 `json:"loanSharesA"`

	// The amount of shares borrowed by user from vault B.
	LoanSharesB uint64 `json:"loanSharesB"`

	// The amount of funds borrowed by user from vault A. Doesn't include accrued interest.
	LoanFundsA uint64 `json:"loanFundsA"`

	// The amount of funds borrowed by user from vault B. Doesn't include accrued interest.
	LoanFundsB uint64 `json:"loanFundsB"`

	// The leftovers are funds that couldn't be added to a pool as liquidity. They remain in the position token account.
	LeftoversA uint64 `json:"leftoversA"`

	// The leftovers are funds that couldn't be added to a pool as liquidity. They remain in the position token account.
	LeftoversB uint64 `json:"leftoversB"`

	// Position entry tick index.
	TickEntryIndex int32 `json:"tickEntryIndex"`

	// Position stop loss tick index.
	TickStopLossIndex int32 `json:"tickStopLossIndex"`

	// Position stop loss tick index.
	TickTakeProfitIndex int32 `json:"tickTakeProfitIndex"`

	// Position state: normal, liquidated, closed by limit order
	State TunaPositionState `json:"state"`

	// OBSOLETE: Which token to swap collateral to when a limit order is executed. Used for position ver 4 or older.
	// bits 0..1: Stop loss swap. 0 - no swap, 1 - swap to token A, 2 - swap to token B
	// bits 2..3: Take profit swap. 0 - no swap, 1 - swap to token A, 2 - swap to token B
	SwapToTokenOnLimitOrder uint8 `json:"swapToTokenOnLimitOrder"`

	// Yield amount in token A that has already been collected and compounded into the position.
	CompoundedYieldA uint64 `json:"compoundedYieldA"`

	// Yield amount in token B that has already been collected and compounded into the position.
	CompoundedYieldB uint64 `json:"compoundedYieldB"`

	// Position options.
	// Bits 0..1: Stop loss swap. 0 - no swap, 1 - swap to token A, 2 - swap to token B
	// Bits 2..3: Take profit swap. 0 - no swap, 1 - swap to token A, 2 - swap to token B
	// Bits 4..5: Yield auto compounding. 0 - don't compound, 1 - compound yield, 2 - compound yield with leverage
	Flags uint32 `json:"flags"`

	// Market maker (Orca, Fusion)
	MarketMaker MarketMaker `json:"marketMaker"`

	// The position might be re-balanced if the current tick is lower than tick_lower_index or
	// higher than tick_higher_index by a threshold value.
	RebalanceThresholdTicks uint32 `json:"rebalanceThresholdTicks"`

	// Reserved
	Reserved [57]uint8 `json:"reserved"`
}

func (obj TunaPosition) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `MintA`:
	err = encoder.Encode(obj.MintA)
	if err != nil {
		return errors.NewField("MintA", err)
	}
	// Serialize `MintB`:
	err = encoder.Encode(obj.MintB)
	if err != nil {
		return errors.NewField("MintB", err)
	}
	// Serialize `PositionMint`:
	err = encoder.Encode(obj.PositionMint)
	if err != nil {
		return errors.NewField("PositionMint", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `TickLowerIndex`:
	err = encoder.Encode(obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Serialize `TickUpperIndex`:
	err = encoder.Encode(obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Serialize `LoanSharesA`:
	err = encoder.Encode(obj.LoanSharesA)
	if err != nil {
		return errors.NewField("LoanSharesA", err)
	}
	// Serialize `LoanSharesB`:
	err = encoder.Encode(obj.LoanSharesB)
	if err != nil {
		return errors.NewField("LoanSharesB", err)
	}
	// Serialize `LoanFundsA`:
	err = encoder.Encode(obj.LoanFundsA)
	if err != nil {
		return errors.NewField("LoanFundsA", err)
	}
	// Serialize `LoanFundsB`:
	err = encoder.Encode(obj.LoanFundsB)
	if err != nil {
		return errors.NewField("LoanFundsB", err)
	}
	// Serialize `LeftoversA`:
	err = encoder.Encode(obj.LeftoversA)
	if err != nil {
		return errors.NewField("LeftoversA", err)
	}
	// Serialize `LeftoversB`:
	err = encoder.Encode(obj.LeftoversB)
	if err != nil {
		return errors.NewField("LeftoversB", err)
	}
	// Serialize `TickEntryIndex`:
	err = encoder.Encode(obj.TickEntryIndex)
	if err != nil {
		return errors.NewField("TickEntryIndex", err)
	}
	// Serialize `TickStopLossIndex`:
	err = encoder.Encode(obj.TickStopLossIndex)
	if err != nil {
		return errors.NewField("TickStopLossIndex", err)
	}
	// Serialize `TickTakeProfitIndex`:
	err = encoder.Encode(obj.TickTakeProfitIndex)
	if err != nil {
		return errors.NewField("TickTakeProfitIndex", err)
	}
	// Serialize `State`:
	err = encoder.Encode(obj.State)
	if err != nil {
		return errors.NewField("State", err)
	}
	// Serialize `SwapToTokenOnLimitOrder`:
	err = encoder.Encode(obj.SwapToTokenOnLimitOrder)
	if err != nil {
		return errors.NewField("SwapToTokenOnLimitOrder", err)
	}
	// Serialize `CompoundedYieldA`:
	err = encoder.Encode(obj.CompoundedYieldA)
	if err != nil {
		return errors.NewField("CompoundedYieldA", err)
	}
	// Serialize `CompoundedYieldB`:
	err = encoder.Encode(obj.CompoundedYieldB)
	if err != nil {
		return errors.NewField("CompoundedYieldB", err)
	}
	// Serialize `Flags`:
	err = encoder.Encode(obj.Flags)
	if err != nil {
		return errors.NewField("Flags", err)
	}
	// Serialize `MarketMaker`:
	err = encoder.Encode(obj.MarketMaker)
	if err != nil {
		return errors.NewField("MarketMaker", err)
	}
	// Serialize `RebalanceThresholdTicks`:
	err = encoder.Encode(obj.RebalanceThresholdTicks)
	if err != nil {
		return errors.NewField("RebalanceThresholdTicks", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj TunaPosition) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TunaPosition: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TunaPosition) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `MintA`:
	err = decoder.Decode(&obj.MintA)
	if err != nil {
		return errors.NewField("MintA", err)
	}
	// Deserialize `MintB`:
	err = decoder.Decode(&obj.MintB)
	if err != nil {
		return errors.NewField("MintB", err)
	}
	// Deserialize `PositionMint`:
	err = decoder.Decode(&obj.PositionMint)
	if err != nil {
		return errors.NewField("PositionMint", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `TickLowerIndex`:
	err = decoder.Decode(&obj.TickLowerIndex)
	if err != nil {
		return errors.NewField("TickLowerIndex", err)
	}
	// Deserialize `TickUpperIndex`:
	err = decoder.Decode(&obj.TickUpperIndex)
	if err != nil {
		return errors.NewField("TickUpperIndex", err)
	}
	// Deserialize `LoanSharesA`:
	err = decoder.Decode(&obj.LoanSharesA)
	if err != nil {
		return errors.NewField("LoanSharesA", err)
	}
	// Deserialize `LoanSharesB`:
	err = decoder.Decode(&obj.LoanSharesB)
	if err != nil {
		return errors.NewField("LoanSharesB", err)
	}
	// Deserialize `LoanFundsA`:
	err = decoder.Decode(&obj.LoanFundsA)
	if err != nil {
		return errors.NewField("LoanFundsA", err)
	}
	// Deserialize `LoanFundsB`:
	err = decoder.Decode(&obj.LoanFundsB)
	if err != nil {
		return errors.NewField("LoanFundsB", err)
	}
	// Deserialize `LeftoversA`:
	err = decoder.Decode(&obj.LeftoversA)
	if err != nil {
		return errors.NewField("LeftoversA", err)
	}
	// Deserialize `LeftoversB`:
	err = decoder.Decode(&obj.LeftoversB)
	if err != nil {
		return errors.NewField("LeftoversB", err)
	}
	// Deserialize `TickEntryIndex`:
	err = decoder.Decode(&obj.TickEntryIndex)
	if err != nil {
		return errors.NewField("TickEntryIndex", err)
	}
	// Deserialize `TickStopLossIndex`:
	err = decoder.Decode(&obj.TickStopLossIndex)
	if err != nil {
		return errors.NewField("TickStopLossIndex", err)
	}
	// Deserialize `TickTakeProfitIndex`:
	err = decoder.Decode(&obj.TickTakeProfitIndex)
	if err != nil {
		return errors.NewField("TickTakeProfitIndex", err)
	}
	// Deserialize `State`:
	err = decoder.Decode(&obj.State)
	if err != nil {
		return errors.NewField("State", err)
	}
	// Deserialize `SwapToTokenOnLimitOrder`:
	err = decoder.Decode(&obj.SwapToTokenOnLimitOrder)
	if err != nil {
		return errors.NewField("SwapToTokenOnLimitOrder", err)
	}
	// Deserialize `CompoundedYieldA`:
	err = decoder.Decode(&obj.CompoundedYieldA)
	if err != nil {
		return errors.NewField("CompoundedYieldA", err)
	}
	// Deserialize `CompoundedYieldB`:
	err = decoder.Decode(&obj.CompoundedYieldB)
	if err != nil {
		return errors.NewField("CompoundedYieldB", err)
	}
	// Deserialize `Flags`:
	err = decoder.Decode(&obj.Flags)
	if err != nil {
		return errors.NewField("Flags", err)
	}
	// Deserialize `MarketMaker`:
	err = decoder.Decode(&obj.MarketMaker)
	if err != nil {
		return errors.NewField("MarketMaker", err)
	}
	// Deserialize `RebalanceThresholdTicks`:
	err = decoder.Decode(&obj.RebalanceThresholdTicks)
	if err != nil {
		return errors.NewField("RebalanceThresholdTicks", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *TunaPosition) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TunaPosition: %w", err)
	}
	return nil
}

func UnmarshalTunaPosition(buf []byte) (*TunaPosition, error) {
	obj := new(TunaPosition)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TunaPositionState binary.BorshEnum

const (
	TunaPositionState_Normal TunaPositionState = iota
	TunaPositionState_Liquidated
	TunaPositionState_ClosedByLimitOrder
)

func (value TunaPositionState) String() string {
	switch value {
	case TunaPositionState_Normal:
		return "Normal"
	case TunaPositionState_Liquidated:
		return "Liquidated"
	case TunaPositionState_ClosedByLimitOrder:
		return "ClosedByLimitOrder"
	default:
		return ""
	}
}

type Vault struct {
	// Struct version
	Version uint16 `json:"version"`

	// Bump seed for the vault account
	Bump [1]uint8 `json:"bump"`

	// The mint of the token that this vault holds
	Mint solanago.PublicKey `json:"mint"`

	// The amount of funds deposited in the vault - takes into account accrued interest
	DepositedFunds uint64 `json:"depositedFunds"`

	// The amount of shares deposited in the vault
	DepositedShares uint64 `json:"depositedShares"`

	// The amount of funds borrowed from the vault - takes into account accrued interest
	BorrowedFunds uint64 `json:"borrowedFunds"`

	// The amount of shares borrowed from the vault
	BorrowedShares uint64 `json:"borrowedShares"`

	// Bad dept may appear on a position liquidation if not enough funds to repay the debt to a lending pool.
	UnpaidDebtShares uint64 `json:"unpaidDebtShares"`

	// The interest rate of the vault per seconds. (1<<60) / 31536000 = 1152921504606846976 / 31536000 = 100% annually.
	InterestRate uint64 `json:"interestRate"`

	// The last time the vault was updated.
	LastUpdateTimestamp uint64 `json:"lastUpdateTimestamp"`

	// The maximum allowed supply for this pool. The default value 0 is unlimited supply.
	SupplyLimit uint64 `json:"supplyLimit"`

	// Pyth oracle price update account.
	PythOraclePriceUpdate solanago.PublicKey `json:"pythOraclePriceUpdate"`

	// Pyth oracle price feed id.
	PythOracleFeedId solanago.PublicKey `json:"pythOracleFeedId"`

	// Reserved
	Reserved [184]uint8 `json:"reserved"`
}

func (obj Vault) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Version`:
	err = encoder.Encode(obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `DepositedFunds`:
	err = encoder.Encode(obj.DepositedFunds)
	if err != nil {
		return errors.NewField("DepositedFunds", err)
	}
	// Serialize `DepositedShares`:
	err = encoder.Encode(obj.DepositedShares)
	if err != nil {
		return errors.NewField("DepositedShares", err)
	}
	// Serialize `BorrowedFunds`:
	err = encoder.Encode(obj.BorrowedFunds)
	if err != nil {
		return errors.NewField("BorrowedFunds", err)
	}
	// Serialize `BorrowedShares`:
	err = encoder.Encode(obj.BorrowedShares)
	if err != nil {
		return errors.NewField("BorrowedShares", err)
	}
	// Serialize `UnpaidDebtShares`:
	err = encoder.Encode(obj.UnpaidDebtShares)
	if err != nil {
		return errors.NewField("UnpaidDebtShares", err)
	}
	// Serialize `InterestRate`:
	err = encoder.Encode(obj.InterestRate)
	if err != nil {
		return errors.NewField("InterestRate", err)
	}
	// Serialize `LastUpdateTimestamp`:
	err = encoder.Encode(obj.LastUpdateTimestamp)
	if err != nil {
		return errors.NewField("LastUpdateTimestamp", err)
	}
	// Serialize `SupplyLimit`:
	err = encoder.Encode(obj.SupplyLimit)
	if err != nil {
		return errors.NewField("SupplyLimit", err)
	}
	// Serialize `PythOraclePriceUpdate`:
	err = encoder.Encode(obj.PythOraclePriceUpdate)
	if err != nil {
		return errors.NewField("PythOraclePriceUpdate", err)
	}
	// Serialize `PythOracleFeedId`:
	err = encoder.Encode(obj.PythOracleFeedId)
	if err != nil {
		return errors.NewField("PythOracleFeedId", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj Vault) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Vault: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Vault) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Version`:
	err = decoder.Decode(&obj.Version)
	if err != nil {
		return errors.NewField("Version", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `DepositedFunds`:
	err = decoder.Decode(&obj.DepositedFunds)
	if err != nil {
		return errors.NewField("DepositedFunds", err)
	}
	// Deserialize `DepositedShares`:
	err = decoder.Decode(&obj.DepositedShares)
	if err != nil {
		return errors.NewField("DepositedShares", err)
	}
	// Deserialize `BorrowedFunds`:
	err = decoder.Decode(&obj.BorrowedFunds)
	if err != nil {
		return errors.NewField("BorrowedFunds", err)
	}
	// Deserialize `BorrowedShares`:
	err = decoder.Decode(&obj.BorrowedShares)
	if err != nil {
		return errors.NewField("BorrowedShares", err)
	}
	// Deserialize `UnpaidDebtShares`:
	err = decoder.Decode(&obj.UnpaidDebtShares)
	if err != nil {
		return errors.NewField("UnpaidDebtShares", err)
	}
	// Deserialize `InterestRate`:
	err = decoder.Decode(&obj.InterestRate)
	if err != nil {
		return errors.NewField("InterestRate", err)
	}
	// Deserialize `LastUpdateTimestamp`:
	err = decoder.Decode(&obj.LastUpdateTimestamp)
	if err != nil {
		return errors.NewField("LastUpdateTimestamp", err)
	}
	// Deserialize `SupplyLimit`:
	err = decoder.Decode(&obj.SupplyLimit)
	if err != nil {
		return errors.NewField("SupplyLimit", err)
	}
	// Deserialize `PythOraclePriceUpdate`:
	err = decoder.Decode(&obj.PythOraclePriceUpdate)
	if err != nil {
		return errors.NewField("PythOraclePriceUpdate", err)
	}
	// Deserialize `PythOracleFeedId`:
	err = decoder.Decode(&obj.PythOracleFeedId)
	if err != nil {
		return errors.NewField("PythOracleFeedId", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *Vault) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Vault: %w", err)
	}
	return nil
}

func UnmarshalVault(buf []byte) (*Vault, error) {
	obj := new(Vault)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Whirlpool struct {
	WhirlpoolsConfig           solanago.PublicKey     `json:"whirlpoolsConfig"`
	WhirlpoolBump              [1]uint8               `json:"whirlpoolBump"`
	TickSpacing                uint16                 `json:"tickSpacing"`
	FeeTierIndexSeed           [2]uint8               `json:"feeTierIndexSeed"`
	FeeRate                    uint16                 `json:"feeRate"`
	ProtocolFeeRate            uint16                 `json:"protocolFeeRate"`
	Liquidity                  binary.Uint128         `json:"liquidity"`
	SqrtPrice                  binary.Uint128         `json:"sqrtPrice"`
	TickCurrentIndex           int32                  `json:"tickCurrentIndex"`
	ProtocolFeeOwedA           uint64                 `json:"protocolFeeOwedA"`
	ProtocolFeeOwedB           uint64                 `json:"protocolFeeOwedB"`
	TokenMintA                 solanago.PublicKey     `json:"tokenMintA"`
	TokenVaultA                solanago.PublicKey     `json:"tokenVaultA"`
	FeeGrowthGlobalA           binary.Uint128         `json:"feeGrowthGlobalA"`
	TokenMintB                 solanago.PublicKey     `json:"tokenMintB"`
	TokenVaultB                solanago.PublicKey     `json:"tokenVaultB"`
	FeeGrowthGlobalB           binary.Uint128         `json:"feeGrowthGlobalB"`
	RewardLastUpdatedTimestamp uint64                 `json:"rewardLastUpdatedTimestamp"`
	RewardInfos                [3]WhirlpoolRewardInfo `json:"rewardInfos"`
}

func (obj Whirlpool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WhirlpoolsConfig`:
	err = encoder.Encode(obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Serialize `WhirlpoolBump`:
	err = encoder.Encode(obj.WhirlpoolBump)
	if err != nil {
		return errors.NewField("WhirlpoolBump", err)
	}
	// Serialize `TickSpacing`:
	err = encoder.Encode(obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Serialize `FeeTierIndexSeed`:
	err = encoder.Encode(obj.FeeTierIndexSeed)
	if err != nil {
		return errors.NewField("FeeTierIndexSeed", err)
	}
	// Serialize `FeeRate`:
	err = encoder.Encode(obj.FeeRate)
	if err != nil {
		return errors.NewField("FeeRate", err)
	}
	// Serialize `ProtocolFeeRate`:
	err = encoder.Encode(obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Serialize `Liquidity`:
	err = encoder.Encode(obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Serialize `SqrtPrice`:
	err = encoder.Encode(obj.SqrtPrice)
	if err != nil {
		return errors.NewField("SqrtPrice", err)
	}
	// Serialize `TickCurrentIndex`:
	err = encoder.Encode(obj.TickCurrentIndex)
	if err != nil {
		return errors.NewField("TickCurrentIndex", err)
	}
	// Serialize `ProtocolFeeOwedA`:
	err = encoder.Encode(obj.ProtocolFeeOwedA)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedA", err)
	}
	// Serialize `ProtocolFeeOwedB`:
	err = encoder.Encode(obj.ProtocolFeeOwedB)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedB", err)
	}
	// Serialize `TokenMintA`:
	err = encoder.Encode(obj.TokenMintA)
	if err != nil {
		return errors.NewField("TokenMintA", err)
	}
	// Serialize `TokenVaultA`:
	err = encoder.Encode(obj.TokenVaultA)
	if err != nil {
		return errors.NewField("TokenVaultA", err)
	}
	// Serialize `FeeGrowthGlobalA`:
	err = encoder.Encode(obj.FeeGrowthGlobalA)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalA", err)
	}
	// Serialize `TokenMintB`:
	err = encoder.Encode(obj.TokenMintB)
	if err != nil {
		return errors.NewField("TokenMintB", err)
	}
	// Serialize `TokenVaultB`:
	err = encoder.Encode(obj.TokenVaultB)
	if err != nil {
		return errors.NewField("TokenVaultB", err)
	}
	// Serialize `FeeGrowthGlobalB`:
	err = encoder.Encode(obj.FeeGrowthGlobalB)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalB", err)
	}
	// Serialize `RewardLastUpdatedTimestamp`:
	err = encoder.Encode(obj.RewardLastUpdatedTimestamp)
	if err != nil {
		return errors.NewField("RewardLastUpdatedTimestamp", err)
	}
	// Serialize `RewardInfos`:
	err = encoder.Encode(obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	return nil
}

func (obj Whirlpool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Whirlpool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Whirlpool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WhirlpoolsConfig`:
	err = decoder.Decode(&obj.WhirlpoolsConfig)
	if err != nil {
		return errors.NewField("WhirlpoolsConfig", err)
	}
	// Deserialize `WhirlpoolBump`:
	err = decoder.Decode(&obj.WhirlpoolBump)
	if err != nil {
		return errors.NewField("WhirlpoolBump", err)
	}
	// Deserialize `TickSpacing`:
	err = decoder.Decode(&obj.TickSpacing)
	if err != nil {
		return errors.NewField("TickSpacing", err)
	}
	// Deserialize `FeeTierIndexSeed`:
	err = decoder.Decode(&obj.FeeTierIndexSeed)
	if err != nil {
		return errors.NewField("FeeTierIndexSeed", err)
	}
	// Deserialize `FeeRate`:
	err = decoder.Decode(&obj.FeeRate)
	if err != nil {
		return errors.NewField("FeeRate", err)
	}
	// Deserialize `ProtocolFeeRate`:
	err = decoder.Decode(&obj.ProtocolFeeRate)
	if err != nil {
		return errors.NewField("ProtocolFeeRate", err)
	}
	// Deserialize `Liquidity`:
	err = decoder.Decode(&obj.Liquidity)
	if err != nil {
		return errors.NewField("Liquidity", err)
	}
	// Deserialize `SqrtPrice`:
	err = decoder.Decode(&obj.SqrtPrice)
	if err != nil {
		return errors.NewField("SqrtPrice", err)
	}
	// Deserialize `TickCurrentIndex`:
	err = decoder.Decode(&obj.TickCurrentIndex)
	if err != nil {
		return errors.NewField("TickCurrentIndex", err)
	}
	// Deserialize `ProtocolFeeOwedA`:
	err = decoder.Decode(&obj.ProtocolFeeOwedA)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedA", err)
	}
	// Deserialize `ProtocolFeeOwedB`:
	err = decoder.Decode(&obj.ProtocolFeeOwedB)
	if err != nil {
		return errors.NewField("ProtocolFeeOwedB", err)
	}
	// Deserialize `TokenMintA`:
	err = decoder.Decode(&obj.TokenMintA)
	if err != nil {
		return errors.NewField("TokenMintA", err)
	}
	// Deserialize `TokenVaultA`:
	err = decoder.Decode(&obj.TokenVaultA)
	if err != nil {
		return errors.NewField("TokenVaultA", err)
	}
	// Deserialize `FeeGrowthGlobalA`:
	err = decoder.Decode(&obj.FeeGrowthGlobalA)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalA", err)
	}
	// Deserialize `TokenMintB`:
	err = decoder.Decode(&obj.TokenMintB)
	if err != nil {
		return errors.NewField("TokenMintB", err)
	}
	// Deserialize `TokenVaultB`:
	err = decoder.Decode(&obj.TokenVaultB)
	if err != nil {
		return errors.NewField("TokenVaultB", err)
	}
	// Deserialize `FeeGrowthGlobalB`:
	err = decoder.Decode(&obj.FeeGrowthGlobalB)
	if err != nil {
		return errors.NewField("FeeGrowthGlobalB", err)
	}
	// Deserialize `RewardLastUpdatedTimestamp`:
	err = decoder.Decode(&obj.RewardLastUpdatedTimestamp)
	if err != nil {
		return errors.NewField("RewardLastUpdatedTimestamp", err)
	}
	// Deserialize `RewardInfos`:
	err = decoder.Decode(&obj.RewardInfos)
	if err != nil {
		return errors.NewField("RewardInfos", err)
	}
	return nil
}

func (obj *Whirlpool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Whirlpool: %w", err)
	}
	return nil
}

func UnmarshalWhirlpool(buf []byte) (*Whirlpool, error) {
	obj := new(Whirlpool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Stores the state relevant for tracking liquidity mining rewards at the `Whirlpool` level.
// These values are used in conjunction with `PositionRewardInfo`, `Tick.reward_growths_outside`,
// and `Whirlpool.reward_last_updated_timestamp` to determine how many rewards are earned by open
// positions.
type WhirlpoolRewardInfo struct {
	// Reward token mint.
	Mint solanago.PublicKey `json:"mint"`

	// Reward vault token account.
	Vault solanago.PublicKey `json:"vault"`

	// Authority account that has permission to initialize the reward and set emissions.
	Authority solanago.PublicKey `json:"authority"`

	// Q64.64 number that indicates how many tokens per second are earned per unit of liquidity.
	EmissionsPerSecondX64 binary.Uint128 `json:"emissionsPerSecondX64"`

	// Q64.64 number that tracks the total tokens earned per unit of liquidity since the reward
	// emissions were turned on.
	GrowthGlobalX64 binary.Uint128 `json:"growthGlobalX64"`
}

func (obj WhirlpoolRewardInfo) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Vault`:
	err = encoder.Encode(obj.Vault)
	if err != nil {
		return errors.NewField("Vault", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `EmissionsPerSecondX64`:
	err = encoder.Encode(obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	// Serialize `GrowthGlobalX64`:
	err = encoder.Encode(obj.GrowthGlobalX64)
	if err != nil {
		return errors.NewField("GrowthGlobalX64", err)
	}
	return nil
}

func (obj WhirlpoolRewardInfo) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WhirlpoolRewardInfo: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WhirlpoolRewardInfo) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Vault`:
	err = decoder.Decode(&obj.Vault)
	if err != nil {
		return errors.NewField("Vault", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `EmissionsPerSecondX64`:
	err = decoder.Decode(&obj.EmissionsPerSecondX64)
	if err != nil {
		return errors.NewField("EmissionsPerSecondX64", err)
	}
	// Deserialize `GrowthGlobalX64`:
	err = decoder.Decode(&obj.GrowthGlobalX64)
	if err != nil {
		return errors.NewField("GrowthGlobalX64", err)
	}
	return nil
}

func (obj *WhirlpoolRewardInfo) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WhirlpoolRewardInfo: %w", err)
	}
	return nil
}

func UnmarshalWhirlpoolRewardInfo(buf []byte) (*WhirlpoolRewardInfo, error) {
	obj := new(WhirlpoolRewardInfo)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
